/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Std Cn15.c                            *
* Font:        HelveticaNeueLT Std Cn                                *
* Height:      15                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 15                                            *
* Range disabled: 0000 - FFFF                                        *
* Character enabled:   0x43 (67)                                     *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\WB\MDK5\connect.txt                          *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\WB\MDK5\fonts_all.txt                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn15;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0021[  9] = { /* code 0021, EXCLAMATION MARK */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0022[  4] = { /* code 0022, QUOTATION MARK */
  X__X____,
  X__X____,
  X__X____,
  X__X____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0025[  9] = { /* code 0025, PERCENT SIGN */
  XXX___X_,
  X_X__X__,
  X_X__X__,
  X_X_X___,
  XX__X_XX,
  ___X_X_X,
  __XX_X_X,
  __X__X_X,
  _X___XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0028[ 12] = { /* code 0028, LEFT PARENTHESIS */
  __X_____,
  _XX_____,
  _X______,
  _X______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______,
  _X______,
  _XX_____,
  __X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0029[ 12] = { /* code 0029, RIGHT PARENTHESIS */
  X_______,
  XX______,
  _X______,
  _X______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _X______,
  _X______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_002E[  1] = { /* code 002E, FULL STOP */
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_002F[  9] = { /* code 002F, SOLIDUS */
  ___X____,
  __XX____,
  __X_____,
  __X_____,
  _XX_____,
  _X______,
  _X______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0030[  9] = { /* code 0030, DIGIT ZERO */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0031[  9] = { /* code 0031, DIGIT ONE */
  __XX____,
  __XX____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0032[  9] = { /* code 0032, DIGIT TWO */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  ____XX__,
  ___XX___,
  __XXX___,
  _XXX____,
  _XX_____,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0033[  9] = { /* code 0033, DIGIT THREE */
  _XXXX___,
  XX__XX__,
  ____XX__,
  ____X___,
  __XXX___,
  ____XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0034[  9] = { /* code 0034, DIGIT FOUR */
  ___XX___,
  __XXX___,
  __XXX___,
  _X_XX___,
  _X_XX___,
  X__XX___,
  XXXXXX__,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0035[  9] = { /* code 0035, DIGIT FIVE */
  _XXXXX__,
  _X______,
  XX______,
  XXXXX___,
  XX__XX__,
  ____XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0036[  9] = { /* code 0036, DIGIT SIX */
  _XXXX___,
  XX__XX__,
  XX______,
  XXXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _X__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0037[  9] = { /* code 0037, DIGIT SEVEN */
  XXXXXX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0038[  9] = { /* code 0038, DIGIT EIGHT */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXX____,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0039[  9] = { /* code 0039, DIGIT NINE */
  _XXXX___,
  XX__X___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ____XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_003A[  6] = { /* code 003A, COLON */
  XX______,
  ________,
  ________,
  ________,
  ________,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0040[ 18] = { /* code 0040, COMMERCIAL AT */
  __XXXXX_,________,
  _X_____X,________,
  X__XXX__,X_______,
  X_X__XX_,X_______,
  X_X__X__,X_______,
  X_X__X_X,________,
  X__XXXX_,________,
  _X_____X,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0041[  9] = { /* code 0041, LATIN CAPITAL LETTER A */
  __XXX___,
  __X_X___,
  __X_X___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XXXXX__,
  XX___XX_,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0042[  9] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXX____,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XXXX____,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0043[  9] = { /* code 0043, LATIN CAPITAL LETTER C */
  _XXXX___,
  _X__XX__,
  XX__XX__,
  XX______,
  XX______,
  XX______,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0044[  9] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXX___,
  XX__X___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__X___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0045[  9] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0046[  9] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0047[  9] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXXX__,
  _X___XX_,
  XX___XX_,
  XX______,
  XX_XXX__,
  XX___X__,
  XX__XX__,
  _X__XX__,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0048[  9] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XXXXX___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XX_XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0049[  9] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_004A[  9] = { /* code 004A, LATIN CAPITAL LETTER J */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  XX_XX___,
  XX_XX___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_004B[  9] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX__XX__,
  XX_XX___,
  XX_XX___,
  XXXX____,
  XXXX____,
  XX_XX___,
  XX_XX___,
  XX__XX__,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_004C[  9] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_004D[  9] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_004E[  9] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX__XX_,
  XXX__XX_,
  XXX__XX_,
  XXXX_XX_,
  XX_X_XX_,
  XX_XXXX_,
  XX__XXX_,
  XX__XXX_,
  XX__XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_004F[  9] = { /* code 004F, LATIN CAPITAL LETTER O */
  _XXXXX__,
  _X___X__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _X___X__,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0050[  9] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXX____,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XXXX____,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0051[ 10] = { /* code 0051, LATIN CAPITAL LETTER Q */
  _XXXXX__,
  _X___X__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _X___X__,
  _XXXXXX_,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0052[  9] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXX____,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XXX_____,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XX_XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0053[  9] = { /* code 0053, LATIN CAPITAL LETTER S */
  _XXXX___,
  XX__XX__,
  XX______,
  XXX_____,
  _XXXX___,
  ___XXX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0054[  9] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0055[  9] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0056[  9] = { /* code 0056, LATIN CAPITAL LETTER V */
  XX__XX__,
  XX__XX__,
  _X__X___,
  _X__X___,
  _XX_X___,
  _XXXX___,
  _XXXX___,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0057[ 18] = { /* code 0057, LATIN CAPITAL LETTER W */
  XX__X__X,X_______,
  XX_XXX_X,X_______,
  XX_X_X_X,X_______,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  __XX_XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0058[  9] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXX__XX_,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  __XXX___,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0059[  9] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XX__XX__,
  XX__XX__,
  _XXXX___,
  _XXXX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_005A[  9] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXX___,
  ___XX___,
  __XX____,
  __XX____,
  __X_____,
  _XX_____,
  _XX_____,
  XX______,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_005C[  9] = { /* code 005C, REVERSE SOLIDUS */
  X_______,
  XX______,
  _X______,
  _X______,
  _XX_____,
  __X_____,
  __X_____,
  __XX____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_005F[  1] = { /* code 005F, LOW LINE */
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0061[  7] = { /* code 0061, LATIN SMALL LETTER A */
  _XXXX___,
  _X__XX__,
  ___XXX__,
  _XXXXX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0062[  9] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,
  XX______,
  XXXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0063[  7] = { /* code 0063, LATIN SMALL LETTER C */
  _XXXX___,
  XX__XX__,
  XX______,
  XX______,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0064[  9] = { /* code 0064, LATIN SMALL LETTER D */
  ____XX__,
  ____XX__,
  _XXXXX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0065[  7] = { /* code 0065, LATIN SMALL LETTER E */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XXXXXX__,
  XX______,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0066[  9] = { /* code 0066, LATIN SMALL LETTER F */
  __XX____,
  _XX_____,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0067[ 10] = { /* code 0067, LATIN SMALL LETTER G */
  _XXXXX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ____XX__,
  ____XX__,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0068[  9] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,
  XX______,
  XXXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0069[  9] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_006A[ 12] = { /* code 006A, LATIN SMALL LETTER J */
  _XX_____,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_006B[  9] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,
  XX______,
  XX_XXX__,
  XX_XX___,
  XXXX____,
  XXXX____,
  XX_XX___,
  XX_XX___,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_006C[  9] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_006D[  7] = { /* code 006D, LATIN SMALL LETTER M */
  XXXX_XX_,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_006E[  7] = { /* code 006E, LATIN SMALL LETTER N */
  XXXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_006F[  7] = { /* code 006F, LATIN SMALL LETTER O */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0070[ 10] = { /* code 0070, LATIN SMALL LETTER P */
  XXXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XXXXX___,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0071[ 10] = { /* code 0071, LATIN SMALL LETTER Q */
  _XXXXX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ____XX__,
  ____XX__,
  ____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0072[  7] = { /* code 0072, LATIN SMALL LETTER R */
  XXXX____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0073[  7] = { /* code 0073, LATIN SMALL LETTER S */
  _XXXX___,
  XX__X___,
  XXX_____,
  _XXX____,
  ___XX___,
  _X_XX___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0074[  9] = { /* code 0074, LATIN SMALL LETTER T */
  _XX_____,
  _XX_____,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0075[  7] = { /* code 0075, LATIN SMALL LETTER U */
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0076[  7] = { /* code 0076, LATIN SMALL LETTER V */
  XX_XX___,
  XX_XX___,
  _X_X____,
  _X_X____,
  _X_X____,
  _XXX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0077[ 14] = { /* code 0077, LATIN SMALL LETTER W */
  XX_XXX_X,X_______,
  XX_X_X_X,X_______,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _X_X_X_X,________,
  _XXX_XXX,________,
  __XX_XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0078[  7] = { /* code 0078, LATIN SMALL LETTER X */
  XX__XX__,
  _XXXX___,
  __XX____,
  __XX____,
  _XXXX___,
  _XXXX___,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_0079[ 10] = { /* code 0079, LATIN SMALL LETTER Y */
  XX_XX___,
  XX_XX___,
  _X_X____,
  _X_X____,
  _X_X____,
  _XXX____,
  _XXX____,
  __X_____,
  __X_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_007A[  7] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXX___,
  ___XX___,
  __XX____,
  _XXX____,
  _XX_____,
  XX______,
  XXXXX___};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn15_00B0[  4] = { /* code 00B0, DEGREE SIGN */
  _X______,
  X_X_____,
  X_X_____,
  _X______};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHelveticaNeueLTStdCn15_CharInfo[76] = {
   {   1,   1,   0,  12,   9, acGUI_FontHelveticaNeueLTStdCn15_0020 } /* code 0020, SPACE */
  ,{   2,   9,   1,   3,   4, acGUI_FontHelveticaNeueLTStdCn15_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   4,   4,   1,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0022 } /* code 0022, QUOTATION MARK */
  ,{   8,   9,   1,   3,  10, acGUI_FontHelveticaNeueLTStdCn15_0025 } /* code 0025, PERCENT SIGN */
  ,{   3,  12,   0,   3,   4, acGUI_FontHelveticaNeueLTStdCn15_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   3,  12,   0,   3,   4, acGUI_FontHelveticaNeueLTStdCn15_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   4,   1,   0,   8,   5, acGUI_FontHelveticaNeueLTStdCn15_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   1,   1,  11,   3, acGUI_FontHelveticaNeueLTStdCn15_002E } /* code 002E, FULL STOP */
  ,{   4,   9,   0,   3,   4, acGUI_FontHelveticaNeueLTStdCn15_002F } /* code 002F, SOLIDUS */
  ,{   6,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0030 } /* code 0030, DIGIT ZERO */
  ,{   4,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0031 } /* code 0031, DIGIT ONE */
  ,{   6,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0032 } /* code 0032, DIGIT TWO */
  ,{   6,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0033 } /* code 0033, DIGIT THREE */
  ,{   6,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0034 } /* code 0034, DIGIT FOUR */
  ,{   6,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0035 } /* code 0035, DIGIT FIVE */
  ,{   6,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0036 } /* code 0036, DIGIT SIX */
  ,{   6,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0037 } /* code 0037, DIGIT SEVEN */
  ,{   6,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0038 } /* code 0038, DIGIT EIGHT */
  ,{   6,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0039 } /* code 0039, DIGIT NINE */
  ,{   2,   6,   1,   6,   3, acGUI_FontHelveticaNeueLTStdCn15_003A } /* code 003A, COLON */
  ,{   9,   9,   1,   3,  10, acGUI_FontHelveticaNeueLTStdCn15_0040 } /* code 0040, COMMERCIAL AT */
  ,{   7,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   6,   9,   1,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   6,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   6,   9,   1,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   5,   9,   1,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   5,   9,   1,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   7,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   5,   9,   1,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,   9,   1,   3,   3, acGUI_FontHelveticaNeueLTStdCn15_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   5,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   6,   9,   1,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   5,   9,   1,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   8,   9,   1,   3,  10, acGUI_FontHelveticaNeueLTStdCn15_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   7,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   7,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   5,   9,   1,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   7,  10,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   5,   9,   1,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   6,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   6,   9,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   6,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   6,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{   9,   9,   0,   3,  10, acGUI_FontHelveticaNeueLTStdCn15_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   7,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   6,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   5,   9,   1,   3,   6, acGUI_FontHelveticaNeueLTStdCn15_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   4,   9,   0,   3,   4, acGUI_FontHelveticaNeueLTStdCn15_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   6,   1,   0,  13,   7, acGUI_FontHelveticaNeueLTStdCn15_005F } /* code 005F, LOW LINE */
  ,{   6,   7,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn15_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   6,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   6,   7,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn15_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   6,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   6,   7,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn15_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   4,   9,   0,   3,   4, acGUI_FontHelveticaNeueLTStdCn15_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   6,  10,   0,   5,   7, acGUI_FontHelveticaNeueLTStdCn15_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   6,   9,   0,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,   9,   1,   3,   3, acGUI_FontHelveticaNeueLTStdCn15_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   3,  12,   0,   3,   3, acGUI_FontHelveticaNeueLTStdCn15_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   6,   9,   1,   3,   7, acGUI_FontHelveticaNeueLTStdCn15_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   2,   9,   1,   3,   3, acGUI_FontHelveticaNeueLTStdCn15_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   8,   7,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn15_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   6,   7,   0,   5,   7, acGUI_FontHelveticaNeueLTStdCn15_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   6,   7,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn15_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   6,  10,   0,   5,   7, acGUI_FontHelveticaNeueLTStdCn15_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   6,  10,   0,   5,   7, acGUI_FontHelveticaNeueLTStdCn15_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   4,   7,   0,   5,   4, acGUI_FontHelveticaNeueLTStdCn15_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   5,   7,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn15_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   4,   9,   0,   3,   4, acGUI_FontHelveticaNeueLTStdCn15_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   6,   7,   0,   5,   7, acGUI_FontHelveticaNeueLTStdCn15_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   5,   7,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn15_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{   9,   7,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn15_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   6,   7,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn15_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   5,  10,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn15_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   5,   7,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn15_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   3,   4,   1,   3,   5, acGUI_FontHelveticaNeueLTStdCn15_00B0 } /* code 00B0, DEGREE SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn15_Prop9 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn15_CharInfo[ 75] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn15_Prop8 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn15_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn15_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn15_Prop7 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn15_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn15_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn15_Prop6 = {
   0x005C /* first character */
  ,0x005C /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn15_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn15_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn15_Prop5 = {
   0x0040 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn15_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn15_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn15_Prop4 = {
   0x002D /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn15_CharInfo[  6] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn15_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn15_Prop3 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn15_CharInfo[  4] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn15_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn15_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn15_CharInfo[  3] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn15_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn15_Prop1 = {
   0x0020 /* first character */
  ,0x0022 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn15_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn15_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn15 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,15 /* height of font  */
  ,15 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTStdCn15_Prop1}
  ,12 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,9 /* Height of capital characters */
};

