/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Std Cn34.c                            *
* Font:        HelveticaNeueLT Std Cn                                *
* Height:      34                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 34                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\WB\MDK5\fonts_all.txt                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn34;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0021[ 21] = { /* code 0021, EXCLAMATION MARK */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  _XX_____,
  ________,
  ________,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0022[ 18] = { /* code 0022, QUOTATION MARK */
  XXXX_XXX,X_______,
  XXXX_XXX,X_______,
  XXXX_XXX,X_______,
  XXXX_XXX,X_______,
  XXXX_XXX,X_______,
  XXXX_XXX,X_______,
  XXXX_XXX,X_______,
  XXXX_XXX,X_______,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0025[ 66] = { /* code 0025, PERCENT SIGN */
  __XXXX__,______XX,XX______,
  _XXXXXX_,______XX,X_______,
  XXX__XXX,_____XXX,________,
  XXX__XXX,_____XXX,________,
  XXX__XXX,____XXX_,________,
  XXX__XXX,____XXX_,________,
  XXX__XXX,___XXX__,________,
  XXX__XXX,___XX___,________,
  XXX__XXX,__XXX___,________,
  XXX__XXX,__XX____,________,
  _XXXXXX_,_XXX____,________,
  __XXXX__,XXX___XX,XXX_____,
  ________,XX___XXX,XXXX____,
  _______X,XX__XXX_,__XXX___,
  _______X,X___XXX_,__XXX___,
  ______XX,X___XXX_,__XXX___,
  ______XX,____XXX_,__XXX___,
  _____XXX,____XXX_,__XXX___,
  _____XX_,____XXX_,__XXX___,
  ____XX__,_____XXX,XXXX____,
  ____XX__,______XX,XXX_____,
  ___X____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0028[ 27] = { /* code 0028, LEFT PARENTHESIS */
  ____XXX_,
  ___XXXX_,
  ___XXX__,
  __XXXX__,
  __XXX___,
  __XXX___,
  _XXXX___,
  _XXX____,
  _XXX____,
  _XXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXXX___,
  __XXX___,
  __XXX___,
  __XXXX__,
  ___XXX__,
  ___XXX__,
  ____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0029[ 27] = { /* code 0029, RIGHT PARENTHESIS */
  XXX_____,
  XXXX____,
  _XXX____,
  _XXXX___,
  __XXX___,
  __XXX___,
  __XXXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  __XXXX__,
  __XXX___,
  __XXX___,
  _XXXX___,
  _XXX____,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_002D[  3] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_002E[  4] = { /* code 002E, FULL STOP */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_002F[ 42] = { /* code 002F, SOLIDUS */
  ______XX,XX______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ____XXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0030[ 42] = { /* code 0030, DIGIT ZERO */
  ____XXXX,________,
  __XXXXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXX__X,XXX_____,
  _XXX____,XXX_____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXX____,XXX_____,
  _XXXX__X,XXX_____,
  _XXXXXXX,XX______,
  __XXXXXX,XX______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0031[ 21] = { /* code 0031, DIGIT ONE */
  _____XXX,
  _____XXX,
  ____XXXX,
  ___XXXXX,
  XXXXXXXX,
  XXXXXXXX,
  XXXXXXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0032[ 42] = { /* code 0032, DIGIT TWO */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXX___,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  ________,_XXXX___,
  ________,XXXX____,
  ________,XXXX____,
  ______XX,XXXX____,
  _____XXX,XXX_____,
  ____XXXX,XX______,
  ___XXXXX,X_______,
  __XXXXXX,________,
  __XXXXX_,________,
  _XXXXX__,________,
  _XXXX___,________,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0033[ 42] = { /* code 0033, DIGIT THREE */
  ____XXXX,X_______,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXXX___,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  _______X,XXX_____,
  ____XXXX,XX______,
  ____XXXX,XX______,
  ____XXXX,XXX_____,
  _______X,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXXX__X,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0034[ 42] = { /* code 0034, DIGIT FOUR */
  ______XX,XXX_____,
  ______XX,XXX_____,
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  ____XXXX,XXX_____,
  ____XXXX,XXX_____,
  ___XXX_X,XXX_____,
  ___XXX_X,XXX_____,
  __XXX__X,XXX_____,
  __XXX__X,XXX_____,
  _XXX___X,XXX_____,
  _XXX___X,XXX_____,
  XXX____X,XXX_____,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0035[ 42] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX__XX,XX______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  XXXXX___,XXXX____,
  XXXX____,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXXX___,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0036[ 42] = { /* code 0036, DIGIT SIX */
  _____XXX,X_______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  _XXXX___,XXXXX___,
  _XXX____,_XXXX___,
  _XXX____,_XXXX___,
  XXXX____,________,
  XXXX____,________,
  XXXX__XX,XX______,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXX___,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,XXXX____,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0037[ 42] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  ________,_XXX____,
  ________,XXXX____,
  _______X,XXX_____,
  _______X,XXX_____,
  ______XX,XX______,
  ______XX,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0038[ 42] = { /* code 0038, DIGIT EIGHT */
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  _XXXXX__,XXXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  __XXXX__,XXXX____,
  __XXXXXX,XXX_____,
  ____XXXX,XX______,
  __XXXXXX,XXXX____,
  _XXXX___,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0039[ 42] = { /* code 0039, DIGIT NINE */
  _____XXX,X_______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXX___,XXXX____,
  XXXX____,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,XXXXX___,
  XXXXX___,XXXXX___,
  _XXXXXXX,XXXXX___,
  _XXXXXXX,XXXXX___,
  ___XXXX_,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  _XXXX___,_XXX____,
  _XXXX___,XXXX____,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_003A[ 15] = { /* code 003A, COLON */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0040[ 63] = { /* code 0040, COMMERCIAL AT */
  _______X,XXXX____,________,
  _____XXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XX______,
  ___XXXX_,______XX,XX______,
  __XXXX__,_______X,XXX_____,
  _XXXX___,XXXX__XX,XXXX____,
  _XXX__XX,XXXXX_XX,_XXXX___,
  _XXX_XXX,XXXXXXXX,__XXX___,
  XXX__XXX,X__XXXXX,__XXX___,
  XXX_XXXX,____XXX_,__XXX___,
  XXX_XXX_,____XXX_,__XXX___,
  XXX_XXX_,____XXX_,__XX____,
  XXX_XXX_,____XXX_,_XXX____,
  _XX_XXXX,___XXXX_,_XX_____,
  _XXX_XXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XX__XXX_,___X____,
  ___XXXX_,_______X,XXX_____,
  ____XXXX,XXXXXXXX,XX______,
  _____XXX,XXXXXXXX,________,
  ________,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0041[ 42] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  ____XXXX,XXXX____,
  ____XXX_,_XXX____,
  ____XXX_,_XXX____,
  ____XXX_,_XXX____,
  ___XXXX_,_XXXX___,
  ___XXXX_,_XXXX___,
  ___XXX__,_XXXX___,
  ___XXX__,__XXX___,
  __XXXX__,__XXXX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXX_,
  _XXXX___,___XXXX_,
  _XXXX___,___XXXX_,
  _XXXX___,___XXXX_,
  XXXXX___,___XXXXX,
  XXXX____,____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0042[ 42] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXXX,XX______,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXX____,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXX____,
  XXXX____,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,_XXXXX__,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0043[ 42] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,X_______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,XXXX____,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0044[ 42] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXXX,X_______,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0045[ 42] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0046[ 42] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0047[ 42] = { /* code 0047, LATIN CAPITAL LETTER G */
  _____XXX,XX______,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXXX___,
  _XXXXX__,_XXXX___,
  _XXXX___,_XXXXX__,
  _XXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX___X,XXXXXX__,
  XXXX___X,XXXXXX__,
  XXXX___X,XXXXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  _XXXX___,__XXXX__,
  _XXXX___,_XXXXX__,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XX_XXX__,
  ____XXXX,X__XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0048[ 42] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0049[ 21] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_004A[ 42] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXXX__X,XXXX____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_004B[ 42] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXXX____,_XXXXX__,
  XXXX____,XXXXX___,
  XXXX____,XXXX____,
  XXXX___X,XXXX____,
  XXXX__XX,XXX_____,
  XXXX__XX,XX______,
  XXXX_XXX,XX______,
  XXXX_XXX,X_______,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXX_XX,XX______,
  XXXXX_XX,XX______,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXXX____,
  XXXX____,XXXXX___,
  XXXX____,XXXXX___,
  XXXX____,_XXXXX__,
  XXXX____,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_004C[ 42] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_004D[ 63] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXXXXX__,_____XXX,XXX_____,
  XXXXXXX_,____XXXX,XXX_____,
  XXXXXXX_,____XXXX,XXX_____,
  XXXXXXX_,____XXXX,XXX_____,
  XXXXXXX_,____XXXX,XXX_____,
  XXXXXXXX,___XXXXX,XXX_____,
  XXXX_XXX,___XXX_X,XXX_____,
  XXXX_XXX,___XXX_X,XXX_____,
  XXXX_XXX,___XXX_X,XXX_____,
  XXXX_XXX,___XXX_X,XXX_____,
  XXXX_XXX,X_XXXX_X,XXX_____,
  XXXX__XX,X_XXX__X,XXX_____,
  XXXX__XX,X_XXX__X,XXX_____,
  XXXX__XX,X_XXX__X,XXX_____,
  XXXX__XX,X_XXX__X,XXX_____,
  XXXX___X,XXXX___X,XXX_____,
  XXXX___X,XXXX___X,XXX_____,
  XXXX___X,XXXX___X,XXX_____,
  XXXX___X,XXXX___X,XXX_____,
  XXXX___X,XXXX___X,XXX_____,
  XXXX____,XXX____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_004E[ 42] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXXXX___,__XXXX__,
  XXXXX___,__XXXX__,
  XXXXXX__,__XXXX__,
  XXXXXX__,__XXXX__,
  XXXXXX__,__XXXX__,
  XXXXXXX_,__XXXX__,
  XXXXXXX_,__XXXX__,
  XXXXXXXX,__XXXX__,
  XXXX_XXX,__XXXX__,
  XXXX_XXX,__XXXX__,
  XXXX_XXX,X_XXXX__,
  XXXX__XX,X_XXXX__,
  XXXX__XX,X_XXXX__,
  XXXX___X,XXXXXX__,
  XXXX___X,XXXXXX__,
  XXXX___X,XXXXXX__,
  XXXX____,XXXXXX__,
  XXXX____,XXXXXX__,
  XXXX____,XXXXXX__,
  XXXX____,_XXXXX__,
  XXXX____,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_004F[ 42] = { /* code 004F, LATIN CAPITAL LETTER O */
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0050[ 42] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXX____,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,X_______,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0051[ 46] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  __XXXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ____XXXX,XXXXXXX_,
  ________,___XXX__,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0052[ 42] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXXX,XX______,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXX____,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,XXXX____,
  XXXX____,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0053[ 42] = { /* code 0053, LATIN CAPITAL LETTER S */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  XXXXX___,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,________,
  XXXXX___,________,
  _XXXXXX_,________,
  _XXXXXXX,XX______,
  __XXXXXX,XXX_____,
  ____XXXX,XXXX____,
  ______XX,XXXXX___,
  ________,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXXX___,XXXXX___,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0054[ 42] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0055[ 42] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0056[ 42] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXXX___,__XXXXX_,
  XXXXX___,__XXXXX_,
  _XXXX___,__XXXX__,
  _XXXX___,__XXXX__,
  _XXXX___,__XXXX__,
  _XXXXX__,__XXXX__,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXXX_,_XXXX___,
  ___XXXX_,XXXX____,
  ___XXXX_,XXXX____,
  ___XXXX_,XXXX____,
  ___XXXX_,XXXX____,
  ____XXXX,XXX_____,
  ____XXXX,XXX_____,
  ____XXXX,XXX_____,
  ____XXXX,XXX_____,
  _____XXX,XX______,
  _____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0057[ 63] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXX____,_XXXX___,_XXXX___,
  XXXX____,XXXXX___,_XXXX___,
  XXXX____,XXXXX___,_XXXX___,
  _XXX____,XXXXX___,_XXX____,
  _XXXX___,XXXXX___,XXXX____,
  _XXXX___,XXXXX___,XXXX____,
  _XXXX___,XX_XX___,XXXX____,
  _XXXX__X,XX_XXX__,XXXX____,
  __XXX__X,XX_XXX__,XXX_____,
  __XXX__X,XX_XXX__,XXX_____,
  __XXX__X,XX_XXX__,XXX_____,
  __XXXX_X,XX_XXX_X,XXX_____,
  __XXXX_X,X___XX_X,XXX_____,
  __XXXX_X,X___XX_X,XXX_____,
  ___XXXXX,X___XXXX,XX______,
  ___XXXXX,X___XXXX,XX______,
  ___XXXXX,X___XXXX,XX______,
  ___XXXXX,X___XXXX,XX______,
  ___XXXXX,X___XXXX,XX______,
  ___XXXXX,_____XXX,XX______,
  ____XXXX,_____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0058[ 42] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXXXX___,__XXXXX_,
  _XXXXX__,__XXXX__,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXXX_,XXXXX___,
  ___XXXX_,XXXX____,
  ___XXXX_,XXXX____,
  ____XXXX,XXX_____,
  ____XXXX,XXX_____,
  _____XXX,XX______,
  _____XXX,XX______,
  _____XXX,XX______,
  ____XXXX,XXX_____,
  ____XXXX,XXX_____,
  ___XXXX_,XXXX____,
  ___XXXX_,XXXX____,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  _XXXXX__,_XXXXX__,
  _XXXX___,__XXXX__,
  XXXXX___,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0059[ 42] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXXXX___,__XXXX__,
  XXXXX___,_XXXXX__,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  ___XXXXX,XXX_____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______,
  ____XXXX,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_005A[ 42] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _______X,XXX_____,
  _______X,XXX_____,
  ______XX,XX______,
  ______XX,XX______,
  _____XXX,XX______,
  _____XXX,X_______,
  ____XXXX,X_______,
  ____XXXX,________,
  ___XXXXX,________,
  ___XXXX_,________,
  __XXXXX_,________,
  __XXXX__,________,
  _XXXXX__,________,
  _XXXX___,________,
  XXXXX___,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_005C[ 42] = { /* code 005C, REVERSE SOLIDUS */
  XXXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0061[ 30] = { /* code 0061, LATIN SMALL LETTER A */
  ___XXXXX,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  XXXX___X,XXX_____,
  _______X,XXX_____,
  _____XXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXX_X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXX_X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0062[ 42] = { /* code 0062, LATIN SMALL LETTER B */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX_XXX,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XXXXX__X,XXX_____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXXX__X,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0063[ 30] = { /* code 0063, LATIN SMALL LETTER C */
  ____XXXX,X_______,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXXX__X,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXXX___,XXXX____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0064[ 42] = { /* code 0064, LATIN SMALL LETTER D */
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ___XXXX_,XXXX____,
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXX__X,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXXX__X,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  ___XXXX_,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0065[ 30] = { /* code 0065, LATIN SMALL LETTER E */
  ____XXXX,________,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXXX__X,XXX_____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,XXXX____,
  _XXXX__X,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0066[ 21] = { /* code 0066, LATIN SMALL LETTER F */
  ____XXXX,
  ___XXXXX,
  __XXXXXX,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  XXXXXXXX,
  XXXXXXXX,
  XXXXXXXX,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0067[ 42] = { /* code 0067, LATIN SMALL LETTER G */
  ___XXXX_,XXXX____,
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXX__X,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXXX__X,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  ___XXX__,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  XXXX___X,XXX_____,
  XXXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0068[ 42] = { /* code 0068, LATIN SMALL LETTER H */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX__XX,XX______,
  XXXX_XXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXXX___,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0069[ 21] = { /* code 0069, LATIN SMALL LETTER I */
  XXXX____,
  XXXX____,
  XXXX____,
  ________,
  ________,
  ________,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_006A[ 27] = { /* code 006A, LATIN SMALL LETTER J */
  __XXXX__,
  __XXXX__,
  __XXXX__,
  ________,
  ________,
  ________,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  XXXXXX__,
  XXXXX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_006B[ 42] = { /* code 006B, LATIN SMALL LETTER K */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,XXXX____,
  XXXX___X,XXX_____,
  XXXX__XX,XX______,
  XXXX__XX,XX______,
  XXXX_XXX,X_______,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXX_XX,XX______,
  XXXX__XX,XX______,
  XXXX___X,XXX_____,
  XXXX___X,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_006C[ 21] = { /* code 006C, LATIN SMALL LETTER L */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_006D[ 45] = { /* code 006D, LATIN SMALL LETTER M */
  XXXX__XX,XX____XX,XX______,
  XXXXXXXX,XXX__XXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXX___,XXXXX___,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_006E[ 30] = { /* code 006E, LATIN SMALL LETTER N */
  XXXX__XX,XX______,
  XXXX_XXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXXX___,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_006F[ 30] = { /* code 006F, LATIN SMALL LETTER O */
  ____XXXX,________,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXXX__X,XXX_____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXXX__X,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0070[ 42] = { /* code 0070, LATIN SMALL LETTER P */
  XXXX_XXX,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XXXXX__X,XXX_____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXXX__X,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  XXXX_XXX,X_______,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0071[ 42] = { /* code 0071, LATIN SMALL LETTER Q */
  ___XXXX_,XXXX____,
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXX__X,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXXX__X,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  ___XXXX_,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0072[ 15] = { /* code 0072, LATIN SMALL LETTER R */
  XXXX__XX,
  XXXX_XXX,
  XXXXXXXX,
  XXXXXXXX,
  XXXXX___,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0073[ 30] = { /* code 0073, LATIN SMALL LETTER S */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXXX__,________,
  __XXXXXX,________,
  ___XXXXX,XXX_____,
  _____XXX,XXX_____,
  _______X,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0074[ 19] = { /* code 0074, LATIN SMALL LETTER T */
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  XXXXXXXX,
  XXXXXXXX,
  XXXXXXXX,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXXXX,
  __XXXXXX,
  ___XXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0075[ 30] = { /* code 0075, LATIN SMALL LETTER U */
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX___X,XXXX____,
  XXXXXXXX,XXXX____,
  _XXXXXX_,XXXX____,
  __XXXX__,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0076[ 30] = { /* code 0076, LATIN SMALL LETTER V */
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXX____,XXX_____,
  _XXXX___,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  __XXX__X,XX______,
  __XXX__X,XX______,
  __XXXX_X,XX______,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0077[ 45] = { /* code 0077, LATIN SMALL LETTER W */
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  _XXX___X,XXXXX___,XXX_____,
  _XXXX__X,XXXXX___,XXX_____,
  _XXXX__X,XXXXX__X,XXX_____,
  _XXXX__X,XXXXX__X,XXX_____,
  __XXX__X,XX_XX__X,XX______,
  __XXX__X,X__XXX_X,XX______,
  __XXX_XX,X__XXX_X,XX______,
  __XXXXXX,X__XXX_X,XX______,
  __XXXXXX,X__XXXXX,XX______,
  ___XXXXX,X__XXXXX,X_______,
  ___XXXXX,____XXXX,X_______,
  ___XXXXX,____XXXX,X_______,
  ___XXXXX,____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0078[ 30] = { /* code 0078, LATIN SMALL LETTER X */
  XXXXX___,XXXXX___,
  _XXXX___,XXXX____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  ___XXX_X,XX______,
  ___XXXXX,XX______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXXXX,XX______,
  ___XXX_X,XX______,
  __XXXX_X,XXX_____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  XXXX____,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_0079[ 42] = { /* code 0079, LATIN SMALL LETTER Y */
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXX____,XXX_____,
  _XXXX___,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  __XXX__X,XX______,
  __XXX__X,XX______,
  __XXXX_X,XX______,
  ___XXX_X,XX______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_007A[ 30] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  ______XX,XX______,
  _____XXX,XX______,
  _____XXX,X_______,
  ____XXXX,________,
  ___XXXXX,________,
  ___XXXX_,________,
  __XXXX__,________,
  _XXXXX__,________,
  _XXXX___,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn34_00B0[  9] = { /* code 00B0, DEGREE SIGN */
  __XXXX__,
  _XXXXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHelveticaNeueLTStdCn34_CharInfo[76] = {
   {   1,   1,   0,  28,  8, acGUI_FontHelveticaNeueLTStdCn34_0020 } /* code 0020, SPACE */
  ,{   4,  21,   2,   7,   9, acGUI_FontHelveticaNeueLTStdCn34_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   9,   9,   2,   7,  13, acGUI_FontHelveticaNeueLTStdCn34_0022 } /* code 0022, QUOTATION MARK */
  ,{  21,  22,   1,   7,  23, acGUI_FontHelveticaNeueLTStdCn34_0025 } /* code 0025, PERCENT SIGN */
  ,{   7,  27,   1,   7,   9, acGUI_FontHelveticaNeueLTStdCn34_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   7,  27,   0,   7,   9, acGUI_FontHelveticaNeueLTStdCn34_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   8,   3,   1,  18,  11, acGUI_FontHelveticaNeueLTStdCn34_002D } /* code 002D, HYPHEN-MINUS */
  ,{   4,   4,   1,  24,   7, acGUI_FontHelveticaNeueLTStdCn34_002E } /* code 002E, FULL STOP */
  ,{  10,  21,   0,   7,  10, acGUI_FontHelveticaNeueLTStdCn34_002F } /* code 002F, SOLIDUS */
  ,{  12,  21,   1,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  21,   1,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0031 } /* code 0031, DIGIT ONE */
  ,{  13,  21,   0,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0032 } /* code 0032, DIGIT TWO */
  ,{  12,  21,   1,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0033 } /* code 0033, DIGIT THREE */
  ,{  13,  21,   1,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0034 } /* code 0034, DIGIT FOUR */
  ,{  13,  21,   0,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0035 } /* code 0035, DIGIT FIVE */
  ,{  13,  21,   0,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0036 } /* code 0036, DIGIT SIX */
  ,{  13,  21,   0,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0037 } /* code 0037, DIGIT SEVEN */
  ,{  13,  21,   0,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0038 } /* code 0038, DIGIT EIGHT */
  ,{  13,  21,   0,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0039 } /* code 0039, DIGIT NINE */
  ,{   4,  15,   1,  13,   7, acGUI_FontHelveticaNeueLTStdCn34_003A } /* code 003A, COLON */
  ,{  21,  21,   1,   7,  23, acGUI_FontHelveticaNeueLTStdCn34_0040 } /* code 0040, COMMERCIAL AT */
  ,{  16,  21,   0,   7,  16, acGUI_FontHelveticaNeueLTStdCn34_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  14,  21,   1,   7,  16, acGUI_FontHelveticaNeueLTStdCn34_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  13,  21,   1,   7,  16, acGUI_FontHelveticaNeueLTStdCn34_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  13,  21,   2,   7,  17, acGUI_FontHelveticaNeueLTStdCn34_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  12,  21,   1,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  11,  21,   1,   7,  13, acGUI_FontHelveticaNeueLTStdCn34_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  14,  21,   1,   7,  16, acGUI_FontHelveticaNeueLTStdCn34_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  13,  21,   1,   7,  16, acGUI_FontHelveticaNeueLTStdCn34_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   4,  21,   2,   7,   7, acGUI_FontHelveticaNeueLTStdCn34_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  12,  21,   0,   7,  13, acGUI_FontHelveticaNeueLTStdCn34_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  14,  21,   1,   7,  16, acGUI_FontHelveticaNeueLTStdCn34_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{  11,  21,   1,   7,  13, acGUI_FontHelveticaNeueLTStdCn34_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  19,  21,   1,   7,  21, acGUI_FontHelveticaNeueLTStdCn34_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  14,  21,   1,   7,  17, acGUI_FontHelveticaNeueLTStdCn34_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  14,  21,   1,   7,  16, acGUI_FontHelveticaNeueLTStdCn34_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  13,  21,   1,   7,  15, acGUI_FontHelveticaNeueLTStdCn34_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  15,  23,   1,   7,  16, acGUI_FontHelveticaNeueLTStdCn34_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  14,  21,   1,   7,  16, acGUI_FontHelveticaNeueLTStdCn34_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  13,  21,   1,   7,  15, acGUI_FontHelveticaNeueLTStdCn34_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  12,  21,   1,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  13,  21,   1,   7,  16, acGUI_FontHelveticaNeueLTStdCn34_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  15,  21,   0,   7,  15, acGUI_FontHelveticaNeueLTStdCn34_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  21,  21,   0,   7,  22, acGUI_FontHelveticaNeueLTStdCn34_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  15,  21,   0,   7,  16, acGUI_FontHelveticaNeueLTStdCn34_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  14,  21,   0,   7,  15, acGUI_FontHelveticaNeueLTStdCn34_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  12,  21,   1,   7,  14, acGUI_FontHelveticaNeueLTStdCn34_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{  10,  21,   0,   7,  10, acGUI_FontHelveticaNeueLTStdCn34_005C } /* code 005C, REVERSE SOLIDUS */
  ,{  14,   1,   0,  30,  15, acGUI_FontHelveticaNeueLTStdCn34_005F } /* code 005F, LOW LINE */
  ,{  11,  15,   1,  13,  14, acGUI_FontHelveticaNeueLTStdCn34_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{  12,  21,   1,   7,  15, acGUI_FontHelveticaNeueLTStdCn34_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{  12,  15,   1,  13,  13, acGUI_FontHelveticaNeueLTStdCn34_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{  12,  21,   1,   7,  15, acGUI_FontHelveticaNeueLTStdCn34_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{  12,  15,   1,  13,  13, acGUI_FontHelveticaNeueLTStdCn34_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   8,  21,   0,   7,   9, acGUI_FontHelveticaNeueLTStdCn34_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{  12,  21,   1,  13,  15, acGUI_FontHelveticaNeueLTStdCn34_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{  12,  21,   1,   7,  15, acGUI_FontHelveticaNeueLTStdCn34_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   4,  21,   1,   7,   7, acGUI_FontHelveticaNeueLTStdCn34_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   6,  27,  -1,   7,   7, acGUI_FontHelveticaNeueLTStdCn34_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  13,  21,   1,   7,  15, acGUI_FontHelveticaNeueLTStdCn34_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   4,  21,   1,   7,   7, acGUI_FontHelveticaNeueLTStdCn34_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  20,  15,   1,  13,  22, acGUI_FontHelveticaNeueLTStdCn34_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{  12,  15,   1,  13,  15, acGUI_FontHelveticaNeueLTStdCn34_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{  12,  15,   1,  13,  14, acGUI_FontHelveticaNeueLTStdCn34_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{  12,  21,   1,  13,  15, acGUI_FontHelveticaNeueLTStdCn34_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{  12,  21,   1,  13,  15, acGUI_FontHelveticaNeueLTStdCn34_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   8,  15,   1,  13,  10, acGUI_FontHelveticaNeueLTStdCn34_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{  12,  15,   0,  13,  13, acGUI_FontHelveticaNeueLTStdCn34_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   8,  19,   0,   9,   9, acGUI_FontHelveticaNeueLTStdCn34_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{  12,  15,   1,  13,  15, acGUI_FontHelveticaNeueLTStdCn34_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  12,  15,   0,  13,  13, acGUI_FontHelveticaNeueLTStdCn34_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  20,  15,   0,  13,  20, acGUI_FontHelveticaNeueLTStdCn34_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{  13,  15,   0,  13,  13, acGUI_FontHelveticaNeueLTStdCn34_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{  12,  21,   0,  13,  13, acGUI_FontHelveticaNeueLTStdCn34_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{  11,  15,   1,  13,  12, acGUI_FontHelveticaNeueLTStdCn34_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   8,   9,   2,   7,  12, acGUI_FontHelveticaNeueLTStdCn34_00B0 } /* code 00B0, DEGREE SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn34_Prop9 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn34_CharInfo[ 75] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn34_Prop8 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn34_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn34_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn34_Prop7 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn34_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn34_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn34_Prop6 = {
   0x005C /* first character */
  ,0x005C /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn34_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn34_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn34_Prop5 = {
   0x0040 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn34_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn34_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn34_Prop4 = {
   0x002D /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn34_CharInfo[  6] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn34_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn34_Prop3 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn34_CharInfo[  4] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn34_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn34_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn34_CharInfo[  3] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn34_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn34_Prop1 = {
   0x0020 /* first character */
  ,0x0022 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn34_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn34_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn34 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,34 /* height of font  */
  ,34 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTStdCn34_Prop1}
  ,28 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,21 /* Height of capital characters */
};

