/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Std Med Cn30.c                        *
* Font:        HelveticaNeueLT Std Med Cn                            *
* Height:      30                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 30                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\WB\MDK5\fonts_all.txt                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdMedCn30;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0021[ 18] = { /* code 0021, EXCLAMATION MARK */
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  _XXXX___,
  _XXX____,
  ________,
  _XXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0022[ 18] = { /* code 0022, QUOTATION MARK */
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XX___XX,________,
  XXX__XXX,________,
  XXX__XXX,________,
  XXX__XXX,________,
  XXX__XXX,________,
  XXX__XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0025[ 54] = { /* code 0025, PERCENT SIGN */
  ___XXXX_,_____XXX,________,
  __XXXXXX,_____XX_,________,
  _XXX__XX,____XXX_,________,
  _XXX__XX,___XXX__,________,
  XXX__XXX,___XX___,________,
  XXX__XXX,__XXX___,________,
  XXX__XXX,_XXX____,________,
  XXX__XXX,_XX_____,________,
  XXXXXXX_,XXX_____,________,
  _XXXXX__,XX__XXXX,X_______,
  _______X,X__XXXXX,XX______,
  ______XX,X_XXX__X,XX______,
  ______XX,__XXX__X,XX______,
  _____XXX,__XXX__X,XX______,
  ____XXX_,__XXX__X,X_______,
  ____XX__,__XXX_XX,X_______,
  ___XXX__,__XXXXXX,X_______,
  __XXX___,___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0028[ 46] = { /* code 0028, LEFT PARENTHESIS */
  _____XXX,X_______,
  _____XXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  __XXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0029[ 46] = { /* code 0029, RIGHT PARENTHESIS */
  ____XXXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,X_______,
  _____XXX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ____XXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXX___,________,
  _XXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_002D[  3] = { /* code 002D, HYPHEN-MINUS */
  _XXXXXXX,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_002E[  5] = { /* code 002E, FULL STOP */
  _XXXX___,
  _XXXX___,
  _XXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_002F[ 36] = { /* code 002F, SOLIDUS */
  ________,_XXX____,
  ________,XXX_____,
  ________,XXX_____,
  _______X,XX______,
  _______X,XX______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  ____XXXX,________,
  ____XXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXX___,________,
  _XXXX___,________,
  _XXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0030[ 36] = { /* code 0030, DIGIT ZERO */
  ______XX,XX______,
  ____XXXX,XXX_____,
  ___XXXXX,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXX____,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XX______,
  XXXX__XX,XX______,
  XXXXXXXX,X_______,
  _XXXXXXX,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0031[ 18] = { /* code 0031, DIGIT ONE */
  _____XXX,
  _____XXX,
  ___XXXXX,
  XXXXXXX_,
  XXXXXXX_,
  XXXXXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXX___,
  _XXXX___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0032[ 36] = { /* code 0032, DIGIT TWO */
  ______XX,XXX_____,
  ____XXXX,XXXXX___,
  ____XXXX,XXXXX___,
  ___XXXX_,_XXXX___,
  ___XXX__,_XXXX___,
  __XXXX__,_XXXX___,
  ________,_XXXX___,
  ________,XXXXX___,
  _______X,XXXX____,
  ______XX,XXX_____,
  _____XXX,XX______,
  ____XXXX,X_______,
  ___XXXXX,________,
  __XXXXX_,________,
  _XXXXX__,________,
  _XXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0033[ 36] = { /* code 0033, DIGIT THREE */
  _____XXX,XX______,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXX___,XXXX____,
  _XXX____,XXXX____,
  ________,XXXX____,
  ________,XXX_____,
  _____XXX,XX______,
  _____XXX,XX______,
  ____XXXX,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XX______,
  XXXXXXXX,XX______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0034[ 36] = { /* code 0034, DIGIT FOUR */
  ________,XXXXX___,
  ________,XXXXX___,
  _______X,XXXXX___,
  ______XX,XXXX____,
  ______XX,XXXX____,
  _____XXX,XXXX____,
  ____XXX_,XXXX____,
  ___XXXX_,XXXX____,
  ___XXX__,XXXX____,
  __XXX___,XXX_____,
  _XXXX__X,XXX_____,
  _XXXXXXX,XXXXX___,
  _XXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____,
  _______X,XXX_____,
  _______X,XX______,
  ______XX,XX______,
  ______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0035[ 36] = { /* code 0035, DIGIT FIVE */
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXX___,________,
  _XXX____,________,
  _XXX__XX,XX______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  _______X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XX______,
  XXXX__XX,XX______,
  XXXXXXXX,X_______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0036[ 36] = { /* code 0036, DIGIT SIX */
  ______XX,XX______,
  ____XXXX,XXXX____,
  ___XXXXX,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  _XXXX___,________,
  _XXXX_XX,XX______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXX__X,XXX_____,
  XXXXX__X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XX______,
  XXXXXXXX,X_______,
  _XXXXXXX,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0037[ 36] = { /* code 0037, DIGIT SEVEN */
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXX_____,
  _______X,XXX_____,
  ______XX,XX______,
  ______XX,X_______,
  _____XXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0038[ 36] = { /* code 0038, DIGIT EIGHT */
  _____XXX,XX______,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXX__,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  _XXXXXXX,XXX_____,
  _XXXX__X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XX______,
  XXXXXXXX,XX______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0039[ 36] = { /* code 0039, DIGIT NINE */
  ______XX,XX______,
  ____XXXX,XXX_____,
  ___XXXXX,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX__X,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXX_X,XXX_____,
  _______X,XXX_____,
  XXXX___X,XX______,
  XXXX__XX,XX______,
  XXXXXXXX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_003A[ 14] = { /* code 003A, COLON */
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _XXXX___,
  _XXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0040[ 54] = { /* code 0040, COMMERCIAL AT */
  ________,_XXXXX__,________,
  _______X,XXXXXXXX,________,
  _____XXX,X_____XX,X_______,
  ____XXXX,_______X,XX______,
  ___XXX__,________,XX______,
  ___XX___,_XXX____,XXX_____,
  __XXX__X,XXXXXXXX,_XX_____,
  _XXX__XX,XXXXXXX_,_XX_____,
  _XXX_XXX,X___XXX_,_XX_____,
  _XX__XXX,____XX__,XX______,
  _XX__XX_,____XX__,XX______,
  XXX_XXX_,__XXX__X,X_______,
  _XXX_XXX,XXXXXXXX,________,
  _XXX_XXX,XX_XXXX_,________,
  __XXX_XX,X__XX___,X_______,
  __XXXX__,_____XXX,________,
  ____XXXX,XXXXXX__,________,
  ______XX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0041[ 36] = { /* code 0041, LATIN CAPITAL LETTER A */
  _______X,XXXXX___,
  _______X,XXXXX___,
  _______X,XXXXX___,
  ______XX,X_XXX___,
  ______XX,X_XXX___,
  _____XXX,X_XXX___,
  _____XXX,__XXX___,
  _____XXX,__XXX___,
  ____XXXX,__XXX___,
  ____XXX_,__XXX___,
  ___XXXX_,__XXX___,
  ___XXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __XXX___,__XXXX__,
  _XXXX___,__XXXX__,
  _XXXX___,__XXXX__,
  XXXX____,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0042[ 36] = { /* code 0042, LATIN CAPITAL LETTER B */
  ___XXXXX,XXXX____,
  ___XXXXX,XXXXXX__,
  ___XXXXX,XXXXXX__,
  ___XXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,_XXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXX_____,
  __XXXXXX,XXXX____,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,XXXX____,
  _XXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0043[ 36] = { /* code 0043, LATIN CAPITAL LETTER C */
  ______XX,XXX_____,
  ____XXXX,XXXX____,
  ___XXXXX,XXXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXX____,________,
  XXXX____,________,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX___X,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0044[ 36] = { /* code 0044, LATIN CAPITAL LETTER D */
  ___XXXXX,XXXX____,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXXX__,
  ___XXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXX___,__XXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0045[ 36] = { /* code 0045, LATIN CAPITAL LETTER E */
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0046[ 36] = { /* code 0046, LATIN CAPITAL LETTER F */
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0047[ 36] = { /* code 0047, LATIN CAPITAL LETTER G */
  ______XX,XXX_____,
  ____XXXX,XXXX____,
  ___XXXXX,XXXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX__X,XXXXX___,
  _XXX__XX,XXXX____,
  XXXX__XX,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX___X,XXXX____,
  XXXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXX__,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0048[ 36] = { /* code 0048, LATIN CAPITAL LETTER H */
  ___XXXX_,___XXXX_,
  ___XXXX_,___XXXX_,
  ___XXXX_,___XXXX_,
  ___XXX__,___XXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XXXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXX____,_XXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0049[ 18] = { /* code 0049, LATIN CAPITAL LETTER I */
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_004A[ 36] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XX______,
  XXXXXXXX,XX______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_004B[ 36] = { /* code 004B, LATIN CAPITAL LETTER K */
  ___XXXX_,___XXXXX,
  ___XXXX_,__XXXX__,
  ___XXXX_,_XXXXX__,
  ___XXX__,_XXXX___,
  __XXXX__,XXXX____,
  __XXXX_X,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX__X,XXXX____,
  _XXX____,XXXX____,
  XXXX____,XXXXX___,
  XXXX____,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_004C[ 36] = { /* code 004C, LATIN CAPITAL LETTER L */
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_004D[ 54] = { /* code 004D, LATIN CAPITAL LETTER M */
  ___XXXXX,X____XXX,XXX_____,
  ___XXXXX,X___XXXX,XXX_____,
  ___XXXXX,X___XXXX,XXX_____,
  ___XXXXX,X___XXXX,XX______,
  __XXXXXX,X__XXXXX,XX______,
  __XXX_XX,X__XXXXX,XX______,
  __XXX_XX,X__XXXXX,XX______,
  __XXX_XX,X_XXX_XX,XX______,
  __XXX_XX,X_XXX_XX,XX______,
  __XX__XX,X_XX__XX,X_______,
  _XXX__XX,XXXX_XXX,X_______,
  _XXX__XX,XXXX_XXX,X_______,
  _XXX__XX,XXX__XXX,X_______,
  _XXX__XX,XXX__XXX,X_______,
  _XXX__XX,XXX__XXX,X_______,
  _XX___XX,XX___XXX,________,
  XXX___XX,XX__XXXX,________,
  XXX___XX,X___XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_004E[ 36] = { /* code 004E, LATIN CAPITAL LETTER N */
  ___XXXX_,___XXXX_,
  ___XXXXX,___XXXX_,
  ___XXXXX,___XXXX_,
  ___XXXXX,___XXX__,
  __XXXXXX,__XXXX__,
  __XXXXXX,__XXXX__,
  __XXXXXX,__XXXX__,
  __XXXXXX,__XXXX__,
  __XXX_XX,X_XXXX__,
  __XX__XX,X_XXX___,
  _XXX__XX,XXXXX___,
  _XXX__XX,XXXXX___,
  _XXX__XX,XXXXX___,
  _XXX__XX,XXXXX___,
  _XXX___X,XXXXX___,
  _XX____X,XXXX____,
  XXX____X,XXXX____,
  XXX____X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_004F[ 36] = { /* code 004F, LATIN CAPITAL LETTER O */
  ______XX,XX______,
  ____XXXX,XXXX____,
  ___XXXXX,XXXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXX____,_XXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXX_____,
  XXXX___X,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0050[ 36] = { /* code 0050, LATIN CAPITAL LETTER P */
  ___XXXXX,XXXX____,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXXX__,
  ___XXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,_XXXXX__,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXX____,
  _XXXXXXX,XX______,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0051[ 40] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ______XX,XX______,
  ____XXXX,XXXX____,
  ___XXXXX,XXXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXX____,_XXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXX_____,
  XXXX___X,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  ___XXXXX,XXXX____,
  ________,XXX_____,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0052[ 36] = { /* code 0052, LATIN CAPITAL LETTER R */
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXXX__,
  ___XXXXX,XXXXXX__,
  ___XXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,_XXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXX____,
  _XXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0053[ 36] = { /* code 0053, LATIN CAPITAL LETTER S */
  _____XXX,XX______,
  ___XXXXX,XXXX____,
  ___XXXXX,XXXX____,
  __XXXX__,XXXX____,
  __XXX___,XXXX____,
  _XXXX___,________,
  _XXXXX__,________,
  _XXXXXXX,________,
  __XXXXXX,XX______,
  ___XXXXX,XXX_____,
  _____XXX,XXXX____,
  _______X,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX___X,XXX_____,
  XXXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0054[ 36] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  ____XXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXX___,________,
  _XXXX___,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0055[ 36] = { /* code 0055, LATIN CAPITAL LETTER U */
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXX___,__XXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXX____,_XXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX___X,XXX_____,
  XXXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0056[ 36] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXXX___,_XXXX___,
  XXXXX___,XXXXX___,
  XXXXX___,XXXX____,
  XXXX____,XXXX____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XX______,
  _XXX__XX,XX______,
  _XXX__XX,X_______,
  _XXX_XXX,X_______,
  _XXX_XXX,X_______,
  _XXX_XXX,________,
  _XXXXXXX,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0057[ 54] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXX____,XXXX___X,XXX_____,
  XXXX___X,XXXX___X,XXX_____,
  XXXX___X,XXXX__XX,XX______,
  XXXX___X,XXXX__XX,XX______,
  XXXX__XX,XXX___XX,XX______,
  XXXX__XX,XXX___XX,X_______,
  XXXX__XX,_XX__XXX,X_______,
  XXXX_XXX,_XX__XXX,X_______,
  XXXX_XXX,_XX__XXX,________,
  XXXX_XX_,_XX_XXXX,________,
  XXXXXXX_,_XX_XXX_,________,
  XXXXXXX_,_XX_XXX_,________,
  XXXXXX__,XXX_XXX_,________,
  XXXXXX__,XXXXXX__,________,
  XXXXXX__,XXXXXX__,________,
  XXXXXX__,XXXXXX__,________,
  XXXXX___,XXXXX___,________,
  XXXXX___,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0058[ 54] = { /* code 0058, LATIN CAPITAL LETTER X */
  ____XXXX,____XXXX,X_______,
  ____XXXX,X__XXXXX,________,
  ____XXXX,X__XXXX_,________,
  _____XXX,X_XXXX__,________,
  _____XXX,X_XXXX__,________,
  _____XXX,XXXXX___,________,
  _____XXX,XXXXX___,________,
  ______XX,XXXX____,________,
  ______XX,XXX_____,________,
  ______XX,XXX_____,________,
  _____XXX,XXXX____,________,
  ____XXXX,XXXX____,________,
  ____XXXX,XXXX____,________,
  ___XXXX_,XXXX____,________,
  __XXXXX_,XXXXX___,________,
  __XXXX__,_XXXX___,________,
  _XXXXX__,_XXXX___,________,
  XXXXX___,_XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0059[ 36] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXXX____,XXXXX___,
  XXXX___X,XXXX____,
  XXXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX_XX,XX______,
  _XXXX_XX,X_______,
  _XXXXXXX,X_______,
  __XXXXXX,________,
  __XXXXXX,________,
  __XXXXX_,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXX___,________,
  _XXXX___,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_005A[ 36] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ____XXXX,XXXXXX__,
  ___XXXXX,XXXXXX__,
  ___XXXXX,XXXXXX__,
  ________,XXXXX___,
  ________,XXXX____,
  _______X,XXXX____,
  ______XX,XXX_____,
  ______XX,XX______,
  _____XXX,XX______,
  ____XXXX,X_______,
  ____XXXX,________,
  ___XXXXX,________,
  __XXXXX_,________,
  __XXXX__,________,
  _XXXXX__,________,
  _XXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_005C[ 18] = { /* code 005C, REVERSE SOLIDUS */
  XXXX____,
  XXXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXXX__,
  __XXXX__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0061[ 26] = { /* code 0061, LATIN SMALL LETTER A */
  ____XXXX,X_______,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _______X,XXX_____,
  ____XXXX,XX______,
  __XXXXXX,XX______,
  _XXXX__X,XX______,
  XXXX___X,XX______,
  XXXX___X,XX______,
  XXXX__XX,XX______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _XXX__XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0062[ 36] = { /* code 0062, LATIN SMALL LETTER B */
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,XXX_____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX__X,XXX_____,
  _XXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0063[ 26] = { /* code 0063, LATIN SMALL LETTER C */
  _____XXX,X_______,
  ___XXXXX,XX______,
  __XXXXXX,XX______,
  _XXXX__X,XX______,
  _XXXX__X,XX______,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX___X,XX______,
  XXXX__XX,X_______,
  XXXXXXXX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0064[ 36] = { /* code 0064, LATIN SMALL LETTER D */
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXX____,
  ________,XXXX____,
  ____XXX_,XXXX____,
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXX__X,XXXX____,
  _XXXX___,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  _XXX__XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0065[ 26] = { /* code 0065, LATIN SMALL LETTER E */
  _____XXX,X_______,
  ___XXXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX___,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXX____,________,
  XXXX___X,XX______,
  XXXX__XX,X_______,
  XXXXXXXX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0066[ 36] = { /* code 0066, LATIN SMALL LETTER F */
  _____XXX,X_______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ___XXXX_,________,
  __XXXX__,________,
  _XXXXXXX,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  __XXXX__,________,
  __XXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0067[ 36] = { /* code 0067, LATIN SMALL LETTER G */
  _____XXX,_XXXX___,
  ___XXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXX__,XXXXX___,
  __XXXX__,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX__X,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXX_X,XXX_____,
  _______X,XXX_____,
  ______XX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0068[ 36] = { /* code 0068, LATIN SMALL LETTER H */
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXXX___,
  __XXXX__,XXXXX___,
  __XXXX__,_XXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXX____,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0069[ 18] = { /* code 0069, LATIN SMALL LETTER I */
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ________,
  ________,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_006A[ 46] = { /* code 006A, LATIN SMALL LETTER J */
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ________,________,
  ________,________,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  _XXXXX__,________,
  _XXXXX__,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_006B[ 36] = { /* code 006B, LATIN SMALL LETTER K */
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,_XXXXX__,
  __XXXX__,XXXX____,
  __XXXX_X,XXX_____,
  __XXXXXX,XXX_____,
  __XXX_XX,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXXX_XX,XX______,
  _XXXX_XX,XXX_____,
  _XXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_006C[ 18] = { /* code 006C, LATIN SMALL LETTER L */
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_006D[ 39] = { /* code 006D, LATIN SMALL LETTER M */
  __XXXX__,XXXX___X,XXX_____,
  __XXXXXX,XXXX_XXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXX__,_XXXX___,XXXX____,
  __XXXX__,_XXXX___,XXX_____,
  _XXXX___,XXXX___X,XXX_____,
  _XXXX___,XXXX___X,XXX_____,
  _XXXX___,XXXX___X,XXX_____,
  _XXXX___,XXXX___X,XXX_____,
  _XXXX___,XXXX___X,XXX_____,
  _XXX____,XXX____X,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_006E[ 26] = { /* code 006E, LATIN SMALL LETTER N */
  __XXXX__,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXX____,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_006F[ 26] = { /* code 006F, LATIN SMALL LETTER O */
  _____XXX,X_______,
  ___XXXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XX______,
  XXXXXXXX,XX______,
  _XXXXXXX,X_______,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0070[ 36] = { /* code 0070, LATIN SMALL LETTER P */
  ___XXXX_,_XXX____,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ___XXXX_,_XXXX___,
  ___XXXX_,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,XXXX____,
  __XXXXXX,XXXX____,
  _XXXX_XX,XXX_____,
  _XXXX_XX,XX______,
  _XXXX___,________,
  _XXXX___,________,
  _XXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0071[ 36] = { /* code 0071, LATIN SMALL LETTER Q */
  ____XXX_,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  _XXXX__X,XXXX____,
  _XXXX___,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  __XXX_XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,X_______,
  _____XXX,X_______,
  _____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0072[ 26] = { /* code 0072, LATIN SMALL LETTER R */
  __XXXX__,XX______,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  __XXXX__,________,
  __XXXX__,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0073[ 26] = { /* code 0073, LATIN SMALL LETTER S */
  ____XXXX,________,
  __XXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXX___X,XX______,
  _XXX____,________,
  _XXXXXX_,________,
  _XXXXXXX,X_______,
  ___XXXXX,XX______,
  XXX____X,XX______,
  XXX___XX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0074[ 18] = { /* code 0074, LATIN SMALL LETTER T */
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXX__,
  __XXXX__,
  _XXXXXXX,
  XXXXXXXX,
  XXXXXXXX,
  __XXXX__,
  __XXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  XXXXXX__,
  _XXXXX__,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0075[ 26] = { /* code 0075, LATIN SMALL LETTER U */
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXX____,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  _XXXX_XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0076[ 26] = { /* code 0076, LATIN SMALL LETTER V */
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  _XXX___X,XX______,
  _XXX__XX,XX______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  _XXXXX__,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0077[ 39] = { /* code 0077, LATIN SMALL LETTER W */
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX__XX,XXX___XX,X_______,
  XXXX__XX,XXX__XXX,X_______,
  _XXX__XX,_XX__XXX,________,
  _XXX_XXX,_XX__XXX,________,
  _XXX_XXX,_XX_XXXX,________,
  _XXX_XX_,_XX_XXX_,________,
  _XXXXXX_,_XX_XXX_,________,
  _XXXXXX_,_XXXXX__,________,
  _XXXXX__,_XXXXX__,________,
  _XXXXX__,_XXXXX__,________,
  _XXXXX__,_XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0078[ 26] = { /* code 0078, LATIN SMALL LETTER X */
  ___XXXX_,__XXXX__,
  ___XXXX_,_XXXX___,
  ____XXX_,XXXX____,
  ____XXX_,XXX_____,
  ____XXXX,XXX_____,
  _____XXX,XX______,
  _____XXX,XX______,
  ____XXXX,XX______,
  ___XXXXX,XX______,
  ___XXX_X,XXX_____,
  __XXXX_X,XXX_____,
  _XXXX__X,XXX_____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_0079[ 36] = { /* code 0079, LATIN SMALL LETTER Y */
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  ___XXX__,_XXX____,
  ___XXX__,XXXX____,
  ___XXX__,XXX_____,
  ___XXX__,XXX_____,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ___XXXXX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ___XXXX_,________,
  _XXXXX__,________,
  _XXXXX__,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_007A[ 26] = { /* code 007A, LATIN SMALL LETTER Z */
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  ______XX,XXX_____,
  _____XXX,XX______,
  _____XXX,X_______,
  ____XXXX,________,
  ___XXXX_,________,
  __XXXXX_,________,
  _XXXXX__,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn30_00B0[  8] = { /* code 00B0, DEGREE SIGN */
  ___XXXX_,
  __XXXXXX,
  _XX___XX,
  _XX____X,
  XX____XX,
  _XX___XX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHelveticaNeueLTStdMedCn30_CharInfo[76] = {
   {   1,   1,   0,  24,  14, acGUI_FontHelveticaNeueLTStdMedCn30_0020 } /* code 0020, SPACE */
  ,{   7,  18,   2,   6,   8, acGUI_FontHelveticaNeueLTStdMedCn30_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   9,   9,   4,   6,  12, acGUI_FontHelveticaNeueLTStdMedCn30_0022 } /* code 0022, QUOTATION MARK */
  ,{  18,  18,   2,   6,  19, acGUI_FontHelveticaNeueLTStdMedCn30_0025 } /* code 0025, PERCENT SIGN */
  ,{   9,  23,   2,   6,   8, acGUI_FontHelveticaNeueLTStdMedCn30_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   9,  23,  -1,   6,   8, acGUI_FontHelveticaNeueLTStdMedCn30_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   8,   3,   2,  15,   9, acGUI_FontHelveticaNeueLTStdMedCn30_002D } /* code 002D, HYPHEN-MINUS */
  ,{   5,   5,   1,  19,   7, acGUI_FontHelveticaNeueLTStdMedCn30_002E } /* code 002E, FULL STOP */
  ,{  12,  18,   0,   6,   9, acGUI_FontHelveticaNeueLTStdMedCn30_002F } /* code 002F, SOLIDUS */
  ,{  12,  18,   2,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  18,   4,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0031 } /* code 0031, DIGIT ONE */
  ,{  13,  18,   1,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0032 } /* code 0032, DIGIT TWO */
  ,{  12,  18,   2,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0033 } /* code 0033, DIGIT THREE */
  ,{  13,  18,   1,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0034 } /* code 0034, DIGIT FOUR */
  ,{  12,  18,   2,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0035 } /* code 0035, DIGIT FIVE */
  ,{  12,  18,   2,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0036 } /* code 0036, DIGIT SIX */
  ,{  12,  18,   3,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0037 } /* code 0037, DIGIT SEVEN */
  ,{  12,  18,   2,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0038 } /* code 0038, DIGIT EIGHT */
  ,{  12,  18,   2,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0039 } /* code 0039, DIGIT NINE */
  ,{   6,  14,   1,  10,   7, acGUI_FontHelveticaNeueLTStdMedCn30_003A } /* code 003A, COLON */
  ,{  19,  18,   2,   6,  20, acGUI_FontHelveticaNeueLTStdMedCn30_0040 } /* code 0040, COMMERCIAL AT */
  ,{  14,  18,   0,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  14,  18,   1,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  13,  18,   2,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  14,  18,   1,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  13,  18,   1,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  13,  18,   1,   6,  12, acGUI_FontHelveticaNeueLTStdMedCn30_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  13,  18,   2,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  15,  18,   1,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   7,  18,   1,   6,   7, acGUI_FontHelveticaNeueLTStdMedCn30_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  13,  18,   1,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  16,  18,   1,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{  11,  18,   1,   6,  12, acGUI_FontHelveticaNeueLTStdMedCn30_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  19,  18,   2,   6,  19, acGUI_FontHelveticaNeueLTStdMedCn30_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  15,  18,   2,   6,  15, acGUI_FontHelveticaNeueLTStdMedCn30_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  13,  18,   2,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  14,  18,   1,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  13,  20,   2,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  14,  18,   1,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  12,  18,   2,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  12,  18,   3,   6,  12, acGUI_FontHelveticaNeueLTStdMedCn30_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  14,  18,   2,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  13,  18,   3,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  19,  18,   3,   6,  19, acGUI_FontHelveticaNeueLTStdMedCn30_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  17,  18,   0,   6,  14, acGUI_FontHelveticaNeueLTStdMedCn30_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  13,  18,   4,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  14,  18,   0,   6,  12, acGUI_FontHelveticaNeueLTStdMedCn30_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   6,  18,   3,   6,   9, acGUI_FontHelveticaNeueLTStdMedCn30_005C } /* code 005C, REVERSE SOLIDUS */
  ,{  12,   1,   0,  26,  13, acGUI_FontHelveticaNeueLTStdMedCn30_005F } /* code 005F, LOW LINE */
  ,{  11,  13,   2,  11,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{  12,  18,   1,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{  10,  13,   2,  11,  12, acGUI_FontHelveticaNeueLTStdMedCn30_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{  13,  18,   2,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{  11,  13,   2,  11,  12, acGUI_FontHelveticaNeueLTStdMedCn30_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   9,  18,   2,   6,   7, acGUI_FontHelveticaNeueLTStdMedCn30_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{  13,  18,   1,  11,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{  13,  18,   1,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   7,  18,   1,   6,   7, acGUI_FontHelveticaNeueLTStdMedCn30_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{  10,  23,  -2,   6,   7, acGUI_FontHelveticaNeueLTStdMedCn30_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  14,  18,   1,   6,  13, acGUI_FontHelveticaNeueLTStdMedCn30_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   7,  18,   1,   6,   7, acGUI_FontHelveticaNeueLTStdMedCn30_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  20,  13,   1,  11,  20, acGUI_FontHelveticaNeueLTStdMedCn30_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{  13,  13,   1,  11,  13, acGUI_FontHelveticaNeueLTStdMedCn30_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{  11,  13,   2,  11,  13, acGUI_FontHelveticaNeueLTStdMedCn30_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{  13,  18,   0,  11,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{  12,  18,   2,  11,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{  10,  13,   1,  11,   9, acGUI_FontHelveticaNeueLTStdMedCn30_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{  10,  13,   2,  11,  12, acGUI_FontHelveticaNeueLTStdMedCn30_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   8,  18,   2,   6,   8, acGUI_FontHelveticaNeueLTStdMedCn30_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{  12,  13,   2,  11,  13, acGUI_FontHelveticaNeueLTStdMedCn30_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  11,  13,   2,  11,  12, acGUI_FontHelveticaNeueLTStdMedCn30_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  18,  13,   2,  11,  19, acGUI_FontHelveticaNeueLTStdMedCn30_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{  14,  13,   0,  11,  12, acGUI_FontHelveticaNeueLTStdMedCn30_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{  13,  18,   0,  11,  12, acGUI_FontHelveticaNeueLTStdMedCn30_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{  12,  13,   1,  11,  12, acGUI_FontHelveticaNeueLTStdMedCn30_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   8,   8,   3,   6,  10, acGUI_FontHelveticaNeueLTStdMedCn30_00B0 } /* code 00B0, DEGREE SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn30_Prop9 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_CharInfo[ 75] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn30_Prop8 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn30_Prop7 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn30_Prop6 = {
   0x005C /* first character */
  ,0x005C /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn30_Prop5 = {
   0x0040 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn30_Prop4 = {
   0x002D /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_CharInfo[  6] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn30_Prop3 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_CharInfo[  4] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn30_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_CharInfo[  3] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn30_Prop1 = {
   0x0020 /* first character */
  ,0x0022 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn30_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdMedCn30 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,30 /* height of font  */
  ,30 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTStdMedCn30_Prop1}
  ,24 /* Baseline */
  ,13 /* Height of lowercase characters */
  ,18 /* Height of capital characters */
};

