/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Std Med Cn25.c                        *
* Font:        HelveticaNeueLT Std Med Cn                            *
* Height:      25                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 25                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\WB\MDK5\fonts_all.txt                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdMedCn25;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0021[ 16] = { /* code 0021, EXCLAMATION MARK */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0022[  6] = { /* code 0022, QUOTATION MARK */
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0025[ 32] = { /* code 0025, PERCENT SIGN */
  _XXXX___,__XX____,
  _X__X___,_XX_____,
  XX__XX__,_XX_____,
  XX__XX__,_X______,
  XX__XX__,XX______,
  XX__XX__,X_______,
  XX__XX_X,X_______,
  _X__X__X,________,
  _XXXX_XX,__XXXX__,
  ______XX,__X__X__,
  ______X_,_XX__XX_,
  _____XX_,_XX__XX_,
  _____X__,_XX__XX_,
  ____XX__,_XX__XX_,
  ____X___,__X__X__,
  ___XX___,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0028[ 20] = { /* code 0028, LEFT PARENTHESIS */
  ___X____,
  __XX____,
  __X_____,
  _XX_____,
  _XX_____,
  _X______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0029[ 20] = { /* code 0029, RIGHT PARENTHESIS */
  XX______,
  XX______,
  _X______,
  _XX_____,
  _XX_____,
  __X_____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __X_____,
  _XX_____,
  _XX_____,
  _X______,
  XX______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_002D[  2] = { /* code 002D, HYPHEN-MINUS */
  XXXXXX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_002E[  3] = { /* code 002E, FULL STOP */
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_002F[ 16] = { /* code 002F, SOLIDUS */
  _____XX_,
  _____X__,
  ____XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0030[ 16] = { /* code 0030, DIGIT ZERO */
  __XXXX__,
  _XXXXXX_,
  _XX__XX_,
  _X____X_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _X____X_,
  _XX__XX_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0031[ 16] = { /* code 0031, DIGIT ONE */
  ____X___,
  ___XX___,
  __XXX___,
  XXXXX___,
  XXXXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0032[ 16] = { /* code 0032, DIGIT TWO */
  __XXXX__,
  _XXXXXX_,
  _XX___XX,
  XX____XX,
  XX____XX,
  ______XX,
  ______XX,
  _____XX_,
  ____XXX_,
  ___XXX__,
  __XXX___,
  _XXX____,
  _XX_____,
  XXX_____,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0033[ 16] = { /* code 0033, DIGIT THREE */
  __XXXX__,
  _XXXXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  ______XX,
  _____XX_,
  ___XXXX_,
  ___XXXX_,
  _____XX_,
  ______XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0034[ 32] = { /* code 0034, DIGIT FOUR */
  _____XX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  _XX__XX_,________,
  _XX__XX_,________,
  XX___XX_,________,
  XX___XX_,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0035[ 16] = { /* code 0035, DIGIT FIVE */
  _XXXXXX_,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _X______,
  XX_XXX__,
  XXXXXXX_,
  XXX__XXX,
  ______XX,
  ______XX,
  ______XX,
  XX____XX,
  XX___XX_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0036[ 32] = { /* code 0036, DIGIT SIX */
  ___XXX__,________,
  __XXXXX_,________,
  _XX___XX,________,
  _XX___XX,________,
  XX______,________,
  XX______,________,
  XX_XXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX____X,X_______,
  _XX___XX,________,
  _XXXXXXX,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0037[ 32] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  ______XX,________,
  _____XXX,________,
  _____XX_,________,
  ____XXX_,________,
  ____XX__,________,
  ____XX__,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  ___XX___,________,
  __XX____,________,
  __XX____,________,
  __XX____,________,
  __XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0038[ 32] = { /* code 0038, DIGIT EIGHT */
  __XXXX__,________,
  _XXXXXX_,________,
  XXX__XXX,________,
  XX____XX,________,
  XX____XX,________,
  XX____XX,________,
  XXX__XXX,________,
  _XXXXXX_,________,
  _XXXXXXX,________,
  _XX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0039[ 32] = { /* code 0039, DIGIT NINE */
  ___XXX__,________,
  _XXXXXX_,________,
  _XX___XX,________,
  XX____XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______,
  _______X,X_______,
  XX_____X,________,
  XX____XX,________,
  _XXXXXX_,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_003A[ 11] = { /* code 003A, COLON */
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0040[ 32] = { /* code 0040, COMMERCIAL AT */
  ______XX,XX______,
  ____XXXX,XXXXX___,
  __XXXX__,___XXX__,
  __XX____,____XXX_,
  _XX___XX,X___XXX_,
  _XX__XXX,XX_X__XX,
  XX__XX__,_XXX__XX,
  XX_XXX__,__XX__XX,
  XX_XX___,__X___XX,
  XX_XX___,_XX___X_,
  _X_XX___,XXX__XX_,
  _XX_XXXX,XXXXXX__,
  _XXX_XXX,_XXX__X_,
  __XXX___,____XX__,
  ___XXXXX,XXXXX___,
  ______XX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0041[ 32] = { /* code 0041, LATIN CAPITAL LETTER A */
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX__X,XX______,
  __XXX___,XX______,
  __XX____,XX______,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXX____,XXX_____,
  _XX_____,_XX_____,
  _XX_____,_XX_____,
  XXX_____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0042[ 32] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XX_____X,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_____X,XX______,
  XXXXXXXX,X_______,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0043[ 32] = { /* code 0043, LATIN CAPITAL LETTER C */
  ___XXXX_,________,
  _XXXXXXX,________,
  _XX___XX,X_______,
  _X_____X,X_______,
  XX_____X,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX____X,X_______,
  _XX___XX,________,
  _XXXXXXX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0044[ 32] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX_____X,X_______,
  XX____XX,X_______,
  XXXXXXXX,________,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0045[ 16] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,
  XXXXXXXX,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,
  XXXXXXXX,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXX_,
  XXXXXXX_,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0047[ 32] = { /* code 0047, LATIN CAPITAL LETTER G */
  ___XXXX_,________,
  __XXXXXX,________,
  _XX___XX,________,
  _XX____X,X_______,
  XX_____X,X_______,
  XX______,________,
  XX______,________,
  XX______,________,
  XX___XXX,XX______,
  XX___XXX,XX______,
  XX______,XX______,
  XX_____X,XX______,
  XX_____X,XX______,
  _XX___XX,XX______,
  _XXXXXX_,XX______,
  __XXXX__,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0048[ 32] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_004A[ 16] = { /* code 004A, LATIN CAPITAL LETTER J */
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  XX____XX,
  XX____XX,
  XX___XXX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_004B[ 32] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX____XX,X_______,
  XX____XX,________,
  XX___XXX,________,
  XX__XXX_,________,
  XX__XX__,________,
  XX_XXX__,________,
  XXXXX___,________,
  XXXXX___,________,
  XXXXXX__,________,
  XXX_XX__,________,
  XX__XXX_,________,
  XX___XX_,________,
  XX___XXX,________,
  XX____XX,________,
  XX____XX,X_______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_004C[ 16] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_004D[ 32] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXXX___,XXXXX___,
  XX_XX___,XX_XX___,
  XX_XX___,XX_XX___,
  XX_XX___,XX_XX___,
  XX_XXX_X,XX_XX___,
  XX__XX_X,X__XX___,
  XX__XX_X,X__XX___,
  XX__XX_X,X__XX___,
  XX__XXXX,X__XX___,
  XX___XXX,___XX___,
  XX___XXX,___XX___,
  XX___XXX,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_004E[ 32] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX_____,XX______,
  XXX_____,XX______,
  XXXX____,XX______,
  XXXX____,XX______,
  XXXXX___,XX______,
  XX_XX___,XX______,
  XX_XXX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XXX_,XX______,
  XX___XX_,XX______,
  XX___XXX,XX______,
  XX____XX,XX______,
  XX____XX,XX______,
  XX_____X,XX______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_004F[ 32] = { /* code 004F, LATIN CAPITAL LETTER O */
  ___XXXX_,________,
  __XXXXXX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  _XX____X,X_______,
  _XX____X,X_______,
  __XXXXXX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0050[ 32] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,________,
  XXXXXXXX,________,
  XXXXXXX_,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0051[ 34] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXX_,________,
  __XXXXXX,________,
  _XX____X,X_______,
  _XX____X,X_______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX______,XX______,
  XX____X_,XX______,
  _XX__XXX,XX______,
  _XX___XX,X_______,
  __XXXXXX,X_______,
  ___XXXX_,XX______,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0052[ 32] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX____XX,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XX____XX,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0053[ 32] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX___XX,X_______,
  XX_____X,X_______,
  XX______,________,
  XXX_____,________,
  _XXX____,________,
  _XXXXXX_,________,
  ___XXXXX,________,
  _____XXX,X_______,
  _______X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0054[ 32] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0055[ 32] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0056[ 32] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXX_____,XXX_____,
  XXX_____,XX______,
  _XX_____,XX______,
  _XX____X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XX___X,X_______,
  __XX___X,X_______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XX_XX,________,
  ___XX_XX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  ___XXXX_,________,
  ____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0057[ 32] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXX____X,X____XXX,
  XXX___XX,XX___XXX,
  _XX___XX,XX___XX_,
  _XX___XX,XX___XX_,
  _XX___XX,XX___XX_,
  _XXX__XX,XX___XX_,
  _XXX__XX,XX__XXX_,
  __XX_XX_,_XX_XX__,
  __XX_XX_,_XX_XX__,
  __XX_XX_,_XX_XX__,
  __XX_XX_,_XX_XX__,
  __XXXXX_,_XX_XX__,
  __XXXXX_,_XXXX___,
  ___XXX__,__XXX___,
  ___XXX__,__XXX___,
  ___XXX__,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0058[ 32] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXX_____,XXX_____,
  _XXX___X,XX______,
  __XX___X,XX______,
  __XXX_XX,X_______,
  ___XX_XX,X_______,
  ___XXXXX,________,
  ____XXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXXXX,________,
  ___XX_XX,________,
  __XXX_XX,X_______,
  __XX___X,X_______,
  _XXX___X,XX______,
  _XX____X,XX______,
  XXX_____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0059[ 32] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXX____X,XX______,
  _XX____X,X_______,
  _XXX___X,X_______,
  __XX__XX,X_______,
  __XX__XX,________,
  __XXX_XX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________,
  ____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_005A[ 32] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXX___,________,
  __XX____,________,
  _XXX____,________,
  _XX_____,________,
  XXX_____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_005C[ 16] = { /* code 005C, REVERSE SOLIDUS */
  XX______,
  _X______,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ____XX__,
  ____XX__,
  ____XX__,
  _____X__,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0061[ 22] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXX__,________,
  _XXXXXXX,________,
  XX____XX,________,
  ______XX,________,
  __XXXXXX,________,
  _XXX__XX,________,
  XX____XX,________,
  XX____XX,________,
  XX___XXX,________,
  XXXXXXXX,X_______,
  _XXX___X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0062[ 16] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX_XXX__,
  XXXXXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XX_,
  XXXXXXX_,
  XX_XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0063[ 11] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _XXXXXX_,
  _XX___XX,
  XX____XX,
  XX______,
  XX______,
  XX______,
  XX____XX,
  _XX___XX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0064[ 16] = { /* code 0064, LATIN SMALL LETTER D */
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX,
  __XXX_XX,
  _XXXXXXX,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXXX,
  __XXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0065[ 11] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXX__,
  _XXXXXX_,
  _X____XX,
  XX____XX,
  XXXXXXXX,
  XXXXXXXX,
  XX______,
  XX____XX,
  XXX___XX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0066[ 16] = { /* code 0066, LATIN SMALL LETTER F */
  ___XXX__,
  __XXXX__,
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0067[ 15] = { /* code 0067, LATIN SMALL LETTER G */
  __XXX_XX,
  _XXXXXXX,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXXX,
  __XXX_XX,
  ______XX,
  XX____XX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0068[ 16] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX_XXXX_,
  XXXXXXXX,
  XXX___XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0069[ 16] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_006A[ 20] = { /* code 006A, LATIN SMALL LETTER J */
  __XX____,
  __XX____,
  ________,
  ________,
  ________,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_006B[ 32] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX______,________,
  XX___XXX,________,
  XX__XXX_,________,
  XX__XX__,________,
  XX_XX___,________,
  XXXXX___,________,
  XXXXX___,________,
  XXX_XX__,________,
  XX__XXX_,________,
  XX___XX_,________,
  XX___XXX,________,
  XX____XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_006C[ 16] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_006D[ 22] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XXXX_,_XXXX___,
  XXXXXXXX,XXXXXX__,
  XXX___XX,X___XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__,
  XX____XX,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_006E[ 11] = { /* code 006E, LATIN SMALL LETTER N */
  XX_XXXX_,
  XXXXXXXX,
  XXX___XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_006F[ 11] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXX__,
  _XXXXXX_,
  _XX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0070[ 15] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXX__,
  XXXXXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  XXXXXXX_,
  XX_XXX__,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0071[ 15] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXX_XX,
  _XXXXXXX,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXXX,
  __XXX_XX,
  ______XX,
  ______XX,
  ______XX,
  ______XX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0072[ 11] = { /* code 0072, LATIN SMALL LETTER R */
  XX_XX___,
  XXXXX___,
  XXX_____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0073[ 11] = { /* code 0073, LATIN SMALL LETTER S */
  __XXX___,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XXXX____,
  __XXXX__,
  ____XXX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0074[ 14] = { /* code 0074, LATIN SMALL LETTER T */
  __XX____,
  __XX____,
  __XX____,
  XXXXXX__,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XXXX__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0075[ 11] = { /* code 0075, LATIN SMALL LETTER U */
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX___XXX,
  XXXXXXXX,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0076[ 22] = { /* code 0076, LATIN SMALL LETTER V */
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XXX__XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  ___XXX__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0077[ 22] = { /* code 0077, LATIN SMALL LETTER W */
  XXX___XX,____XX__,
  XXX__XXX,X__XXX__,
  _XX__XXX,X__XX___,
  _XX__XXX,X__XX___,
  _XX__XXX,X__XX___,
  _XX__X__,X__XX___,
  __XX_X__,XX_X____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  ___XX___,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0078[ 22] = { /* code 0078, LATIN SMALL LETTER X */
  XXX___XX,X_______,
  _XX___XX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXXX_,________,
  __XX_XX_,________,
  _XXX_XXX,________,
  _XX___XX,________,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_0079[ 30] = { /* code 0079, LATIN SMALL LETTER Y */
  XXX___XX,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XX___XX,________,
  _XXX_XXX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XX___,________,
  _XXXX___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_007A[ 11] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,
  XXXXXXXX,
  _____XX_,
  ____XXX_,
  ___XXX__,
  ___XX___,
  __XXX___,
  _XXX____,
  _XX_____,
  XXXXXXXX,
  XXXXXXXX};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdMedCn25_00B0[  7] = { /* code 00B0, DEGREE SIGN */
  __XXX___,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHelveticaNeueLTStdMedCn25_CharInfo[76] = {
   {   1,   1,   0,  20,  11, acGUI_FontHelveticaNeueLTStdMedCn25_0020 } /* code 0020, SPACE */
  ,{   2,  16,   2,   4,   6, acGUI_FontHelveticaNeueLTStdMedCn25_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   6,   6,   2,   4,   9, acGUI_FontHelveticaNeueLTStdMedCn25_0022 } /* code 0022, QUOTATION MARK */
  ,{  15,  16,   1,   4,  16, acGUI_FontHelveticaNeueLTStdMedCn25_0025 } /* code 0025, PERCENT SIGN */
  ,{   4,  20,   1,   4,   5, acGUI_FontHelveticaNeueLTStdMedCn25_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   4,  20,   1,   4,   5, acGUI_FontHelveticaNeueLTStdMedCn25_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   6,   2,   1,  13,   7, acGUI_FontHelveticaNeueLTStdMedCn25_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   3,   2,  17,   5, acGUI_FontHelveticaNeueLTStdMedCn25_002E } /* code 002E, FULL STOP */
  ,{   7,  16,   0,   4,   6, acGUI_FontHelveticaNeueLTStdMedCn25_002F } /* code 002F, SOLIDUS */
  ,{   8,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,  16,   2,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0031 } /* code 0031, DIGIT ONE */
  ,{   8,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0032 } /* code 0032, DIGIT TWO */
  ,{   8,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0033 } /* code 0033, DIGIT THREE */
  ,{   9,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0034 } /* code 0034, DIGIT FOUR */
  ,{   8,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0035 } /* code 0035, DIGIT FIVE */
  ,{   9,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0037 } /* code 0037, DIGIT SEVEN */
  ,{   9,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0038 } /* code 0038, DIGIT EIGHT */
  ,{   9,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0039 } /* code 0039, DIGIT NINE */
  ,{   2,  11,   2,   9,   5, acGUI_FontHelveticaNeueLTStdMedCn25_003A } /* code 003A, COLON */
  ,{  16,  16,   1,   4,  17, acGUI_FontHelveticaNeueLTStdMedCn25_0040 } /* code 0040, COMMERCIAL AT */
  ,{  12,  16,   0,   4,  11, acGUI_FontHelveticaNeueLTStdMedCn25_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  10,  16,   1,   4,  11, acGUI_FontHelveticaNeueLTStdMedCn25_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   9,  16,   1,   4,  11, acGUI_FontHelveticaNeueLTStdMedCn25_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  10,  16,   1,   4,  12, acGUI_FontHelveticaNeueLTStdMedCn25_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   8,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   8,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  10,  16,   1,   4,  11, acGUI_FontHelveticaNeueLTStdMedCn25_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   9,  16,   1,   4,  12, acGUI_FontHelveticaNeueLTStdMedCn25_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  16,   1,   4,   5, acGUI_FontHelveticaNeueLTStdMedCn25_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   8,  16,   0,   4,   9, acGUI_FontHelveticaNeueLTStdMedCn25_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  10,  16,   1,   4,  11, acGUI_FontHelveticaNeueLTStdMedCn25_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   8,  16,   1,   4,   9, acGUI_FontHelveticaNeueLTStdMedCn25_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  13,  16,   1,   4,  15, acGUI_FontHelveticaNeueLTStdMedCn25_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  10,  16,   1,   4,  12, acGUI_FontHelveticaNeueLTStdMedCn25_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  10,  16,   1,   4,  12, acGUI_FontHelveticaNeueLTStdMedCn25_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   9,  16,   1,   4,  11, acGUI_FontHelveticaNeueLTStdMedCn25_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  10,  17,   1,   4,  12, acGUI_FontHelveticaNeueLTStdMedCn25_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  10,  16,   1,   4,  11, acGUI_FontHelveticaNeueLTStdMedCn25_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   9,  16,   1,   4,  11, acGUI_FontHelveticaNeueLTStdMedCn25_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  10,  16,   0,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   9,  16,   1,   4,  11, acGUI_FontHelveticaNeueLTStdMedCn25_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  11,  16,   0,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  16,  16,   0,   4,  16, acGUI_FontHelveticaNeueLTStdMedCn25_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  11,  16,   0,   4,  11, acGUI_FontHelveticaNeueLTStdMedCn25_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  10,  16,   0,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   9,  16,   0,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   7,  16,   0,   4,   6, acGUI_FontHelveticaNeueLTStdMedCn25_005C } /* code 005C, REVERSE SOLIDUS */
  ,{  11,   1,   0,  22,  11, acGUI_FontHelveticaNeueLTStdMedCn25_005F } /* code 005F, LOW LINE */
  ,{   9,  11,   1,   9,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   8,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   8,  11,   1,   9,   9, acGUI_FontHelveticaNeueLTStdMedCn25_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   8,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   8,  11,   1,   9,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   6,  16,   0,   4,   6, acGUI_FontHelveticaNeueLTStdMedCn25_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   8,  15,   1,   9,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   8,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  16,   1,   4,   5, acGUI_FontHelveticaNeueLTStdMedCn25_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   4,  20,  -1,   4,   5, acGUI_FontHelveticaNeueLTStdMedCn25_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   9,  16,   1,   4,  10, acGUI_FontHelveticaNeueLTStdMedCn25_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   2,  16,   1,   4,   5, acGUI_FontHelveticaNeueLTStdMedCn25_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  14,  11,   1,   9,  16, acGUI_FontHelveticaNeueLTStdMedCn25_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   8,  11,   1,   9,  10, acGUI_FontHelveticaNeueLTStdMedCn25_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   8,  11,   1,   9,  10, acGUI_FontHelveticaNeueLTStdMedCn25_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   8,  15,   1,   9,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   8,  15,   1,   9,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   5,  11,   1,   9,   7, acGUI_FontHelveticaNeueLTStdMedCn25_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   7,  11,   1,   9,   9, acGUI_FontHelveticaNeueLTStdMedCn25_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   6,  14,   0,   6,   6, acGUI_FontHelveticaNeueLTStdMedCn25_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   8,  11,   1,   9,  10, acGUI_FontHelveticaNeueLTStdMedCn25_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   9,  11,   0,   9,   9, acGUI_FontHelveticaNeueLTStdMedCn25_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  14,  11,   0,   9,  14, acGUI_FontHelveticaNeueLTStdMedCn25_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   9,  11,   0,   9,   9, acGUI_FontHelveticaNeueLTStdMedCn25_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   9,  15,   0,   9,   9, acGUI_FontHelveticaNeueLTStdMedCn25_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   8,  11,   0,   9,   9, acGUI_FontHelveticaNeueLTStdMedCn25_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   7,   7,   1,   4,   8, acGUI_FontHelveticaNeueLTStdMedCn25_00B0 } /* code 00B0, DEGREE SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn25_Prop9 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_CharInfo[ 75] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn25_Prop8 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn25_Prop7 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn25_Prop6 = {
   0x005C /* first character */
  ,0x005C /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn25_Prop5 = {
   0x0040 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn25_Prop4 = {
   0x002D /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_CharInfo[  6] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn25_Prop3 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_CharInfo[  4] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn25_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_CharInfo[  3] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdMedCn25_Prop1 = {
   0x0020 /* first character */
  ,0x0022 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdMedCn25_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdMedCn25 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,25 /* height of font  */
  ,25 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTStdMedCn25_Prop1}
  ,20 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

