/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Std Cn38.c                            *
* Font:        HelveticaNeueLT Std Cn                                *
* Height:      38                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 38                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\WB\MDK5\fonts_all.txt                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn38;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0021[ 23] = { /* code 0021, EXCLAMATION MARK */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0022[ 20] = { /* code 0022, QUOTATION MARK */
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0025[ 72] = { /* code 0025, PERCENT SIGN */
  __XXXXX_,________,XXXX____,
  _XXXXXXX,________,XXX_____,
  XXX___XX,X______X,XX______,
  XXX___XX,X______X,XX______,
  XXX___XX,X_____XX,X_______,
  XXX___XX,X_____XX,X_______,
  XXX___XX,X____XXX,________,
  XXX___XX,X___XXX_,________,
  XXX___XX,X___XXX_,________,
  XXX___XX,X__XXX__,________,
  _XXXXXXX,___XXX__,________,
  __XXXXX_,__XXX___,XXXXX___,
  ________,_XXXX__X,XXXXXX__,
  ________,_XXX__XX,X___XXX_,
  ________,XXX___XX,X___XXX_,
  ________,XXX___XX,X___XXX_,
  _______X,XX____XX,X___XXX_,
  _______X,XX____XX,X___XXX_,
  ______XX,X_____XX,X___XXX_,
  _____XXX,X_____XX,X___XXX_,
  _____XXX,______XX,X___XXX_,
  ____XXX_,_______X,XXXXXX__,
  ____XXX_,________,XXXXX___,
  ___X____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0028[ 29] = { /* code 0028, LEFT PARENTHESIS */
  ____XXXX,
  ___XXXX_,
  ___XXX__,
  __XXXX__,
  __XXXX__,
  __XXX___,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  _XXX____,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  __XXX___,
  __XXXX__,
  __XXXX__,
  ___XXX__,
  ___XXXX_,
  ____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0029[ 29] = { /* code 0029, RIGHT PARENTHESIS */
  XXXX____,
  _XXXX___,
  __XXX___,
  __XXXX__,
  __XXXX__,
  ___XXX__,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ____XXX_,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXX__,
  __XXXX__,
  __XXXX__,
  __XXX___,
  _XXXX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_002D[  6] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_002E[  5] = { /* code 002E, FULL STOP */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_002F[ 46] = { /* code 002F, SOLIDUS */
  _______X,XXX_____,
  _______X,XX______,
  _______X,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXX____,________,
  _XXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0030[ 46] = { /* code 0030, DIGIT ZERO */
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0031[ 23] = { /* code 0031, DIGIT ONE */
  _____XXX,
  _____XXX,
  ____XXXX,
  ___XXXXX,
  XXXXXXXX,
  XXXXXXXX,
  XXXXXXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0032[ 46] = { /* code 0032, DIGIT TWO */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXX___,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  ________,_XXXX___,
  ________,XXXX____,
  _______X,XXXX____,
  ______XX,XXXX____,
  _____XXX,XXX_____,
  ____XXXX,XX______,
  ____XXXX,X_______,
  ___XXXXX,________,
  __XXXXXX,________,
  __XXXXX_,________,
  _XXXXX__,________,
  _XXXX___,________,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0033[ 46] = { /* code 0033, DIGIT THREE */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXX___,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  ________,_XXXX___,
  ________,XXXX____,
  ________,XXXX____,
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  _____XXX,XXXX____,
  ________,XXXX____,
  ________,_XXXX___,
  ________,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0034[ 46] = { /* code 0034, DIGIT FOUR */
  _______X,XXXX____,
  _______X,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  _____XXX,XXXX____,
  _____XXX,XXXX____,
  ____XXXX,XXXX____,
  ____XXX_,XXXX____,
  ___XXXX_,XXXX____,
  ___XXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXX___,XXXX____,
  _XXX____,XXXX____,
  _XXX____,XXXX____,
  XXX_____,XXXX____,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0035[ 46] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX_XXX,XX______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  XXXXX___,XXXX____,
  XXXX____,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0036[ 46] = { /* code 0036, DIGIT SIX */
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  _XXXX___,XXXXX___,
  _XXXX___,_XXXX___,
  _XXX____,_XXXX___,
  XXXX____,________,
  XXXX____,________,
  XXXX__XX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXX___,
  XXXXX___,_XXXX___,
  XXXXX___,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  _XXX____,__XXXX__,
  _XXXX___,__XXX___,
  _XXXX___,_XXXX___,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0037[ 46] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,XXXX____,
  ________,XXXX____,
  _______X,XXX_____,
  ______XX,XXX_____,
  ______XX,XXX_____,
  ______XX,XX______,
  _____XXX,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0038[ 46] = { /* code 0038, DIGIT EIGHT */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  XXXXX___,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,XXXX____,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  _XXXXXXX,XXXXX___,
  _XXXX___,_XXXX___,
  _XXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  _XXXX___,_XXXX___,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXX____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0039[ 46] = { /* code 0039, DIGIT NINE */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXX___,_XXXX___,
  _XXX____,_XXXX___,
  XXXX____,__XXX___,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,_XXXXX__,
  XXXXX___,_XXXXX__,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  ___XXXXX,__XXXX__,
  ________,__XXXX__,
  ________,__XXXX__,
  XXXX____,__XXX___,
  XXXX____,_XXXX___,
  XXXXX___,_XXXX___,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_003A[ 17] = { /* code 003A, COLON */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0040[ 69] = { /* code 0040, COMMERCIAL AT */
  ________,XXXXXXX_,________,
  ______XX,XXXXXXXX,XX______,
  _____XXX,XXXXXXXX,XXXX____,
  ___XXXXX,X_______,XXXXX___,
  ___XXXX_,________,__XXXX__,
  __XXX___,_XXXXX__,XXXXXXX_,
  _XXXX___,XXXXXXX_,XXX_XXX_,
  _XXX___X,XXXXXXXX,XXX__XXX,
  XXXX__XX,XX___XXX,XX___XXX,
  XXX___XX,X_____XX,XX___XXX,
  XXX__XXX,______XX,XX___XXX,
  XXX__XXX,______XX,XX___XXX,
  XXX__XXX,______XX,X___XXX_,
  XXX__XXX,_____XXX,X___XXX_,
  _XXX_XXX,X___XXXX,X__XXX__,
  _XXX__XX,XXXXXXXX,XXXXX___,
  _XXXX_XX,XXXXXXXX,XXXX____,
  __XXXX_X,XXXX__XX,XX____X_,
  ___XXXX_,________,__XXXX__,
  ___XXXXX,X_______,XXXXX___,
  _____XXX,XXXXXXXX,XXXX____,
  ______XX,XXXXXXXX,XX______,
  ________,_XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0041[ 69] = { /* code 0041, LATIN CAPITAL LETTER A */
  ______XX,XXXX____,________,
  ______XX,XXXX____,________,
  _____XXX,XXXXX___,________,
  _____XXX,XXXXX___,________,
  _____XXX,XXXXX___,________,
  _____XXX,XXXXX___,________,
  ____XXXX,__XXXX__,________,
  ____XXXX,__XXXX__,________,
  ____XXXX,__XXXX__,________,
  ____XXXX,__XXXX__,________,
  ___XXXXX,__XXXXX_,________,
  ___XXXX_,___XXXX_,________,
  ___XXXX_,___XXXX_,________,
  ___XXXX_,___XXXX_,________,
  __XXXXX_,___XXXXX,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,________,
  _XXXXX__,____XXXX,X_______,
  _XXXXX__,____XXXX,X_______,
  _XXXX___,_____XXX,X_______,
  XXXXX___,_____XXX,XX______,
  XXXXX___,_____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0042[ 46] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXX___,
  XXXX____,_XXXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXX___,
  XXXX____,XXXXX___,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0043[ 46] = { /* code 0043, LATIN CAPITAL LETTER C */
  _____XXX,XXX_____,
  ___XXXXX,XXXXX___,
  __XXXXXX,XXXXXX__,
  _XXXXX__,__XXXX__,
  _XXXX___,__XXXXX_,
  _XXXX___,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  _XXXX___,___XXXX_,
  _XXXX___,__XXXX__,
  _XXXXX__,_XXXXX__,
  __XXXXXX,XXXXXX__,
  ___XXXXX,XXXX____,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0044[ 46] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXXX,XX______,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXX___,
  XXXX____,_XXXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,_XXXXX__,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0045[ 46] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0046[ 46] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0047[ 46] = { /* code 0047, LATIN CAPITAL LETTER G */
  _____XXX,XX______,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXXX___,
  _XXXXX__,_XXXX___,
  _XXXX___,_XXXXX__,
  _XXXX___,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX___X,XXXXXX__,
  XXXX___X,XXXXXX__,
  XXXX___X,XXXXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  _XXXX___,__XXXX__,
  _XXXX___,_XXXXX__,
  _XXXXX__,_XXXXX__,
  __XXXXXX,XXXXXX__,
  __XXXXXX,XX_XXX__,
  ____XXXX,X__XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0048[ 46] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0049[ 23] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_004A[ 46] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXXX__X,XXXX____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_004B[ 46] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXXX____,__XXXXX_,
  XXXX____,_XXXXX__,
  XXXX____,XXXXX___,
  XXXX____,XXXXX___,
  XXXX___X,XXXX____,
  XXXX__XX,XXX_____,
  XXXX__XX,XXX_____,
  XXXX_XXX,XX______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XXXXX_XX,XXX_____,
  XXXX___X,XXXX____,
  XXXX___X,XXXX____,
  XXXX____,XXXXX___,
  XXXX____,XXXXX___,
  XXXX____,_XXXXX__,
  XXXX____,_XXXXX__,
  XXXX____,__XXXXX_,
  XXXX____,__XXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_004C[ 46] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_004D[ 69] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXXXXXX_,_____XXX,XXXX____,
  XXXXXXX_,_____XXX,XXXX____,
  XXXXXXX_,_____XXX,XXXX____,
  XXXXXXX_,_____XXX,XXXX____,
  XXXXXXXX,____XXXX,XXXX____,
  XXXXXXXX,____XXXX,XXXX____,
  XXXXXXXX,____XXXX,XXXX____,
  XXXX_XXX,____XXX_,XXXX____,
  XXXX_XXX,____XXX_,XXXX____,
  XXXX_XXX,X__XXXX_,XXXX____,
  XXXX_XXX,X__XXXX_,XXXX____,
  XXXX__XX,X__XXX__,XXXX____,
  XXXX__XX,X__XXX__,XXXX____,
  XXXX__XX,X__XXX__,XXXX____,
  XXXX__XX,XXXXXX__,XXXX____,
  XXXX__XX,XXXXXX__,XXXX____,
  XXXX___X,XXXXX___,XXXX____,
  XXXX___X,XXXXX___,XXXX____,
  XXXX___X,XXXXX___,XXXX____,
  XXXX___X,XXXXX___,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_004E[ 46] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXXXX___,___XXXX_,
  XXXXXX__,___XXXX_,
  XXXXXX__,___XXXX_,
  XXXXXX__,___XXXX_,
  XXXXXXX_,___XXXX_,
  XXXXXXX_,___XXXX_,
  XXXXXXXX,___XXXX_,
  XXXXXXXX,___XXXX_,
  XXXX_XXX,___XXXX_,
  XXXX_XXX,X__XXXX_,
  XXXX_XXX,X__XXXX_,
  XXXX__XX,X__XXXX_,
  XXXX__XX,XX_XXXX_,
  XXXX__XX,XX_XXXX_,
  XXXX___X,XXXXXXX_,
  XXXX___X,XXXXXXX_,
  XXXX____,XXXXXXX_,
  XXXX____,XXXXXXX_,
  XXXX____,XXXXXXX_,
  XXXX____,_XXXXXX_,
  XXXX____,_XXXXXX_,
  XXXX____,_XXXXXX_,
  XXXX____,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_004F[ 46] = { /* code 004F, LATIN CAPITAL LETTER O */
  _____XXX,XX______,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXXX___,
  _XXXXX__,_XXXXX__,
  _XXXX___,__XXXX__,
  _XXX____,___XXX__,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  _XXX____,___XXX__,
  _XXXX___,__XXXX__,
  _XXXXX__,_XXXXX__,
  __XXXXXX,XXXXX___,
  ___XXXXX,XXXX____,
  _____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0050[ 46] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXXX,XX______,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXX___,
  XXXX____,XXXXX___,
  XXXX____,_XXXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,_XXXXX__,
  XXXX____,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XX______,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0051[ 50] = { /* code 0051, LATIN CAPITAL LETTER Q */
  _____XXX,XX______,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXXX___,
  _XXXXX__,_XXXXX__,
  _XXXX___,__XXXX__,
  _XXX____,___XXX__,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  _XXX____,___XXX__,
  _XXXX___,__XXXX__,
  _XXXXX__,_XXXXX__,
  __XXXXXX,XXXXX___,
  ___XXXXX,XXXXXX__,
  _____XXX,XXXXXXXX,
  ________,___XXXX_,
  ________,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0052[ 46] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXX____,_XXXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,XXXXX___,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0053[ 46] = { /* code 0053, LATIN CAPITAL LETTER S */
  ____XXXX,XX______,
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXXX___,
  XXXXX___,_XXXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,________,
  XXXXX___,________,
  XXXXXX__,________,
  _XXXXXXX,X_______,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXXXX___,
  ____XXXX,XXXXXX__,
  ______XX,XXXXXX__,
  ________,_XXXXXX_,
  ________,__XXXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXXX___,__XXXX__,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXX___,
  ____XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0054[ 46] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0055[ 46] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  _XXXX___,_XXXX___,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXX____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0056[ 46] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXXX___,___XXXXX,
  XXXXX___,___XXXXX,
  _XXXX___,___XXXX_,
  _XXXX___,___XXXX_,
  _XXXXX__,__XXXXX_,
  _XXXXX__,__XXXXX_,
  _XXXXX__,__XXXXX_,
  __XXXX__,__XXXX__,
  __XXXX__,__XXXX__,
  __XXXXX_,_XXXXX__,
  __XXXXX_,_XXXXX__,
  ___XXXX_,_XXXX___,
  ___XXXX_,_XXXX___,
  ___XXXX_,_XXXX___,
  ___XXXX_,_XXXX___,
  ___XXXXX,XXXXX___,
  ____XXXX,XXXX____,
  ____XXXX,XXXX____,
  ____XXXX,XXXX____,
  ____XXXX,XXXX____,
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0057[ 69] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXXX___,__XXXX__,___XXXXX,
  XXXXX___,__XXXX__,___XXXXX,
  _XXXX___,_XXXXXX_,___XXXX_,
  _XXXX___,_XXXXXX_,___XXXX_,
  _XXXX___,_XXXXXX_,___XXXX_,
  _XXXX___,_XXXXXX_,___XXXX_,
  _XXXX___,_XXXXXX_,___XXXX_,
  _XXXXX__,_XXXXXX_,__XXXXX_,
  __XXXX__,XXXXXXXX,__XXXX__,
  __XXXX__,XXX__XXX,__XXXX__,
  __XXXX__,XXX__XXX,__XXXX__,
  __XXXX__,XXX__XXX,__XXXX__,
  __XXXX__,XXX__XXX,__XXXX__,
  ___XXX__,XXX__XXX,__XXX___,
  ___XXXXX,XXX__XXX,XXXXX___,
  ___XXXXX,XXX__XXX,XXXXX___,
  ___XXXXX,XX____XX,XXXXX___,
  ___XXXXX,XX____XX,XXXXX___,
  ___XXXXX,XX____XX,XXXXX___,
  ____XXXX,XX____XX,XXXX____,
  ____XXXX,XX____XX,XXXX____,
  ____XXXX,XX____XX,XXXX____,
  ____XXXX,X______X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0058[ 69] = { /* code 0058, LATIN CAPITAL LETTER X */
  _XXXXX__,___XXXXX,X_______,
  _XXXXX__,___XXXXX,________,
  __XXXXX_,___XXXX_,________,
  __XXXXX_,__XXXXX_,________,
  ___XXXX_,__XXXX__,________,
  ___XXXXX,_XXXXX__,________,
  ____XXXX,_XXXXX__,________,
  ____XXXX,XXXXX___,________,
  ____XXXX,XXXXX___,________,
  _____XXX,XXXX____,________,
  _____XXX,XXXX____,________,
  ______XX,XXX_____,________,
  _____XXX,XXXX____,________,
  _____XXX,XXXX____,________,
  ____XXXX,XXXXX___,________,
  ____XXXX,_XXXX___,________,
  ___XXXXX,_XXXXX__,________,
  ___XXXX_,_XXXXX__,________,
  __XXXXX_,__XXXXX_,________,
  __XXXXX_,__XXXXX_,________,
  _XXXXX__,___XXXXX,________,
  _XXXXX__,___XXXXX,________,
  XXXXX___,____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0059[ 46] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXXXX___,___XXXXX,
  _XXXXX__,__XXXXX_,
  _XXXXX__,__XXXXX_,
  __XXXX__,__XXXX__,
  __XXXXX_,_XXXXX__,
  __XXXXX_,_XXXXX__,
  ___XXXX_,_XXXX___,
  ___XXXXX,XXXXX___,
  ____XXXX,XXXX____,
  ____XXXX,XXXX____,
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_005A[ 46] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  ________,XXXXX___,
  ________,XXXXX___,
  _______X,XXXX____,
  _______X,XXXX____,
  ______XX,XXX_____,
  ______XX,XXX_____,
  _____XXX,XX______,
  _____XXX,XX______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXXXX,________,
  ___XXXXX,________,
  __XXXXXX,________,
  __XXXXX_,________,
  _XXXXXX_,________,
  _XXXXX__,________,
  XXXXXX__,________,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_005C[ 46] = { /* code 005C, REVERSE SOLIDUS */
  XXXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXX___,________,
  _XXXX___,________,
  __XXX___,________,
  __XXXX__,________,
  __XXXX__,________,
  ___XXX__,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ____XXX_,________,
  ____XXXX,________,
  ____XXXX,________,
  _____XXX,________,
  _____XXX,X_______,
  _____XXX,X_______,
  ______XX,X_______,
  ______XX,XX______,
  ______XX,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_005F[  4] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0061[ 34] = { /* code 0061, LATIN SMALL LETTER A */
  ___XXXXX,XX______,
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  XXXXX___,_XXXX___,
  XXXX____,_XXXX___,
  ________,_XXXX___,
  ______XX,XXXXX___,
  ___XXXXX,XXXXX___,
  _XXXXXXX,_XXXX___,
  _XXXX___,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXXX___,XXXXX___,
  _XXXXXXX,XXXXX___,
  _XXXXXXX,_XXXX___,
  __XXXXX_,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0062[ 46] = { /* code 0062, LATIN SMALL LETTER B */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX__XX,XX______,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXXX___,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXXX___,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXX__XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0063[ 34] = { /* code 0063, LATIN SMALL LETTER C */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXX___,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0064[ 46] = { /* code 0064, LATIN SMALL LETTER D */
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ___XXXX_,_XXXX___,
  __XXXXXX,XXXXX___,
  _XXXXXXX,XXXXX___,
  _XXXX___,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,XXXXX___,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  ___XXXX_,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0065[ 34] = { /* code 0065, LATIN SMALL LETTER E */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXX___,XXXX____,
  _XXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXX____,________,
  XXXX____,________,
  XXXX____,_XXXX___,
  _XXX____,_XXX____,
  _XXXX___,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0066[ 46] = { /* code 0066, LATIN SMALL LETTER F */
  ____XXXX,X_______,
  ___XXXXX,X_______,
  __XXXXXX,X_______,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0067[ 46] = { /* code 0067, LATIN SMALL LETTER G */
  ___XXXX_,_XXXX___,
  __XXXXXX,_XXXX___,
  _XXXXXXX,XXXXX___,
  _XXXX___,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,XXXXX___,
  _XXXXXXX,XXXXX___,
  __XXXXXX,_XXXX___,
  ___XXXX_,_XXXX___,
  ________,_XXXX___,
  XXXX____,_XXXX___,
  XXXXX___,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXX_____,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0068[ 46] = { /* code 0068, LATIN SMALL LETTER H */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX__XX,XX______,
  XXXX_XXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXXX___,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0069[ 23] = { /* code 0069, LATIN SMALL LETTER I */
  XXXX____,
  XXXX____,
  XXXX____,
  ________,
  ________,
  ________,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_006A[ 29] = { /* code 006A, LATIN SMALL LETTER J */
  __XXXX__,
  __XXXX__,
  __XXXX__,
  ________,
  ________,
  ________,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  XXXXXX__,
  XXXXX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_006B[ 46] = { /* code 006B, LATIN SMALL LETTER K */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,XXXXX___,
  XXXX___X,XXXX____,
  XXXX___X,XXXX____,
  XXXX__XX,XXX_____,
  XXXX_XXX,XX______,
  XXXX_XXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,XX______,
  XXXXX_XX,XX______,
  XXXX__XX,XXX_____,
  XXXX___X,XXXX____,
  XXXX___X,XXXX____,
  XXXX____,XXXXX___,
  XXXX____,XXXXX___,
  XXXX____,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_006C[ 23] = { /* code 006C, LATIN SMALL LETTER L */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_006D[ 51] = { /* code 006D, LATIN SMALL LETTER M */
  XXXX__XX,XX____XX,XX______,
  XXXXXXXX,XXX__XXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXX___,XXXXX___,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_006E[ 34] = { /* code 006E, LATIN SMALL LETTER N */
  XXXX__XX,XX______,
  XXXX_XXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXXX___,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_006F[ 34] = { /* code 006F, LATIN SMALL LETTER O */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXX___,XXXX____,
  _XXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXX____,
  _XXXX___,XXXX____,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0070[ 46] = { /* code 0070, LATIN SMALL LETTER P */
  XXXX__XX,XX______,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXXX___,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXXX___,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXX__XX,XX______,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0071[ 46] = { /* code 0071, LATIN SMALL LETTER Q */
  ___XXXX_,_XXXX___,
  __XXXXXX,XXXXX___,
  _XXXXXXX,XXXXX___,
  _XXXX___,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,XXXXX___,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  ___XXXX_,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0072[ 34] = { /* code 0072, LATIN SMALL LETTER R */
  XXXX__XX,X_______,
  XXXX_XXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXX___,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0073[ 34] = { /* code 0073, LATIN SMALL LETTER S */
  ___XXXXX,X_______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  XXXXX___,XXXX____,
  XXXX____,XXXX____,
  XXXX____,________,
  XXXXXX__,________,
  _XXXXXXX,X_______,
  __XXXXXX,XXX_____,
  ____XXXX,XXX_____,
  _______X,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXXX___,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0074[ 44] = { /* code 0074, LATIN SMALL LETTER T */
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0075[ 34] = { /* code 0075, LATIN SMALL LETTER U */
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX___X,XXXX____,
  XXXXXXXX,XXXX____,
  _XXXXXX_,XXXX____,
  __XXXX__,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0076[ 34] = { /* code 0076, LATIN SMALL LETTER V */
  XXXXX___,_XXXXX__,
  XXXXX___,_XXXXX__,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXXX__,_XXXX___,
  _XXXXX__,XXXXX___,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  ___XXXX_,XXXX____,
  ___XXXX_,XXX_____,
  ___XXXXX,XXX_____,
  ___XXXXX,XXX_____,
  ____XXXX,XXX_____,
  ____XXXX,XX______,
  ____XXXX,XX______,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0077[ 51] = { /* code 0077, LATIN SMALL LETTER W */
  XXXXX___,_XXXX___,__XXXX__,
  XXXXX___,XXXXXX__,__XXXX__,
  _XXXX___,XXXXXX__,_XXXX___,
  _XXXX___,XXXXXX__,_XXXX___,
  _XXXX___,XXXXXX__,_XXXX___,
  _XXXX___,XXXXXX__,_XXXX___,
  _XXXXX_X,XXXXXXX_,_XXXX___,
  __XXXX_X,XXX_XXX_,XXXX____,
  __XXXX_X,XX__XXX_,XXXX____,
  __XXXX_X,XX__XXX_,XXXX____,
  __XXXX_X,XX__XXX_,XXXX____,
  ___XXX_X,XX__XXXX,XXX_____,
  ___XXXXX,XX__XXXX,XXX_____,
  ___XXXXX,X____XXX,XXX_____,
  ___XXXXX,X____XXX,XXX_____,
  ___XXXXX,X____XXX,XXX_____,
  ____XXXX,X____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0078[ 34] = { /* code 0078, LATIN SMALL LETTER X */
  XXXXX___,_XXXXX__,
  _XXXX___,_XXXX___,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  ___XXXXX,XXX_____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______,
  ____XXXX,XX______,
  ____XXXX,XX______,
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  __XXXX__,XXXX____,
  _XXXXX__,XXXXX___,
  _XXXX___,_XXXX___,
  XXXXX___,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_0079[ 46] = { /* code 0079, LATIN SMALL LETTER Y */
  XXXXX___,_XXXXX__,
  XXXXX___,_XXXXX__,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  ___XXXX_,XXXX____,
  ___XXXX_,XXX_____,
  ___XXXXX,XXX_____,
  ___XXXXX,XXX_____,
  ____XXXX,XXX_____,
  ____XXXX,XX______,
  ____XXXX,XX______,
  _____XXX,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  ____XXXX,X_______,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_007A[ 34] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXX_____,
  _____XXX,XX______,
  _____XXX,XX______,
  ____XXXX,X_______,
  ___XXXXX,X_______,
  ___XXXXX,________,
  __XXXXX_,________,
  __XXXXX_,________,
  _XXXXX__,________,
  XXXXXX__,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn38_00B0[ 20] = { /* code 00B0, DEGREE SIGN */
  __XXXXX_,________,
  _XXXXXXX,________,
  _XX___XX,________,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  XX_____X,X_______,
  _XX___XX,________,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHelveticaNeueLTStdCn38_CharInfo[76] = {
   {   1,   1,   0,  31,  17, acGUI_FontHelveticaNeueLTStdCn38_0020 } /* code 0020, SPACE */
  ,{   4,  23,   3,   8,   9, acGUI_FontHelveticaNeueLTStdCn38_0021 } /* code 0021, EXCLAMATION MARK */
  ,{  11,  10,   2,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0022 } /* code 0022, QUOTATION MARK */
  ,{  23,  24,   1,   8,  25, acGUI_FontHelveticaNeueLTStdCn38_0025 } /* code 0025, PERCENT SIGN */
  ,{   8,  29,   2,   8,   9, acGUI_FontHelveticaNeueLTStdCn38_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   8,  29,   0,   8,   9, acGUI_FontHelveticaNeueLTStdCn38_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   9,   3,   1,  20,  12, acGUI_FontHelveticaNeueLTStdCn38_002D } /* code 002D, HYPHEN-MINUS */
  ,{   4,   5,   2,  26,   8, acGUI_FontHelveticaNeueLTStdCn38_002E } /* code 002E, FULL STOP */
  ,{  11,  23,   0,   8,  11, acGUI_FontHelveticaNeueLTStdCn38_002F } /* code 002F, SOLIDUS */
  ,{  14,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  23,   2,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0031 } /* code 0031, DIGIT ONE */
  ,{  13,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0032 } /* code 0032, DIGIT TWO */
  ,{  13,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0033 } /* code 0033, DIGIT THREE */
  ,{  14,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0034 } /* code 0034, DIGIT FOUR */
  ,{  13,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0035 } /* code 0035, DIGIT FIVE */
  ,{  14,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0036 } /* code 0036, DIGIT SIX */
  ,{  14,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0037 } /* code 0037, DIGIT SEVEN */
  ,{  14,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0038 } /* code 0038, DIGIT EIGHT */
  ,{  14,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0039 } /* code 0039, DIGIT NINE */
  ,{   4,  17,   2,  14,   8, acGUI_FontHelveticaNeueLTStdCn38_003A } /* code 003A, COLON */
  ,{  24,  23,   1,   8,  26, acGUI_FontHelveticaNeueLTStdCn38_0040 } /* code 0040, COMMERCIAL AT */
  ,{  18,  23,   0,   8,  18, acGUI_FontHelveticaNeueLTStdCn38_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  14,  23,   2,   8,  18, acGUI_FontHelveticaNeueLTStdCn38_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  15,  23,   1,   8,  17, acGUI_FontHelveticaNeueLTStdCn38_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  15,  23,   2,   8,  18, acGUI_FontHelveticaNeueLTStdCn38_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  12,  23,   2,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  12,  23,   2,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  14,  23,   2,   8,  18, acGUI_FontHelveticaNeueLTStdCn38_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  14,  23,   2,   8,  18, acGUI_FontHelveticaNeueLTStdCn38_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   4,  23,   2,   8,   8, acGUI_FontHelveticaNeueLTStdCn38_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  12,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  16,  23,   2,   8,  17, acGUI_FontHelveticaNeueLTStdCn38_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{  12,  23,   2,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  20,  23,   2,   8,  24, acGUI_FontHelveticaNeueLTStdCn38_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  15,  23,   2,   8,  18, acGUI_FontHelveticaNeueLTStdCn38_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  15,  23,   1,   8,  18, acGUI_FontHelveticaNeueLTStdCn38_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  14,  23,   2,   8,  17, acGUI_FontHelveticaNeueLTStdCn38_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  16,  25,   1,   8,  18, acGUI_FontHelveticaNeueLTStdCn38_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  15,  23,   2,   8,  18, acGUI_FontHelveticaNeueLTStdCn38_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  15,  23,   1,   8,  17, acGUI_FontHelveticaNeueLTStdCn38_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  14,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  14,  23,   2,   8,  17, acGUI_FontHelveticaNeueLTStdCn38_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  16,  23,   0,   8,  17, acGUI_FontHelveticaNeueLTStdCn38_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  24,  23,   0,   8,  24, acGUI_FontHelveticaNeueLTStdCn38_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  17,  23,   0,   8,  17, acGUI_FontHelveticaNeueLTStdCn38_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  16,  23,   0,   8,  17, acGUI_FontHelveticaNeueLTStdCn38_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  14,  23,   1,   8,  15, acGUI_FontHelveticaNeueLTStdCn38_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{  11,  23,   0,   8,  11, acGUI_FontHelveticaNeueLTStdCn38_005C } /* code 005C, REVERSE SOLIDUS */
  ,{  16,   2,   0,  33,  16, acGUI_FontHelveticaNeueLTStdCn38_005F } /* code 005F, LOW LINE */
  ,{  13,  17,   1,  14,  15, acGUI_FontHelveticaNeueLTStdCn38_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{  13,  23,   2,   8,  16, acGUI_FontHelveticaNeueLTStdCn38_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{  13,  17,   1,  14,  15, acGUI_FontHelveticaNeueLTStdCn38_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{  13,  23,   1,   8,  16, acGUI_FontHelveticaNeueLTStdCn38_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{  13,  17,   1,  14,  15, acGUI_FontHelveticaNeueLTStdCn38_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   9,  23,   1,   8,   9, acGUI_FontHelveticaNeueLTStdCn38_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{  13,  23,   1,  14,  16, acGUI_FontHelveticaNeueLTStdCn38_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{  12,  23,   2,   8,  16, acGUI_FontHelveticaNeueLTStdCn38_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   4,  23,   2,   8,   8, acGUI_FontHelveticaNeueLTStdCn38_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   6,  29,   0,   8,   8, acGUI_FontHelveticaNeueLTStdCn38_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  14,  23,   2,   8,  16, acGUI_FontHelveticaNeueLTStdCn38_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   4,  23,   2,   8,   8, acGUI_FontHelveticaNeueLTStdCn38_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  20,  17,   2,  14,  24, acGUI_FontHelveticaNeueLTStdCn38_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{  12,  17,   2,  14,  16, acGUI_FontHelveticaNeueLTStdCn38_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{  13,  17,   1,  14,  15, acGUI_FontHelveticaNeueLTStdCn38_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{  13,  23,   2,  14,  16, acGUI_FontHelveticaNeueLTStdCn38_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{  13,  23,   1,  14,  16, acGUI_FontHelveticaNeueLTStdCn38_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   9,  17,   2,  14,  11, acGUI_FontHelveticaNeueLTStdCn38_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{  12,  17,   1,  14,  14, acGUI_FontHelveticaNeueLTStdCn38_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   9,  22,   1,   9,   9, acGUI_FontHelveticaNeueLTStdCn38_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{  12,  17,   2,  14,  16, acGUI_FontHelveticaNeueLTStdCn38_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  14,  17,   0,  14,  14, acGUI_FontHelveticaNeueLTStdCn38_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  22,  17,   0,  14,  23, acGUI_FontHelveticaNeueLTStdCn38_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{  14,  17,   0,  14,  15, acGUI_FontHelveticaNeueLTStdCn38_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{  14,  23,   0,  14,  14, acGUI_FontHelveticaNeueLTStdCn38_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{  12,  17,   1,  14,  14, acGUI_FontHelveticaNeueLTStdCn38_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   9,  10,   2,   8,  13, acGUI_FontHelveticaNeueLTStdCn38_00B0 } /* code 00B0, DEGREE SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn38_Prop9 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn38_CharInfo[ 75] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn38_Prop8 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn38_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn38_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn38_Prop7 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn38_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn38_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn38_Prop6 = {
   0x005C /* first character */
  ,0x005C /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn38_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn38_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn38_Prop5 = {
   0x0040 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn38_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn38_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn38_Prop4 = {
   0x002D /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn38_CharInfo[  6] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn38_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn38_Prop3 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn38_CharInfo[  4] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn38_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn38_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn38_CharInfo[  3] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn38_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn38_Prop1 = {
   0x0020 /* first character */
  ,0x0022 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn38_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn38_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn38 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,38 /* height of font  */
  ,38 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTStdCn38_Prop1}
  ,31 /* Baseline */
  ,17 /* Height of lowercase characters */
  ,23 /* Height of capital characters */
};

