/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Std Cn20.c                            *
* Font:        HelveticaNeueLT Std Cn                                *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 20                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\WB\MDK5\fonts_all.txt                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn20;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0021[ 12] = { /* code 0021, EXCLAMATION MARK */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0022[  5] = { /* code 0022, QUOTATION MARK */
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0025[ 24] = { /* code 0025, PERCENT SIGN */
  _XXXX___,_XX_____,
  XX__XX__,_X______,
  XX__XX__,XX______,
  XX__XX__,X_______,
  XX__XX_X,X_______,
  _XXXX__X,________,
  ______X_,_XXX____,
  _____XX_,XX_XX___,
  ____XX__,XX_XX___,
  ____XX__,XX_XX___,
  ___XX___,XX_XX___,
  __XXX___,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0028[ 15] = { /* code 0028, LEFT PARENTHESIS */
  __XX____,
  _XX_____,
  _XX_____,
  _X______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______,
  _XX_____,
  _XX_____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0029[ 15] = { /* code 0029, RIGHT PARENTHESIS */
  XX______,
  _XX_____,
  _XX_____,
  __X_____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __X_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_002D[  2] = { /* code 002D, HYPHEN-MINUS */
  XXXXX___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_002E[  3] = { /* code 002E, FULL STOP */
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_002F[ 12] = { /* code 002F, SOLIDUS */
  ____XX__,
  ____X___,
  ___XX___,
  ___XX___,
  ___X____,
  __XX____,
  __XX____,
  __X_____,
  _XX_____,
  _XX_____,
  _X______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0030[ 12] = { /* code 0030, DIGIT ZERO */
  __XXX___,
  _XX__X__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _X__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0031[ 12] = { /* code 0031, DIGIT ONE */
  __XX____,
  __XX____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0032[ 12] = { /* code 0032, DIGIT TWO */
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  _____XX_,
  _____XX_,
  ____XX__,
  __XXXX__,
  __XXX___,
  _XXX____,
  _XX_____,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0033[ 12] = { /* code 0033, DIGIT THREE */
  _XXXX___,
  XX__XX__,
  XX__XX__,
  ____XX__,
  ____X___,
  __XXXX__,
  ____XXX_,
  _____XX_,
  XX___XX_,
  XX___XX_,
  XX___X__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0034[ 12] = { /* code 0034, DIGIT FOUR */
  ____XXX_,
  ____XXX_,
  ___XXXX_,
  ___XXXX_,
  __XX_XX_,
  __XX_XX_,
  _XX__XX_,
  XX___XX_,
  XXXXXXXX,
  XXXXXXXX,
  _____XX_,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0035[ 12] = { /* code 0035, DIGIT FIVE */
  _XXXXXX_,
  _XXXXXX_,
  XX______,
  XX__XX__,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  _____XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0036[ 12] = { /* code 0036, DIGIT SIX */
  __XXXX__,
  _XX__XX_,
  XX___XX_,
  XX______,
  XX_XXXX_,
  XXXXXXX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX___X_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0037[ 12] = { /* code 0037, DIGIT SEVEN */
  XXXXXXX_,
  XXXXXXX_,
  ____XXX_,
  ____XX__,
  ___XXX__,
  ___XX___,
  ___XX___,
  __XXX___,
  __XX____,
  __XX____,
  __XX____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0038[ 12] = { /* code 0038, DIGIT EIGHT */
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  _XX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0039[ 12] = { /* code 0039, DIGIT NINE */
  __XXXX__,
  _X___XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX___XXX,
  _XXXXXXX,
  _XXXX_XX,
  ______XX,
  _XX___XX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_003A[  9] = { /* code 003A, COLON */
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0040[ 24] = { /* code 0040, COMMERCIAL AT */
  ____XXXX,X_______,
  ___XX___,_XX_____,
  __XX____,__XX____,
  _XX__XXX,__XX____,
  _X__XXXX,XX_XX___,
  XX_XX___,XX_XX___,
  XX_XX___,X__XX___,
  XX_XX__X,X__X____,
  _X__XXXX,XXX_____,
  _XX_XXX_,X_______,
  __XX____,__XX____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0041[ 24] = { /* code 0041, LATIN CAPITAL LETTER A */
  ___XXX__,________,
  ___XXX__,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  _XXX_XXX,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0042[ 12] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXX__,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0043[ 12] = { /* code 0043, LATIN CAPITAL LETTER C */
  __XXX___,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX______,
  XX______,
  XX______,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0044[ 12] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXX__,
  XXXXXXX_,
  XX___XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX___XX_,
  XXXXXXX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0045[ 12] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0046[ 12] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XXXXXX__,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0047[ 12] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXX___,
  _XXXXX__,
  XXX__XX_,
  XX___XX_,
  XX______,
  XX__XXXX,
  XX__XXXX,
  XX____XX,
  XX___XXX,
  XXX__XXX,
  _XXXXXXX,
  __XXX_XX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0048[ 12] = { /* code 0048, LATIN CAPITAL LETTER H */
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXXX_,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0049[ 12] = { /* code 0049, LATIN CAPITAL LETTER I */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_004A[ 12] = { /* code 004A, LATIN CAPITAL LETTER J */
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  _____XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_004B[ 12] = { /* code 004B, LATIN CAPITAL LETTER K */
  XX___XXX,
  XX__XXX_,
  XX_XXX__,
  XX_XX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXXX__,
  XX__XX__,
  XX__XXX_,
  XX___XX_,
  XX___XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_004C[ 12] = { /* code 004C, LATIN CAPITAL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XXXXXX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_004D[ 24] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXX____X,XX______,
  XXXX__XX,XX______,
  XXXX__XX,XX______,
  XXXX__XX,XX______,
  XX_X__X_,XX______,
  XX_X__X_,XX______,
  XX_XX_X_,XX______,
  XX_XXXX_,XX______,
  XX_XXXX_,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_004E[ 12] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXX___XX,
  XXX___XX,
  XXXX__XX,
  XXXX__XX,
  XXXX__XX,
  XX_XX_XX,
  XX_XX_XX,
  XX__XXXX,
  XX__XXXX,
  XX__XXXX,
  XX___XXX,
  XX___XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_004F[ 12] = { /* code 004F, LATIN CAPITAL LETTER O */
  __XXXX__,
  _XXXXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0050[ 12] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXX__,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XXXXX___,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0051[ 13] = { /* code 0051, LATIN CAPITAL LETTER Q */
  __XXXX__,
  _XXXXXX_,
  XXX__XX_,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXX_,
  __XXXXXX,
  ______XX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0052[ 12] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXX__,
  XXXXXXX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0053[ 12] = { /* code 0053, LATIN CAPITAL LETTER S */
  __XXX___,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XXX_____,
  _XXXX___,
  __XXXX__,
  ____XXX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0054[ 12] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,
  XXXXXXXX,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0055[ 12] = { /* code 0055, LATIN CAPITAL LETTER U */
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0056[ 24] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX___XX,________,
  _XX___XX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XX_XX_,________,
  __XXXXX_,________,
  ___XXX__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0057[ 24] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___,
  _XX__XXX,__XX____,
  _XX__X_X,__XX____,
  _XX__X_X,__XX____,
  _XX_XX_X,X_XX____,
  _XX_XX_X,X_XX____,
  __X_XX_X,X_X_____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  __XXX___,XXX_____,
  __XXX___,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0058[ 24] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXX___XX,X_______,
  _XXX__XX,________,
  _XXX_XXX,________,
  __XX_XX_,________,
  __XXXXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXXXX_,________,
  __XX_XX_,________,
  _XXX_XXX,________,
  _XX___XX,________,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0059[ 12] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXX__XXX,
  _XX__XX_,
  _XX__XX_,
  _XXX_XX_,
  __XXXX__,
  __XXXX__,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_005A[ 12] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXXX_,
  XXXXXXX_,
  ____XX__,
  ___XXX__,
  ___XX___,
  __XXX___,
  __XX____,
  _XXX____,
  _XX_____,
  XXX_____,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_005C[ 12] = { /* code 005C, REVERSE SOLIDUS */
  XX______,
  _X______,
  _XX_____,
  _XX_____,
  __X_____,
  __XX____,
  __XX____,
  ___X____,
  ___XX___,
  ___XX___,
  ____X___,
  ____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_005F[  1] = { /* code 005F, LOW LINE */
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0061[  9] = { /* code 0061, LATIN SMALL LETTER A */
  _XXXX___,
  XX__XX__,
  ____XX__,
  _XXXXX__,
  XXX_XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0062[ 12] = { /* code 0062, LATIN SMALL LETTER B */
  XX______,
  XX______,
  XX______,
  XX_XXX__,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXX__X__,
  XX_XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0063[  9] = { /* code 0063, LATIN SMALL LETTER C */
  __XX____,
  _XXXX___,
  XX__XX__,
  XX__XX__,
  XX______,
  XX______,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0064[ 12] = { /* code 0064, LATIN SMALL LETTER D */
  ____XX__,
  ____XX__,
  ____XX__,
  _XX_XX__,
  _XXXXX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0065[  9] = { /* code 0065, LATIN SMALL LETTER E */
  _XXXX___,
  _X__XX__,
  XX__XX__,
  XX__XX__,
  XXXXXX__,
  XX______,
  XX__XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0066[ 12] = { /* code 0066, LATIN SMALL LETTER F */
  __XX____,
  _XXX____,
  _XX_____,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0067[ 12] = { /* code 0067, LATIN SMALL LETTER G */
  _XXXXX__,
  _X__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  __X_XX__,
  X___XX__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0068[ 12] = { /* code 0068, LATIN SMALL LETTER H */
  XX______,
  XX______,
  XX______,
  XX_XX___,
  XXXXXX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0069[ 12] = { /* code 0069, LATIN SMALL LETTER I */
  XX______,
  XX______,
  ________,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_006A[ 15] = { /* code 006A, LATIN SMALL LETTER J */
  _XX_____,
  _XX_____,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_006B[ 12] = { /* code 006B, LATIN SMALL LETTER K */
  XX______,
  XX______,
  XX______,
  XX__XXX_,
  XX_XXX__,
  XX_XX___,
  XXXX____,
  XXXXX___,
  XXXXX___,
  XX_XXX__,
  XX__XX__,
  XX__XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_006C[ 12] = { /* code 006C, LATIN SMALL LETTER L */
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_006D[ 18] = { /* code 006D, LATIN SMALL LETTER M */
  XX_XX__X,X_______,
  XXXXXXXX,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_006E[  9] = { /* code 006E, LATIN SMALL LETTER N */
  XXXXX___,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_006F[  9] = { /* code 006F, LATIN SMALL LETTER O */
  _XXXX___,
  _X__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__X___,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0070[ 12] = { /* code 0070, LATIN SMALL LETTER P */
  XX_XXX__,
  XXX__X__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XXXXXX__,
  XX_XXX__,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0071[ 12] = { /* code 0071, LATIN SMALL LETTER Q */
  _XXXXX__,
  _X__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  _XX_XX__,
  ____XX__,
  ____XX__,
  ____XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0072[  9] = { /* code 0072, LATIN SMALL LETTER R */
  XX_X____,
  XXXX____,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0073[  9] = { /* code 0073, LATIN SMALL LETTER S */
  __XXXX__,
  _XX__XX_,
  _XX_____,
  _XXXX___,
  __XXXX__,
  ____XXX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0074[ 12] = { /* code 0074, LATIN SMALL LETTER T */
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXX____,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0075[  9] = { /* code 0075, LATIN SMALL LETTER U */
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0076[  9] = { /* code 0076, LATIN SMALL LETTER V */
  XX___XX_,
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  __XXX___,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0077[ 18] = { /* code 0077, LATIN SMALL LETTER W */
  XXX__XX_,__XX____,
  XXX_XXXX,_XXX____,
  _XX_XXXX,_XX_____,
  _XX_XXXX,_XX_____,
  _XX_XX_X,_XX_____,
  _XX_X__X,_XX_____,
  __XXX__X,XX______,
  __XXX__X,XX______,
  __XXX__X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0078[  9] = { /* code 0078, LATIN SMALL LETTER X */
  XXX__XXX,
  _XX__XX_,
  __XXXX__,
  __XXXX__,
  ___XX___,
  __XXXX__,
  _XXXXXX_,
  _XX__XX_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_0079[ 12] = { /* code 0079, LATIN SMALL LETTER Y */
  XX___XX_,
  XXX_XXX_,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __X_XX__,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  _XXX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_007A[  9] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXX__,
  XXXXXX__,
  ___XX___,
  __XXX___,
  __XX____,
  _XXX____,
  _XX_____,
  XXXXXX__,
  XXXXXX__};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn20_00B0[  5] = { /* code 00B0, DEGREE SIGN */
  _XXX____,
  X___X___,
  X___X___,
  X___X___,
  _XXX____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHelveticaNeueLTStdCn20_CharInfo[76] = {
   {   1,   1,   0,  16,  5, acGUI_FontHelveticaNeueLTStdCn20_0020 } /* code 0020, SPACE */
  ,{   2,  12,   1,   4,   5, acGUI_FontHelveticaNeueLTStdCn20_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   6,   5,   1,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0022 } /* code 0022, QUOTATION MARK */
  ,{  13,  12,   0,   4,  13, acGUI_FontHelveticaNeueLTStdCn20_0025 } /* code 0025, PERCENT SIGN */
  ,{   4,  15,   1,   4,   5, acGUI_FontHelveticaNeueLTStdCn20_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   4,  15,   0,   4,   5, acGUI_FontHelveticaNeueLTStdCn20_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   5,   2,   1,  10,   6, acGUI_FontHelveticaNeueLTStdCn20_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   3,   1,  13,   4, acGUI_FontHelveticaNeueLTStdCn20_002E } /* code 002E, FULL STOP */
  ,{   6,  12,   0,   4,   6, acGUI_FontHelveticaNeueLTStdCn20_002F } /* code 002F, SOLIDUS */
  ,{   7,  12,   1,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0030 } /* code 0030, DIGIT ZERO */
  ,{   4,  12,   1,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0031 } /* code 0031, DIGIT ONE */
  ,{   7,  12,   0,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0032 } /* code 0032, DIGIT TWO */
  ,{   7,  12,   1,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0033 } /* code 0033, DIGIT THREE */
  ,{   8,  12,   0,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0034 } /* code 0034, DIGIT FOUR */
  ,{   7,  12,   0,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  12,   0,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0036 } /* code 0036, DIGIT SIX */
  ,{   7,  12,   1,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0037 } /* code 0037, DIGIT SEVEN */
  ,{   8,  12,   0,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  12,   0,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0039 } /* code 0039, DIGIT NINE */
  ,{   2,   9,   1,   7,   4, acGUI_FontHelveticaNeueLTStdCn20_003A } /* code 003A, COLON */
  ,{  13,  12,   0,   4,  14, acGUI_FontHelveticaNeueLTStdCn20_0040 } /* code 0040, COMMERCIAL AT */
  ,{   9,  12,   0,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   7,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   7,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   8,  12,   1,   4,  10, acGUI_FontHelveticaNeueLTStdCn20_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   6,  12,   1,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   6,  12,   1,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   8,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   7,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  12,   1,   4,   4, acGUI_FontHelveticaNeueLTStdCn20_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   7,  12,   0,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   8,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   6,  12,   1,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  10,  12,   1,   4,  13, acGUI_FontHelveticaNeueLTStdCn20_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   8,  12,   1,   4,  10, acGUI_FontHelveticaNeueLTStdCn20_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   8,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   7,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   8,  13,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   7,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   7,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   8,  12,   0,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   7,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   9,  12,   0,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  13,  12,   0,   4,  13, acGUI_FontHelveticaNeueLTStdCn20_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   9,  12,   0,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   8,  12,   0,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   7,  12,   1,   4,   8, acGUI_FontHelveticaNeueLTStdCn20_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   6,  12,   0,   4,   6, acGUI_FontHelveticaNeueLTStdCn20_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   8,   1,   0,  17,   9, acGUI_FontHelveticaNeueLTStdCn20_005F } /* code 005F, LOW LINE */
  ,{   6,   9,   1,   7,   8, acGUI_FontHelveticaNeueLTStdCn20_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   7,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   6,   9,   1,   7,   8, acGUI_FontHelveticaNeueLTStdCn20_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   6,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   6,   9,   1,   7,   8, acGUI_FontHelveticaNeueLTStdCn20_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   4,  12,   0,   4,   5, acGUI_FontHelveticaNeueLTStdCn20_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   6,  12,   1,   7,   9, acGUI_FontHelveticaNeueLTStdCn20_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   6,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   2,  12,   1,   4,   4, acGUI_FontHelveticaNeueLTStdCn20_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   3,  15,   0,   4,   4, acGUI_FontHelveticaNeueLTStdCn20_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   7,  12,   1,   4,   9, acGUI_FontHelveticaNeueLTStdCn20_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   2,  12,   1,   4,   4, acGUI_FontHelveticaNeueLTStdCn20_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  10,   9,   1,   7,  13, acGUI_FontHelveticaNeueLTStdCn20_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   6,   9,   1,   7,   9, acGUI_FontHelveticaNeueLTStdCn20_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   6,   9,   1,   7,   8, acGUI_FontHelveticaNeueLTStdCn20_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   7,  12,   1,   7,   9, acGUI_FontHelveticaNeueLTStdCn20_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   6,  12,   1,   7,   9, acGUI_FontHelveticaNeueLTStdCn20_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   4,   9,   1,   7,   6, acGUI_FontHelveticaNeueLTStdCn20_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   7,   9,   0,   7,   8, acGUI_FontHelveticaNeueLTStdCn20_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   4,  12,   0,   4,   5, acGUI_FontHelveticaNeueLTStdCn20_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   6,   9,   1,   7,   9, acGUI_FontHelveticaNeueLTStdCn20_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   7,   9,   0,   7,   8, acGUI_FontHelveticaNeueLTStdCn20_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  12,   9,   0,   7,  12, acGUI_FontHelveticaNeueLTStdCn20_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   8,   9,   0,   7,   8, acGUI_FontHelveticaNeueLTStdCn20_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   7,  12,   0,   7,   8, acGUI_FontHelveticaNeueLTStdCn20_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   6,   9,   1,   7,   7, acGUI_FontHelveticaNeueLTStdCn20_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   5,   5,   1,   4,   7, acGUI_FontHelveticaNeueLTStdCn20_00B0 } /* code 00B0, DEGREE SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn20_Prop9 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn20_CharInfo[ 75] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn20_Prop8 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn20_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn20_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn20_Prop7 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn20_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn20_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn20_Prop6 = {
   0x005C /* first character */
  ,0x005C /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn20_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn20_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn20_Prop5 = {
   0x0040 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn20_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn20_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn20_Prop4 = {
   0x002D /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn20_CharInfo[  6] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn20_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn20_Prop3 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn20_CharInfo[  4] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn20_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn20_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn20_CharInfo[  3] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn20_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn20_Prop1 = {
   0x0020 /* first character */
  ,0x0022 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn20_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn20_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn20 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTStdCn20_Prop1}
  ,16 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,12 /* Height of capital characters */
};

