/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Std Cn32.c                            *
* Font:        HelveticaNeueLT Std Cn                                *
* Height:      32                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 32                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\WB\MDK5\fonts_all.txt                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn32;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0021[ 20] = { /* code 0021, EXCLAMATION MARK */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0022[  9] = { /* code 0022, QUOTATION MARK */
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0025[ 63] = { /* code 0025, PERCENT SIGN */
  __XXXX__,_____XXX,________,
  _XXXXXX_,_____XX_,________,
  XXX__XXX,____XXX_,________,
  XXX__XXX,____XX__,________,
  XXX__XXX,___XXX__,________,
  XXX__XXX,___XX___,________,
  XXX__XXX,__XX____,________,
  XXX__XXX,__XX____,________,
  XXX__XXX,_XX_____,________,
  _XXXXXX_,_XX_____,________,
  __XXXX__,XX___XXX,X_______,
  ________,XX__XXXX,XX______,
  _______X,X__XXX__,XXX_____,
  _______X,X__XXX__,XXX_____,
  ______XX,___XXX__,XXX_____,
  ______XX,___XXX__,XXX_____,
  _____XX_,___XXX__,XXX_____,
  _____XX_,___XXX__,XXX_____,
  ____XX__,____XXXX,XX______,
  ____XX__,_____XXX,X_______,
  ___X____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0028[ 25] = { /* code 0028, LEFT PARENTHESIS */
  ____XXX_,
  ___XXX__,
  ___XXX__,
  __XXX___,
  __XXX___,
  _XXXX___,
  _XXX____,
  _XXX____,
  _XXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXXX___,
  __XXX___,
  __XXX___,
  ___XXX__,
  ___XXX__,
  ____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0029[ 25] = { /* code 0029, RIGHT PARENTHESIS */
  XXX_____,
  _XXX____,
  _XXX____,
  __XXX___,
  __XXX___,
  __XXXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXXX_,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  __XXXX__,
  __XXX___,
  __XXX___,
  _XXX____,
  _XXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_002D[  3] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_002E[  4] = { /* code 002E, FULL STOP */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_002F[ 40] = { /* code 002F, SOLIDUS */
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  XXX_____,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0030[ 40] = { /* code 0030, DIGIT ZERO */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  __XXX___,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXX___,XXX_____,
  __XXXXXX,XXX_____,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0031[ 20] = { /* code 0031, DIGIT ONE */
  _____XXX,
  _____XXX,
  ____XXXX,
  ___XXXXX,
  XXXXXXXX,
  XXXXXXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX,
  ____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0032[ 40] = { /* code 0032, DIGIT TWO */
  ___XXXXX,X_______,
  _XXXXXXX,XXX_____,
  _XXXX__X,XXX_____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  ________,XXXX____,
  ________,XXX_____,
  _______X,XXX_____,
  ______XX,XXX_____,
  _____XXX,XX______,
  ____XXXX,X_______,
  ___XXXXX,________,
  __XXXXX_,________,
  __XXXX__,________,
  _XXXXX__,________,
  _XXXX___,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0033[ 40] = { /* code 0033, DIGIT THREE */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  __XXX___,XXX_____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  ________,XXXX____,
  ________,XXX_____,
  _______X,XXX_____,
  ____XXXX,XX______,
  ____XXXX,XX______,
  _______X,XXX_____,
  ________,XXX_____,
  ________,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXXX__X,XXX_____,
  _XXXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0034[ 40] = { /* code 0034, DIGIT FOUR */
  ______XX,XXX_____,
  ______XX,XXX_____,
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  ____XXXX,XXX_____,
  ____XXXX,XXX_____,
  ___XXX_X,XXX_____,
  ___XXX_X,XXX_____,
  __XXX__X,XXX_____,
  __XXX__X,XXX_____,
  _XXX___X,XXX_____,
  _XXX___X,XXX_____,
  XXX____X,XXX_____,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0035[ 40] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX_XXX,X_______,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXX___X,XXX_____,
  XXXX____,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX___X,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0036[ 40] = { /* code 0036, DIGIT SIX */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  __XXX___,XXX_____,
  _XXXX___,XXXX____,
  _XXX____,XXXX____,
  _XXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX__XX,XX______,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXX___,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXX____,_XXXX___,
  _XXXX___,XXXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0037[ 40] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  ________,XXX_____,
  _______X,XXX_____,
  _______X,XX______,
  ______XX,XX______,
  ______XX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXX__,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0038[ 40] = { /* code 0038, DIGIT EIGHT */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  __XXXX_X,XXX_____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  _XXXX___,XXXX____,
  __XXX___,XXX_____,
  __XXXX_X,XXX_____,
  ___XXXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXX___,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,XXXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0039[ 40] = { /* code 0039, DIGIT NINE */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  _XXXX___,XXXX____,
  _XXX____,XXXX____,
  XXXX____,_XXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,XXXXX___,
  _XXXX___,XXXXX___,
  _XXXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  ___XXXX_,_XXXX___,
  ________,_XXXX___,
  ________,_XXX____,
  _XXXX___,_XXX____,
  __XXX___,XXXX____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_003A[ 14] = { /* code 003A, COLON */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0040[ 60] = { /* code 0040, COMMERCIAL AT */
  _______X,XXXXX___,________,
  _____XXX,XXXXXXX_,________,
  ____XXXX,____XXXX,X_______,
  ___XXX__,______XX,XX______,
  __XXX___,_______X,XXX_____,
  _XXX____,XXX__XXX,XXX_____,
  _XXX__XX,XXXX_XX_,_XXX____,
  _XX__XXX,XXXXXXX_,_XXX____,
  XXX__XXX,___XXXX_,_XXX____,
  XXX_XXX_,____XXX_,_XXX____,
  XXX_XXX_,____XX__,_XXX____,
  XXX_XXX_,___XXX__,_XX_____,
  _XX_XXX_,__XXXX__,XXX_____,
  _XXX_XXX,XXXXXXXX,XX______,
  _XXX_XXX,XXXXXXXX,X_______,
  __XXX_XX,XX__XXX_,__X_____,
  ___XXX__,_______X,XX______,
  ___XXXXX,_____XXX,X_______,
  _____XXX,XXXXXXXX,________,
  _______X,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0041[ 40] = { /* code 0041, LATIN CAPITAL LETTER A */
  _____XXX,XX______,
  _____XXX,XX______,
  ____XXXX,XX______,
  ____XXX_,XXX_____,
  ____XXX_,XXX_____,
  ____XXX_,XXX_____,
  ___XXXX_,XXXX____,
  ___XXXX_,XXXX____,
  ___XXX__,_XXX____,
  ___XXX__,_XXX____,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXXXX,XXXXX___,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _XXXX___,__XXXX__,
  _XXXX___,__XXXX__,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0042[ 40] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXXX,X_______,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXX___X,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX___X,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XXXX____,
  XXXX____,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0043[ 40] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,X_______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  _XXXX___,XXXX____,
  _XXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXX____,_XXXX___,
  _XXXX___,XXXX____,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0044[ 40] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXXX,X_______,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0045[ 40] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0046[ 40] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0047[ 40] = { /* code 0047, LATIN CAPITAL LETTER G */
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXX___,XXXXX___,
  _XXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX__XX,XXXXX___,
  XXXX__XX,XXXXX___,
  XXXX__XX,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,XXXXX___,
  _XXXXXXX,XXXXX___,
  __XXXXXX,X_XXX___,
  ____XXXX,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0048[ 40] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0049[ 20] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_004A[ 40] = { /* code 004A, LATIN CAPITAL LETTER J */
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  _XXXXXXX,XX______,
  __XXXXXX,XX______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_004B[ 40] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXXX____,_XXXX___,
  XXXX____,XXXX____,
  XXXX___X,XXXX____,
  XXXX___X,XXX_____,
  XXXX__XX,XX______,
  XXXX_XXX,XX______,
  XXXX_XXX,X_______,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXX_XX,XX______,
  XXXX__XX,XX______,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_004C[ 40] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_004D[ 60] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXXXXX__,____XXXX,XX______,
  XXXXXX__,____XXXX,XX______,
  XXXXXXX_,___XXXXX,XX______,
  XXXXXXX_,___XXXXX,XX______,
  XXXXXXX_,___XXXXX,XX______,
  XXXXXXX_,___XXXXX,XX______,
  XXXXXXX_,___XXXXX,XX______,
  XXXX_XXX,__XXX_XX,XX______,
  XXXX_XXX,__XXX_XX,XX______,
  XXXX_XXX,__XXX_XX,XX______,
  XXXX_XXX,__XXX_XX,XX______,
  XXXX__XX,__XX__XX,XX______,
  XXXX__XX,XXXX__XX,XX______,
  XXXX__XX,XXXX__XX,XX______,
  XXXX__XX,XXXX__XX,XX______,
  XXXX__XX,XXXX__XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_004E[ 40] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXXXX___,_XXXX___,
  XXXXX___,_XXXX___,
  XXXXXX__,_XXXX___,
  XXXXXX__,_XXXX___,
  XXXXXX__,_XXXX___,
  XXXXXX__,_XXXX___,
  XXXXXXX_,_XXXX___,
  XXXXXXX_,_XXXX___,
  XXXX_XX_,_XXXX___,
  XXXX_XXX,_XXXX___,
  XXXX_XXX,_XXXX___,
  XXXX__XX,_XXXX___,
  XXXX__XX,XXXXX___,
  XXXX__XX,XXXXX___,
  XXXX___X,XXXXX___,
  XXXX___X,XXXXX___,
  XXXX___X,XXXXX___,
  XXXX____,XXXXX___,
  XXXX____,XXXXX___,
  XXXX____,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_004F[ 40] = { /* code 004F, LATIN CAPITAL LETTER O */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXX___,XXXX____,
  _XXX____,_XXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXX____,_XXX____,
  _XXXX___,XXXX____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0050[ 40] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXXX____,
  XXXX____,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,X_______,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0051[ 44] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXX___,XXXX____,
  _XXX____,_XXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  _XXX____,_XXX____,
  _XXXX___,XXXX____,
  __XXXXXX,XXXX____,
  __XXXXXX,XXXX____,
  ____XXXX,XXXXX___,
  ________,__XXX___,
  ________,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0052[ 40] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXXX,XX______,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXX____,XXXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,XXXX____,
  XXXX____,XXXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0053[ 40] = { /* code 0053, LATIN CAPITAL LETTER S */
  ___XXXXX,X_______,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  XXXX___X,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,________,
  XXXXX___,________,
  _XXXXXX_,________,
  __XXXXXX,X_______,
  ___XXXXX,XXX_____,
  _____XXX,XXX_____,
  _______X,XXXX____,
  ________,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXXX___,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0054[ 40] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0055[ 40] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXXX__X,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0056[ 40] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  __XXX___,_XXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  ___XXX__,XXX_____,
  ___XXXXX,XXX_____,
  ___XXXXX,XXX_____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______,
  ____XXXX,XX______,
  ____XXXX,XX______,
  ____XXXX,XX______,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0057[ 60] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  XXXX____,XXXX____,XXXX____,
  _XXX____,XXXX____,XXX_____,
  _XXX___X,XXXXX___,XXX_____,
  _XXXX__X,XXXXX__X,XXX_____,
  _XXXX__X,XXXXX__X,XXX_____,
  _XXXX__X,XXXXX__X,XXX_____,
  __XXX__X,XXXXX__X,XX______,
  __XXX__X,X__XX__X,XX______,
  __XXX__X,X__XX__X,XX______,
  __XXX_XX,X__XXX_X,XX______,
  __XXX_XX,X__XXX_X,XX______,
  __XXXXXX,X__XXXXX,XX______,
  ___XXXXX,X__XXXXX,X_______,
  ___XXXXX,____XXXX,X_______,
  ___XXXXX,____XXXX,X_______,
  ___XXXXX,____XXXX,X_______,
  ___XXXXX,____XXXX,X_______,
  ___XXXXX,____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0058[ 40] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXXXX___,_XXXXX__,
  _XXXX___,_XXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  ___XXXXX,XXX_____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______,
  ____XXXX,XX______,
  _____XXX,X_______,
  ____XXXX,XX______,
  ____XXXX,XX______,
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  ___XXX_X,XXX_____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  XXXX____,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0059[ 40] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXXXX___,_XXXXX__,
  _XXXX___,_XXXX___,
  _XXXX___,_XXXX___,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  ___XXXXX,XXX_____,
  ___XXXXX,XXX_____,
  ____XXXX,XX______,
  ____XXXX,XX______,
  ____XXXX,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_005A[ 40] = { /* code 005A, LATIN CAPITAL LETTER Z */
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _______X,XXX_____,
  ______XX,XXX_____,
  ______XX,XX______,
  ______XX,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXX__,________,
  __XXXX__,________,
  _XXXX___,________,
  _XXXX___,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_005C[ 40] = { /* code 005C, REVERSE SOLIDUS */
  XXX_____,________,
  XXX_____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ______XX,X_______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0061[ 28] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXXXX,________,
  _XXXXXXX,XX______,
  XXX____X,XXX_____,
  XXX____X,XXX_____,
  _______X,XXX_____,
  ____XXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXX_X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXX_X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0062[ 40] = { /* code 0062, LATIN SMALL LETTER B */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX_XXX,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XXXXX__X,XXX_____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXX_____,
  XXXXX__X,XXX_____,
  XXXXXXXX,XX______,
  XXXX_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0063[ 28] = { /* code 0063, LATIN SMALL LETTER C */
  ____XXXX,________,
  __XXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  _XXXX__X,XX______,
  _XXXXXXX,XX______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0064[ 40] = { /* code 0064, LATIN SMALL LETTER D */
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  ___XXX_X,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX__XX,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  _XXX__XX,XXX_____,
  _XXXXXXX,XXX_____,
  ___XXX_X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0065[ 28] = { /* code 0065, LATIN SMALL LETTER E */
  ___XXXXX,________,
  __XXXXXX,XX______,
  _XXX___X,XX______,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXX____,________,
  XXXX____,________,
  XXXX___X,XXX_____,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0066[ 20] = { /* code 0066, LATIN SMALL LETTER F */
  ____XXXX,
  ___XXXXX,
  __XXXXXX,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  XXXXXXXX,
  XXXXXXXX,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0067[ 38] = { /* code 0067, LATIN SMALL LETTER G */
  ___XXX_X,XXX_____,
  __XXXXXX,XXX_____,
  _XXX__XX,XXX_____,
  _XXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  _XXX__XX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ___XXX_X,XXX_____,
  _______X,XXX_____,
  XXXX___X,XXX_____,
  XXXX__XX,XX______,
  _XXXXXXX,XX______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0068[ 40] = { /* code 0068, LATIN SMALL LETTER H */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX_XXX,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0069[ 20] = { /* code 0069, LATIN SMALL LETTER I */
  XXXX____,
  XXXX____,
  XXXX____,
  ________,
  ________,
  ________,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_006A[ 25] = { /* code 006A, LATIN SMALL LETTER J */
  __XXXX__,
  __XXXX__,
  __XXXX__,
  ________,
  ________,
  ________,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  XXXXXX__,
  XXXXX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_006B[ 40] = { /* code 006B, LATIN SMALL LETTER K */
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX___X,XXXX____,
  XXXX___X,XXX_____,
  XXXX__XX,XX______,
  XXXX_XXX,X_______,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXX__XX,XX______,
  XXXX__XX,XX______,
  XXXX___X,XXX_____,
  XXXX____,XXXX____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_006C[ 20] = { /* code 006C, LATIN SMALL LETTER L */
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_006D[ 42] = { /* code 006D, LATIN SMALL LETTER M */
  XXXX_XXX,X____XXX,________,
  XXXXXXXX,XX_XXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_006E[ 28] = { /* code 006E, LATIN SMALL LETTER N */
  XXXX_XXX,X_______,
  XXXXXXXX,XX______,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_006F[ 28] = { /* code 006F, LATIN SMALL LETTER O */
  ___XXXXX,________,
  __XXXXXX,XX______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  _XXXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0070[ 38] = { /* code 0070, LATIN SMALL LETTER P */
  XXXX_XXX,X_______,
  XXXXXXXX,XXX_____,
  XXXXX__X,XXX_____,
  XXXX____,XXX_____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  XXXXX__X,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  XXXX_XXX,X_______,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________,
  XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0071[ 38] = { /* code 0071, LATIN SMALL LETTER Q */
  ___XXX_X,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXX_XX,XXX_____,
  _XXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  _XXX__XX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ___XXX_X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____,
  _______X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0072[ 14] = { /* code 0072, LATIN SMALL LETTER R */
  XXXX__XX,
  XXXX_XXX,
  XXXXXXXX,
  XXXXXXXX,
  XXXXX___,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0073[ 28] = { /* code 0073, LATIN SMALL LETTER S */
  ___XXXXX,________,
  _XXXXXXX,X_______,
  XXXX___X,XX______,
  XXXX___X,XX______,
  XXXX____,________,
  _XXXXX__,________,
  _XXXXXXX,X_______,
  ___XXXXX,XX______,
  _____XXX,XXX_____,
  XXX____X,XXX_____,
  XXX____X,XXX_____,
  XXX____X,XXX_____,
  _XXXXXXX,XX______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0074[ 18] = { /* code 0074, LATIN SMALL LETTER T */
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  XXXXXXXX,
  XXXXXXXX,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXXXX,
  ___XXXXX,
  ____XXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0075[ 28] = { /* code 0075, LATIN SMALL LETTER U */
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXX_X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0076[ 28] = { /* code 0076, LATIN SMALL LETTER V */
  XXXX____,XXXX____,
  _XXX____,XXX_____,
  _XXXX___,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  __XXX__X,XX______,
  __XXX__X,XX______,
  __XXXX_X,XX______,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0077[ 42] = { /* code 0077, LATIN SMALL LETTER W */
  XXXX___X,XXXX___X,XXX_____,
  XXXX___X,XXXX___X,XXX_____,
  _XXX___X,XXXX___X,XX______,
  _XXX___X,XXXX___X,XX______,
  _XXXX__X,X_XX__XX,XX______,
  _XXXX_XX,X_XXX_XX,XX______,
  __XXX_XX,X_XXX_XX,X_______,
  __XXX_XX,X_XXX_XX,X_______,
  __XXX_XX,X_XXX_XX,X_______,
  __XXXXXX,___XX_XX,X_______,
  ___XXXXX,___XXXXX,________,
  ___XXXXX,___XXXXX,________,
  ___XXXXX,___XXXXX,________,
  ___XXXXX,___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0078[ 28] = { /* code 0078, LATIN SMALL LETTER X */
  XXXX____,XXXX____,
  _XXXX__X,XXX_____,
  __XXX__X,XX______,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,X_______,
  __XXXXXX,XX______,
  __XXX__X,XX______,
  _XXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_0079[ 38] = { /* code 0079, LATIN SMALL LETTER Y */
  XXXX____,XXXX____,
  _XXX____,XXX_____,
  _XXXX___,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  __XXX__X,XX______,
  __XXX__X,XX______,
  __XXXX_X,XX______,
  ___XXXXX,XX______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_007A[ 28] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  ____XXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXX__,________,
  _XXXX___,________,
  _XXXX___,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn32_00B0[  9] = { /* code 00B0, DEGREE SIGN */
  __XXXX__,
  _XXXXXX_,
  XXX__XXX,
  XX____XX,
  XX____XX,
  XX____XX,
  XXX__XXX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHelveticaNeueLTStdCn32_CharInfo[76] = {
   {   1,   1,   0,  26,  15, acGUI_FontHelveticaNeueLTStdCn32_0020 } /* code 0020, SPACE */
  ,{   4,  20,   2,   6,   8, acGUI_FontHelveticaNeueLTStdCn32_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   8,   9,   2,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0022 } /* code 0022, QUOTATION MARK */
  ,{  19,  21,   1,   6,  21, acGUI_FontHelveticaNeueLTStdCn32_0025 } /* code 0025, PERCENT SIGN */
  ,{   7,  25,   1,   6,   8, acGUI_FontHelveticaNeueLTStdCn32_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   7,  25,   0,   6,   8, acGUI_FontHelveticaNeueLTStdCn32_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   8,   3,   1,  17,  10, acGUI_FontHelveticaNeueLTStdCn32_002D } /* code 002D, HYPHEN-MINUS */
  ,{   4,   4,   1,  22,   6, acGUI_FontHelveticaNeueLTStdCn32_002E } /* code 002E, FULL STOP */
  ,{   9,  20,   0,   6,   9, acGUI_FontHelveticaNeueLTStdCn32_002F } /* code 002F, SOLIDUS */
  ,{  13,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0030 } /* code 0030, DIGIT ZERO */
  ,{   8,  20,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0031 } /* code 0031, DIGIT ONE */
  ,{  12,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0032 } /* code 0032, DIGIT TWO */
  ,{  12,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0033 } /* code 0033, DIGIT THREE */
  ,{  13,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0034 } /* code 0034, DIGIT FOUR */
  ,{  12,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0035 } /* code 0035, DIGIT FIVE */
  ,{  13,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0036 } /* code 0036, DIGIT SIX */
  ,{  12,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0037 } /* code 0037, DIGIT SEVEN */
  ,{  13,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0038 } /* code 0038, DIGIT EIGHT */
  ,{  13,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0039 } /* code 0039, DIGIT NINE */
  ,{   4,  14,   1,  12,   6, acGUI_FontHelveticaNeueLTStdCn32_003A } /* code 003A, COLON */
  ,{  20,  20,   1,   6,  22, acGUI_FontHelveticaNeueLTStdCn32_0040 } /* code 0040, COMMERCIAL AT */
  ,{  15,  20,   0,   6,  15, acGUI_FontHelveticaNeueLTStdCn32_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  13,  20,   1,   6,  15, acGUI_FontHelveticaNeueLTStdCn32_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  13,  20,   1,   6,  14, acGUI_FontHelveticaNeueLTStdCn32_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  13,  20,   1,   6,  15, acGUI_FontHelveticaNeueLTStdCn32_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  11,  20,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{  11,  20,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  13,  20,   1,   6,  15, acGUI_FontHelveticaNeueLTStdCn32_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  13,  20,   1,   6,  15, acGUI_FontHelveticaNeueLTStdCn32_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   4,  20,   1,   6,   7, acGUI_FontHelveticaNeueLTStdCn32_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  11,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  14,  20,   1,   6,  14, acGUI_FontHelveticaNeueLTStdCn32_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{  11,  20,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  18,  20,   1,   6,  20, acGUI_FontHelveticaNeueLTStdCn32_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  13,  20,   1,   6,  15, acGUI_FontHelveticaNeueLTStdCn32_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  13,  20,   1,   6,  15, acGUI_FontHelveticaNeueLTStdCn32_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  13,  20,   1,   6,  14, acGUI_FontHelveticaNeueLTStdCn32_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  13,  22,   1,   6,  15, acGUI_FontHelveticaNeueLTStdCn32_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  14,  20,   1,   6,  15, acGUI_FontHelveticaNeueLTStdCn32_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  12,  20,   1,   6,  14, acGUI_FontHelveticaNeueLTStdCn32_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  12,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  12,  20,   1,   6,  15, acGUI_FontHelveticaNeueLTStdCn32_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  14,  20,   0,   6,  14, acGUI_FontHelveticaNeueLTStdCn32_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  20,  20,   0,   6,  21, acGUI_FontHelveticaNeueLTStdCn32_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  14,  20,   0,   6,  14, acGUI_FontHelveticaNeueLTStdCn32_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  14,  20,   0,   6,  14, acGUI_FontHelveticaNeueLTStdCn32_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  12,  20,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn32_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   9,  20,   0,   6,   9, acGUI_FontHelveticaNeueLTStdCn32_005C } /* code 005C, REVERSE SOLIDUS */
  ,{  14,   1,   0,  28,  14, acGUI_FontHelveticaNeueLTStdCn32_005F } /* code 005F, LOW LINE */
  ,{  11,  14,   1,  12,  13, acGUI_FontHelveticaNeueLTStdCn32_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{  12,  20,   1,   6,  14, acGUI_FontHelveticaNeueLTStdCn32_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{  11,  14,   1,  12,  13, acGUI_FontHelveticaNeueLTStdCn32_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{  11,  20,   1,   6,  14, acGUI_FontHelveticaNeueLTStdCn32_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{  11,  14,   1,  12,  13, acGUI_FontHelveticaNeueLTStdCn32_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   8,  20,   0,   6,   8, acGUI_FontHelveticaNeueLTStdCn32_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{  11,  19,   1,  12,  14, acGUI_FontHelveticaNeueLTStdCn32_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{  11,  20,   1,   6,  14, acGUI_FontHelveticaNeueLTStdCn32_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   4,  20,   1,   6,   6, acGUI_FontHelveticaNeueLTStdCn32_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   6,  25,  -1,   6,   6, acGUI_FontHelveticaNeueLTStdCn32_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  12,  20,   1,   6,  14, acGUI_FontHelveticaNeueLTStdCn32_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   4,  20,   1,   6,   6, acGUI_FontHelveticaNeueLTStdCn32_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  18,  14,   1,  12,  20, acGUI_FontHelveticaNeueLTStdCn32_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{  11,  14,   1,  12,  14, acGUI_FontHelveticaNeueLTStdCn32_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{  11,  14,   1,  12,  13, acGUI_FontHelveticaNeueLTStdCn32_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{  12,  19,   1,  12,  14, acGUI_FontHelveticaNeueLTStdCn32_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{  11,  19,   1,  12,  14, acGUI_FontHelveticaNeueLTStdCn32_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   8,  14,   1,  12,   9, acGUI_FontHelveticaNeueLTStdCn32_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{  11,  14,   1,  12,  12, acGUI_FontHelveticaNeueLTStdCn32_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   8,  18,   0,   8,   8, acGUI_FontHelveticaNeueLTStdCn32_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{  11,  14,   1,  12,  14, acGUI_FontHelveticaNeueLTStdCn32_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  12,  14,   0,  12,  12, acGUI_FontHelveticaNeueLTStdCn32_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  19,  14,   0,  12,  19, acGUI_FontHelveticaNeueLTStdCn32_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{  12,  14,   0,  12,  12, acGUI_FontHelveticaNeueLTStdCn32_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{  12,  19,   0,  12,  12, acGUI_FontHelveticaNeueLTStdCn32_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{  10,  14,   1,  12,  12, acGUI_FontHelveticaNeueLTStdCn32_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   8,   9,   1,   6,  11, acGUI_FontHelveticaNeueLTStdCn32_00B0 } /* code 00B0, DEGREE SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn32_Prop9 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn32_CharInfo[ 75] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn32_Prop8 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn32_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn32_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn32_Prop7 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn32_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn32_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn32_Prop6 = {
   0x005C /* first character */
  ,0x005C /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn32_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn32_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn32_Prop5 = {
   0x0040 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn32_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn32_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn32_Prop4 = {
   0x002D /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn32_CharInfo[  6] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn32_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn32_Prop3 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn32_CharInfo[  4] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn32_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn32_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn32_CharInfo[  3] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn32_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn32_Prop1 = {
   0x0020 /* first character */
  ,0x0022 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn32_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn32_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn32 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,32 /* height of font  */
  ,32 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTStdCn32_Prop1}
  ,26 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,20 /* Height of capital characters */
};

