/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Std Cn23.c                            *
* Font:        HelveticaNeueLT Std Cn                                *
* Height:      23                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 23                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\WB\MDK5\fonts_all.txt                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn23;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0021[ 14] = { /* code 0021, EXCLAMATION MARK */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  _X______,
  ________,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0022[  6] = { /* code 0022, QUOTATION MARK */
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XX_XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0025[ 28] = { /* code 0025, PERCENT SIGN */
  _XXX____,__XX____,
  XX_XX___,_XX_____,
  XX_XX___,XX______,
  XX_XX___,XX______,
  XX_XX__X,X_______,
  XX_XX__X,X_______,
  _XXX__XX,________,
  ______X_,_XXXX___,
  _____XX_,XX__XX__,
  _____X__,XX__XX__,
  ____X___,XX__XX__,
  ____X___,XX__XX__,
  ___X____,XX__XX__,
  __XX____,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0028[ 18] = { /* code 0028, LEFT PARENTHESIS */
  ___XX___,
  __XX____,
  __XX____,
  _XXX____,
  _XX_____,
  _XX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  _XX_____,
  _XX_____,
  _XXX____,
  __XX____,
  __XX____,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0029[ 18] = { /* code 0029, RIGHT PARENTHESIS */
  XX______,
  _XX_____,
  _XX_____,
  _XXX____,
  __XX____,
  __XX____,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XX____,
  __XX____,
  _XXX____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_002D[  2] = { /* code 002D, HYPHEN-MINUS */
  XXXXX___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_002E[  3] = { /* code 002E, FULL STOP */
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_002F[ 14] = { /* code 002F, SOLIDUS */
  ____XXX_,
  ____XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0030[ 28] = { /* code 0030, DIGIT ZERO */
  __XXXXX_,________,
  _XXX__XX,________,
  _XX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX___XX,________,
  _XX__XXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0031[ 14] = { /* code 0031, DIGIT ONE */
  ____XX__,
  ___XXX__,
  ___XXX__,
  XXXXXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0032[ 28] = { /* code 0032, DIGIT TWO */
  __XXXXX_,________,
  _XX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  ____XXXX,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXX____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0033[ 28] = { /* code 0033, DIGIT THREE */
  __XXXXX_,________,
  _XX___XX,X_______,
  XXX___XX,X_______,
  ______XX,X_______,
  ______XX,________,
  _____XX_,________,
  ___XXXXX,________,
  _____XXX,________,
  ______XX,X_______,
  ______XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0034[ 28] = { /* code 0034, DIGIT FOUR */
  _____XXX,________,
  ____XXXX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  __XXXXXX,________,
  __XX_XXX,________,
  _XX__XXX,________,
  _XX__XXX,________,
  XX___XXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0035[ 28] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,________,
  _XXXXXXX,________,
  _XX_____,________,
  _XX_____,________,
  _XX__XX_,________,
  _XXXXXXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  XXX___XX,X_______,
  XXX__XXX,________,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0036[ 28] = { /* code 0036, DIGIT SIX */
  ___XXXX_,________,
  _XXX__XX,________,
  _XX___XX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX_XXX_,________,
  XXXXXXXX,________,
  XXXX__XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX___XX,X_______,
  _XXX__XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0037[ 14] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,
  XXXXXXXX,
  _____XXX,
  _____XX_,
  ____XXX_,
  ____XX__,
  ___XXX__,
  ___XX___,
  ___XX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XX____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0038[ 28] = { /* code 0038, DIGIT EIGHT */
  __XXXXX_,________,
  _XX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX___XX,________,
  __XXXXX_,________,
  _XX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0039[ 28] = { /* code 0039, DIGIT NINE */
  __XXXXX_,________,
  _XX__XXX,________,
  XXX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX__XXX,X_______,
  _XXXXXXX,X_______,
  __XXX_XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  XXX___XX,________,
  _XX__XXX,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_003A[ 10] = { /* code 003A, COLON */
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0040[ 28] = { /* code 0040, COMMERCIAL AT */
  _____XXX,XX______,
  ___XX___,_XXX____,
  __XX____,___XX___,
  _XX__XXX,_XXXX___,
  _X__XXXX,XXX_XX__,
  XX__XX__,XXX_XX__,
  XX_XX___,XX__XX__,
  XX_XX___,XX__X___,
  XX_XX___,XX_XX___,
  _XXXXXXX,XXXX____,
  _XX_XXX_,XXX_____,
  __XX____,___XX___,
  ___XX___,_XXX____,
  _____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0041[ 28] = { /* code 0041, LATIN CAPITAL LETTER A */
  ____XXX_,________,
  ___XXXXX,________,
  ___XX_XX,________,
  ___XX_XX,________,
  ___XX_XX,________,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  __XX___X,X_______,
  __XX___X,X_______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXX___X,XX______,
  XXX_____,XXX_____,
  XXX_____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0042[ 28] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,________,
  XXXXXXX_,________,
  XXXXXXXX,________,
  XXX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0043[ 28] = { /* code 0043, LATIN CAPITAL LETTER C */
  ___XXXX_,________,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXX__XX,________,
  _XXXXXXX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0044[ 28] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XXX__XXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX__XXX,________,
  XXXXXXXX,________,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0045[ 14] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,
  XXXXXXXX,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXXXXXXX,
  XXXXXXXX,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0046[ 14] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,
  XXXXXXXX,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXXXXXXX,
  XXXXXXXX,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0047[ 28] = { /* code 0047, LATIN CAPITAL LETTER G */
  __XXXXX_,________,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  _XX___XX,X_______,
  XXX___XX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX__XXX,X_______,
  XXX__XXX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0048[ 28] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0049[ 14] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_004A[ 14] = { /* code 004A, LATIN CAPITAL LETTER J */
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  _____XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  _XXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_004B[ 28] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX__XXX,________,
  XXX_XXX_,________,
  XXX_XXX_,________,
  XXXXXX__,________,
  XXXXXX__,________,
  XXXXXXX_,________,
  XXXXXXX_,________,
  XXX__XXX,________,
  XXX__XXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_004C[ 14] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_004D[ 28] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXXXX___,XXXXX___,
  XXXXX___,XXXXX___,
  XXXXX___,XXXXX___,
  XXXXX___,XXXXX___,
  XXXXX___,XXXXX___,
  XXXXXX_X,XXXXX___,
  XXX_XX_X,X_XXX___,
  XXX_XX_X,X_XXX___,
  XXX_XX_X,X_XXX___,
  XXX_XX_X,X_XXX___,
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_004E[ 28] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXXX__XX,X_______,
  XXXX__XX,X_______,
  XXXX__XX,X_______,
  XXXX__XX,X_______,
  XXXXX_XX,X_______,
  XXXXX_XX,X_______,
  XXX_X_XX,X_______,
  XXX_XXXX,X_______,
  XXX_XXXX,X_______,
  XXX_XXXX,X_______,
  XXX__XXX,X_______,
  XXX__XXX,X_______,
  XXX__XXX,X_______,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_004F[ 28] = { /* code 004F, LATIN CAPITAL LETTER O */
  __XXXX__,________,
  _XXXXXXX,________,
  _XXX_XXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXX_XXX,________,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0050[ 28] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XXXXXXX_,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0051[ 30] = { /* code 0051, LATIN CAPITAL LETTER Q */
  __XXXX__,________,
  _XXXXXXX,________,
  _XXX_XXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXX_XXX,________,
  _XXXXXXX,________,
  __XXXXXX,X_______,
  _______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0052[ 28] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,________,
  XXXXXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0053[ 28] = { /* code 0053, LATIN CAPITAL LETTER S */
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX____,________,
  _XXXXX__,________,
  __XXXXXX,________,
  ___XXXXX,X_______,
  ______XX,XX______,
  _______X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0054[ 28] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0055[ 28] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0056[ 28] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXX____X,XX______,
  XXX____X,XX______,
  _XX____X,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XX__XX,________,
  __XX__XX,________,
  __XXXXXX,________,
  __XXXXXX,________,
  __XXXXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0057[ 28] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXX___XX,___XXX__,
  XXX___XX,___XXX__,
  XXX__XXX,X__XXX__,
  _XX__XXX,X__XX___,
  _XX__XXX,X__XX___,
  _XX__XXX,X__XX___,
  _XX__XXX,X__XX___,
  _XXX_X__,X_XXX___,
  __XX_X__,X_XX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0058[ 28] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXX____X,XX______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,________,
  __XXXXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXXXX,________,
  __XX_XXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  XXX____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0059[ 28] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX___XX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  __XXXXX_,________,
  __XXXXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_005A[ 14] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXXXX,
  XXXXXXXX,
  _____XXX,
  ____XXX_,
  ____XXX_,
  ___XXX__,
  ___XXX__,
  __XXX___,
  __XXX___,
  _XXX____,
  _XXX____,
  XXX_____,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_005C[ 14] = { /* code 005C, REVERSE SOLIDUS */
  XXX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ___XX___,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0061[ 20] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXXXX,________,
  _XX___XX,X_______,
  ______XX,X_______,
  ___XXXXX,X_______,
  _XXXXXXX,X_______,
  _XXX__XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0062[ 14] = { /* code 0062, LATIN SMALL LETTER B */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_XX__,
  XXXXXXX_,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XX_,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0063[ 20] = { /* code 0063, LATIN SMALL LETTER C */
  ___XXXX_,________,
  _XXXXXXX,________,
  _XX___XX,X_______,
  XXX___XX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX___XX,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0064[ 28] = { /* code 0064, LATIN SMALL LETTER D */
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  __XXX_XX,X_______,
  _XXXXXXX,X_______,
  _XX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX__XXX,X_______,
  __XXX_XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0065[ 20] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXXX_,________,
  _XX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXXXXXX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX___XX,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0066[ 14] = { /* code 0066, LATIN SMALL LETTER F */
  __XXX___,
  _XXXX___,
  _XXX____,
  _XXX____,
  XXXXX___,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0067[ 14] = { /* code 0067, LATIN SMALL LETTER G */
  __XXXXXX,
  _XX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  _XXXXXXX,
  __XX_XXX,
  _____XXX,
  XXX__XXX,
  XXX__XX_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0068[ 14] = { /* code 0068, LATIN SMALL LETTER H */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_XX__,
  XXXXXXXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0069[ 14] = { /* code 0069, LATIN SMALL LETTER I */
  XXX_____,
  XXX_____,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_006A[ 18] = { /* code 006A, LATIN SMALL LETTER J */
  _XXX____,
  _XXX____,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_006B[ 28] = { /* code 006B, LATIN SMALL LETTER K */
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX__XXX,X_______,
  XXX__XX_,________,
  XXX_XXX_,________,
  XXXXXX__,________,
  XXXXXX__,________,
  XXXXXX__,________,
  XXX_XXX_,________,
  XXX__XXX,________,
  XXX__XXX,________,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_006C[ 14] = { /* code 006C, LATIN SMALL LETTER L */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_006D[ 20] = { /* code 006D, LATIN SMALL LETTER M */
  XXX_XXX_,_XXX____,
  XXXXXXXX,XXXX____,
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_006E[ 10] = { /* code 006E, LATIN SMALL LETTER N */
  XXXXXXX_,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_006F[ 20] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXX_,________,
  _XX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX___XX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0070[ 14] = { /* code 0070, LATIN SMALL LETTER P */
  XXXXXX__,
  XXX__XX_,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XX_,
  XXXXXXX_,
  XXX_XX__,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0071[ 28] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXX_XX,X_______,
  _XX__XXX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXX_XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0072[ 10] = { /* code 0072, LATIN SMALL LETTER R */
  XXX_XX__,
  XXXXXX__,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0073[ 10] = { /* code 0073, LATIN SMALL LETTER S */
  __XXXXX_,
  XXX___XX,
  XXX___XX,
  XXXX____,
  _XXXXX__,
  __XXXXX_,
  _____XXX,
  _XX__XXX,
  _XX__XXX,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0074[ 13] = { /* code 0074, LATIN SMALL LETTER T */
  _XXX____,
  _XXX____,
  _XXX____,
  XXXXX___,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXXX___,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0075[ 10] = { /* code 0075, LATIN SMALL LETTER U */
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  XXX__XXX,
  _XXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0076[ 10] = { /* code 0076, LATIN SMALL LETTER V */
  XXX__XXX,
  XXX__XXX,
  _XX__XX_,
  _XX__XX_,
  _XXX_XX_,
  _XXXXXX_,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0077[ 20] = { /* code 0077, LATIN SMALL LETTER W */
  XXX__XXX,__XXX___,
  XXX__XXX,__XXX___,
  _XX__XXX,__XX____,
  _XX_XX_X,X_XX____,
  _XX_XX_X,X_XX____,
  _XXXXX_X,X_XX____,
  _XXXXX_X,XXXX____,
  __XXXX_X,XXX_____,
  __XXX___,XXX_____,
  __XXX___,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0078[ 20] = { /* code 0078, LATIN SMALL LETTER X */
  XXX___XX,X_______,
  _XXX_XXX,________,
  __XX_XX_,________,
  __XXXXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXXXX_,________,
  __XX_XX_,________,
  _XXX_XXX,________,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_0079[ 14] = { /* code 0079, LATIN SMALL LETTER Y */
  XXX__XXX,
  XXX__XXX,
  _XX__XX_,
  _XX__XX_,
  _XXX_XX_,
  _XXXXXX_,
  __XXXX__,
  __XXXX__,
  __XXXX__,
  ___XXX__,
  ___XX___,
  ___XX___,
  _XXXX___,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_007A[ 10] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXX_,
  XXXXXXX_,
  ____XXX_,
  ___XXX__,
  __XXX___,
  __XXX___,
  _XXX____,
  XXX_____,
  XXXXXXX_,
  XXXXXXX_};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn23_00B0[  6] = { /* code 00B0, DEGREE SIGN */
  _XXXX___,
  XX__XX__,
  X____X__,
  X____X__,
  XX__XX__,
  _XXXX___};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHelveticaNeueLTStdCn23_CharInfo[76] = {
   {   1,   1,   0,  19,  5, acGUI_FontHelveticaNeueLTStdCn23_0020 } /* code 0020, SPACE */
  ,{   3,  14,   1,   5,   6, acGUI_FontHelveticaNeueLTStdCn23_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   5,   6,   2,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0022 } /* code 0022, QUOTATION MARK */
  ,{  14,  14,   1,   5,  15, acGUI_FontHelveticaNeueLTStdCn23_0025 } /* code 0025, PERCENT SIGN */
  ,{   5,  18,   0,   3,   6, acGUI_FontHelveticaNeueLTStdCn23_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   5,  18,   1,   3,   6, acGUI_FontHelveticaNeueLTStdCn23_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   5,   2,   1,  12,   7, acGUI_FontHelveticaNeueLTStdCn23_002D } /* code 002D, HYPHEN-MINUS */
  ,{   3,   3,   1,  16,   5, acGUI_FontHelveticaNeueLTStdCn23_002E } /* code 002E, FULL STOP */
  ,{   7,  14,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn23_002F } /* code 002F, SOLIDUS */
  ,{   9,  14,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0030 } /* code 0030, DIGIT ZERO */
  ,{   6,  14,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0031 } /* code 0031, DIGIT ONE */
  ,{   9,  14,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0032 } /* code 0032, DIGIT TWO */
  ,{   9,  14,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0033 } /* code 0033, DIGIT THREE */
  ,{   9,  14,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0034 } /* code 0034, DIGIT FOUR */
  ,{   9,  14,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0035 } /* code 0035, DIGIT FIVE */
  ,{   9,  14,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0036 } /* code 0036, DIGIT SIX */
  ,{   8,  14,   1,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0037 } /* code 0037, DIGIT SEVEN */
  ,{   9,  14,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0038 } /* code 0038, DIGIT EIGHT */
  ,{   9,  14,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0039 } /* code 0039, DIGIT NINE */
  ,{   3,  10,   1,   9,   5, acGUI_FontHelveticaNeueLTStdCn23_003A } /* code 003A, COLON */
  ,{  14,  14,   1,   5,  15, acGUI_FontHelveticaNeueLTStdCn23_0040 } /* code 0040, COMMERCIAL AT */
  ,{  11,  14,   0,   5,  11, acGUI_FontHelveticaNeueLTStdCn23_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   9,  14,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn23_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   9,  14,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   9,  14,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn23_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   8,  14,   1,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   8,  14,   1,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   9,  14,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn23_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   9,  14,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn23_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   3,  14,   1,   5,   5, acGUI_FontHelveticaNeueLTStdCn23_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   8,  14,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  10,  14,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   8,  14,   1,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  13,  14,   1,   5,  14, acGUI_FontHelveticaNeueLTStdCn23_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   9,  14,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn23_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   9,  14,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn23_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   9,  14,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   9,  15,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn23_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  10,  14,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn23_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  10,  14,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   9,  14,   0,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   9,  14,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  10,  14,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  14,  14,   0,   5,  14, acGUI_FontHelveticaNeueLTStdCn23_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  10,  14,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   9,  14,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   8,  14,   1,   5,   9, acGUI_FontHelveticaNeueLTStdCn23_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   7,  14,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn23_005C } /* code 005C, REVERSE SOLIDUS */
  ,{  10,   1,   0,  20,  10, acGUI_FontHelveticaNeueLTStdCn23_005F } /* code 005F, LOW LINE */
  ,{   9,  10,   0,   9,   9, acGUI_FontHelveticaNeueLTStdCn23_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   8,  14,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   9,  10,   0,   9,   9, acGUI_FontHelveticaNeueLTStdCn23_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   9,  14,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   9,  10,   0,   9,   9, acGUI_FontHelveticaNeueLTStdCn23_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   5,  14,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn23_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   8,  14,   1,   9,  10, acGUI_FontHelveticaNeueLTStdCn23_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   8,  14,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   3,  14,   1,   5,   5, acGUI_FontHelveticaNeueLTStdCn23_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   4,  18,   0,   5,   5, acGUI_FontHelveticaNeueLTStdCn23_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   9,  14,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn23_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   3,  14,   1,   5,   5, acGUI_FontHelveticaNeueLTStdCn23_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  13,  10,   1,   9,  14, acGUI_FontHelveticaNeueLTStdCn23_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   8,  10,   1,   9,  10, acGUI_FontHelveticaNeueLTStdCn23_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   9,  10,   0,   9,   9, acGUI_FontHelveticaNeueLTStdCn23_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   8,  14,   1,   9,  10, acGUI_FontHelveticaNeueLTStdCn23_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   9,  14,   0,   9,  10, acGUI_FontHelveticaNeueLTStdCn23_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   6,  10,   1,   9,   6, acGUI_FontHelveticaNeueLTStdCn23_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   8,  10,   0,   9,   8, acGUI_FontHelveticaNeueLTStdCn23_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   5,  13,   0,   6,   6, acGUI_FontHelveticaNeueLTStdCn23_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   8,  10,   1,   9,  10, acGUI_FontHelveticaNeueLTStdCn23_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   8,  10,   0,   9,   8, acGUI_FontHelveticaNeueLTStdCn23_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  13,  10,   0,   9,  13, acGUI_FontHelveticaNeueLTStdCn23_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   9,  10,   0,   9,   9, acGUI_FontHelveticaNeueLTStdCn23_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   8,  14,   0,   9,   8, acGUI_FontHelveticaNeueLTStdCn23_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   7,  10,   1,   9,   8, acGUI_FontHelveticaNeueLTStdCn23_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   6,   6,   1,   5,   8, acGUI_FontHelveticaNeueLTStdCn23_00B0 } /* code 00B0, DEGREE SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn23_Prop9 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn23_CharInfo[ 75] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn23_Prop8 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn23_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn23_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn23_Prop7 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn23_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn23_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn23_Prop6 = {
   0x005C /* first character */
  ,0x005C /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn23_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn23_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn23_Prop5 = {
   0x0040 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn23_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn23_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn23_Prop4 = {
   0x002D /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn23_CharInfo[  6] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn23_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn23_Prop3 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn23_CharInfo[  4] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn23_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn23_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn23_CharInfo[  3] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn23_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn23_Prop1 = {
   0x0020 /* first character */
  ,0x0022 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn23_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn23_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn23 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,23 /* height of font  */
  ,23 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTStdCn23_Prop1}
  ,19 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

