/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Std Cn28.c                            *
* Font:        HelveticaNeueLT Std Cn                                *
* Height:      28                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 28                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\WB\MDK5\fonts_all.txt                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn28;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0021[ 17] = { /* code 0021, EXCLAMATION MARK */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0022[  8] = { /* code 0022, QUOTATION MARK */
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0025[ 34] = { /* code 0025, PERCENT SIGN */
  _XXXX___,___XXX__,
  _XXXX___,___XX___,
  XX__XX__,__XX____,
  XX__XX__,__XX____,
  XX__XX__,_XX_____,
  XX__XX__,_XX_____,
  XX__XX__,XX______,
  _XXXX___,XX______,
  _XXXX__X,X__XXXX_,
  ______XX,X__XXXX_,
  ______XX,__XX__XX,
  _____XX_,__XX__XX,
  _____XX_,__XX__XX,
  ____XX__,__XX__XX,
  ____XX__,__XX__XX,
  ___XX___,___XXXX_,
  __XXX___,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0028[ 22] = { /* code 0028, LEFT PARENTHESIS */
  ___XXX__,
  __XXX___,
  __XX____,
  __XX____,
  _XXX____,
  _XXX____,
  _XX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  _XX_____,
  _XXX____,
  _XXX____,
  __XX____,
  __XX____,
  __XXX___,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0029[ 22] = { /* code 0029, RIGHT PARENTHESIS */
  XXX_____,
  _XXX____,
  _XXX____,
  __XX____,
  __XXX___,
  __XXX___,
  ___XX___,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XX___,
  __XXX___,
  __XXX___,
  __XX____,
  __XX____,
  _XXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_002D[  3] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXX_,
  XXXXXXX_,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_002E[  4] = { /* code 002E, FULL STOP */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_002F[ 17] = { /* code 002F, SOLIDUS */
  _____XXX,
  _____XX_,
  _____XX_,
  ____XXX_,
  ____XXX_,
  ____XX__,
  ___XXX__,
  ___XXX__,
  ___XX___,
  __XXX___,
  __XXX___,
  __XX____,
  _XXX____,
  _XXX____,
  _XX_____,
  _XX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0030[ 34] = { /* code 0030, DIGIT ZERO */
  ___XXXX_,________,
  __XXXXXX,X_______,
  _XXX__XX,X_______,
  _XX____X,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XX____X,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0031[ 17] = { /* code 0031, DIGIT ONE */
  ____XX__,
  ___XXX__,
  __XXXX__,
  XXXXXX__,
  XXXXXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0032[ 34] = { /* code 0032, DIGIT TWO */
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  ____XXXX,________,
  ___XXXX_,________,
  __XXXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXX____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0033[ 34] = { /* code 0033, DIGIT THREE */
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  ___XXXXX,________,
  ___XXXXX,X_______,
  ______XX,X_______,
  _______X,XX______,
  _______X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0034[ 34] = { /* code 0034, DIGIT FOUR */
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  __XXXXXX,________,
  __XX_XXX,________,
  __XX_XXX,________,
  _XX__XXX,________,
  _XX__XXX,________,
  XX___XXX,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0035[ 34] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _XX_____,________,
  _XX_____,________,
  _XX__XX_,________,
  XXX_XXXX,X_______,
  XXXXXXXX,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  _______X,XX______,
  _______X,XX______,
  XXX____X,XX______,
  XXX___XX,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0036[ 34] = { /* code 0036, DIGIT SIX */
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XX___XX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX__XXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXX__XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXX___X,X_______,
  _XXXXXXX,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0037[ 34] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  ____XXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXX___,________,
  __XXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0038[ 34] = { /* code 0038, DIGIT EIGHT */
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  _XXXXXXX,X_______,
  _XXX__XX,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0039[ 34] = { /* code 0039, DIGIT NINE */
  ___XXX__,________,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  XXX____X,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXXX__XX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  __XXX__X,XX______,
  _______X,XX______,
  XXX____X,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_003A[ 12] = { /* code 003A, COLON */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0040[ 51] = { /* code 0040, COMMERCIAL AT */
  _______X,XXX_____,________,
  ____XXXX,XXXXX___,________,
  ___XXX__,___XXXX_,________,
  __XXX___,_____XXX,________,
  _XXX___X,XX___XXX,________,
  _XX___XX,XXXXX__X,X_______,
  _X___XXX,XXXXX__X,X_______,
  XX__XXX_,__XXX__X,X_______,
  XX__XX__,__XXX__X,X_______,
  XX__XX__,__XX___X,________,
  XX__XX__,_XXX__XX,________,
  _XX_XXXX,XXXXXXX_,________,
  _XXX_XXX,XXXXXX__,________,
  __XXX_XX,__XXX__X,________,
  ___XXX__,____XXX_,________,
  ____XXXX,XXXXXX__,________,
  _______X,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0041[ 34] = { /* code 0041, LATIN CAPITAL LETTER A */
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XX_X,X_______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  __XXX___,XXX_____,
  __XXX___,XXX_____,
  __XXX___,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXX____,_XXX____,
  XXXX____,_XXXX___,
  XXXX____,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0042[ 34] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,XX______,
  XXX___XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX___XX,XX______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,XX______,
  XXX____X,XX______,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX____X,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0043[ 34] = { /* code 0043, LATIN CAPITAL LETTER C */
  ____XXXX,________,
  __XXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXX___X,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  _XXX___X,XX______,
  _XXXXXXX,XX______,
  __XXXXXX,X_______,
  ____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0044[ 34] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXX__,________,
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX___XX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,________,
  XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0045[ 34] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0046[ 34] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0047[ 34] = { /* code 0047, LATIN CAPITAL LETTER G */
  ____XXXX,________,
  __XXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXX___X,XXX_____,
  XXX_____,XXX_____,
  XXX_____,________,
  XXX_____,________,
  XXX___XX,XXX_____,
  XXX___XX,XXX_____,
  XXX___XX,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXXX____,XXX_____,
  _XXX___X,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXXXX,_XX_____,
  ___XXXX_,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0048[ 34] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0049[ 17] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_004A[ 34] = { /* code 004A, LATIN CAPITAL LETTER J */
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_004B[ 34] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXX____X,XXX_____,
  XXX___XX,XX______,
  XXX___XX,X_______,
  XXX__XXX,X_______,
  XXX_XXXX,________,
  XXX_XXXX,________,
  XXXXXXX_,________,
  XXXXXX__,________,
  XXXXXXX_,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXX__XXX,X_______,
  XXX__XXX,X_______,
  XXX___XX,XX______,
  XXX___XX,XX______,
  XXX____X,XXX_____,
  XXX____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_004C[ 34] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_004D[ 34] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXXXX___,__XXXXX_,
  XXXXX___,__XXXXX_,
  XXXXX___,__XXXXX_,
  XXXXXX__,_XXXXXX_,
  XXXXXX__,_XXXXXX_,
  XXXXXX__,_XXXXXX_,
  XXX_XX__,_XX_XXX_,
  XXX_XXX_,_XX_XXX_,
  XXX_XXX_,XXX_XXX_,
  XXX_XXX_,XXX_XXX_,
  XXX__XX_,XX__XXX_,
  XXX__XX_,XX__XXX_,
  XXX__XXX,XX__XXX_,
  XXX__XXX,XX__XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_004E[ 34] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXXX____,XXX_____,
  XXXX____,XXX_____,
  XXXXX___,XXX_____,
  XXXXX___,XXX_____,
  XXXXX___,XXX_____,
  XXXXXX__,XXX_____,
  XXXXXX__,XXX_____,
  XXX_XX__,XXX_____,
  XXX_XXX_,XXX_____,
  XXX__XX_,XXX_____,
  XXX__XXX,XXX_____,
  XXX__XXX,XXX_____,
  XXX___XX,XXX_____,
  XXX___XX,XXX_____,
  XXX___XX,XXX_____,
  XXX____X,XXX_____,
  XXX____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_004F[ 34] = { /* code 004F, LATIN CAPITAL LETTER O */
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXX___X,XX______,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  _XXX___X,XX______,
  _XXXXXXX,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0050[ 34] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXXX,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXX____X,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX____X,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0051[ 38] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXX___X,XX______,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  _XXX___X,XX______,
  _XXXXXXX,XX______,
  __XXXXXX,XX______,
  ___XXXXX,XXX_____,
  ________,XXX_____,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0052[ 34] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXXX,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XXX_____,
  XXX____X,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX____X,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______,
  XXXXXXXX,XX______,
  XXX____X,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0053[ 34] = { /* code 0053, LATIN CAPITAL LETTER S */
  ___XXXX_,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX_____,________,
  XXXX____,________,
  _XXXXXX_,________,
  __XXXXXX,X_______,
  ____XXXX,X_______,
  ______XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0054[ 34] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0055[ 34] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  XXXX___X,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0056[ 34] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXXX____,XXXX____,
  XXXX____,XXXX____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXXX__X,XXX_____,
  __XXX__X,XX______,
  __XXX__X,XX______,
  __XXX__X,XX______,
  __XXX__X,XX______,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ____XXXX,________,
  ____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0057[ 51] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXXX___X,XXX___XX,XX______,
  XXXX___X,XXX___XX,XX______,
  _XXX___X,XXX___XX,X_______,
  _XXX___X,XXX___XX,X_______,
  _XXX___X,XXX___XX,X_______,
  _XXX___X,XXX___XX,X_______,
  _XXX__XX,XXXX__XX,X_______,
  __XXX_XX,XXXX_XXX,________,
  __XXX_XX,__XX_XXX,________,
  __XXX_XX,__XX_XXX,________,
  __XXX_XX,__XX_XXX,________,
  __XXX_XX,__XX_XXX,________,
  __XXXXXX,__XXXXXX,________,
  ___XXXXX,__XXXXX_,________,
  ___XXXX_,___XXXX_,________,
  ___XXXX_,___XXXX_,________,
  ___XXXX_,___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0058[ 34] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXXX____,XXXX____,
  _XXXX___,XXX_____,
  _XXXX__X,XXX_____,
  __XXX__X,XX______,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  __XXX_XX,XX______,
  __XXX__X,XX______,
  _XXXX__X,XXX_____,
  _XXX____,XXX_____,
  XXXX____,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0059[ 34] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXXX___X,XXX_____,
  XXXX___X,XXX_____,
  _XXX___X,XX______,
  _XXXX__X,XX______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XXXXX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_005A[ 34] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ______XX,X_______,
  _____XXX,X_______,
  _____XXX,________,
  ____XXXX,________,
  ____XXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXX___,________,
  _XXXX___,________,
  _XXX____,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_005C[ 17] = { /* code 005C, REVERSE SOLIDUS */
  XXX_____,
  _XX_____,
  _XX_____,
  _XXX____,
  _XXX____,
  __XX____,
  __XXX___,
  __XXX___,
  ___XX___,
  ___XXX__,
  ___XXX__,
  ____XX__,
  ____XXX_,
  ____XXX_,
  _____XX_,
  _____XX_,
  _____XXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0061[ 26] = { /* code 0061, LATIN SMALL LETTER A */
  ___XXXX_,________,
  __XXXXXX,________,
  _XX___XX,X_______,
  _XX___XX,X_______,
  ______XX,X_______,
  ___XXXXX,X_______,
  _XXXXXXX,X_______,
  XXXX__XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX__XXX,X_______,
  _XXXXXXX,X_______,
  _XXXX_XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0062[ 34] = { /* code 0062, LATIN SMALL LETTER B */
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX__XXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXX__XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXXX__XX,X_______,
  XXXXXXXX,X_______,
  XXX__XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0063[ 26] = { /* code 0063, LATIN SMALL LETTER C */
  ___XXX__,________,
  __XXXXXX,________,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  XXX___XX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0064[ 34] = { /* code 0064, LATIN SMALL LETTER D */
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  __XXX__X,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  XXXX__XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXX__XX,XX______,
  _XXXXXXX,XX______,
  __XXX__X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0065[ 26] = { /* code 0065, LATIN SMALL LETTER E */
  ___XXXX_,________,
  _XXXXXXX,________,
  _XX___XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXX_____,________,
  XXX_____,________,
  XXX___XX,X_______,
  _XX___XX,________,
  _XXXXXXX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0066[ 17] = { /* code 0066, LATIN SMALL LETTER F */
  ____XXX_,
  __XXXXX_,
  __XXXXX_,
  __XXX___,
  XXXXXXX_,
  XXXXXXX_,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0067[ 36] = { /* code 0067, LATIN SMALL LETTER G */
  ___XX__X,XX______,
  _XXXXX_X,XX______,
  _XXX__XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXXX__XX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  __XXX__X,XX______,
  _______X,XX______,
  XXX____X,XX______,
  XXX___XX,X_______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0068[ 34] = { /* code 0068, LATIN SMALL LETTER H */
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX__XXX,________,
  XXX_XXXX,X_______,
  XXXXXXXX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0069[ 17] = { /* code 0069, LATIN SMALL LETTER I */
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_006A[ 22] = { /* code 006A, LATIN SMALL LETTER J */
  __XXX___,
  __XXX___,
  __XXX___,
  ________,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  XXXXX___,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_006B[ 34] = { /* code 006B, LATIN SMALL LETTER K */
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX___XX,XX______,
  XXX__XXX,X_______,
  XXX__XXX,________,
  XXX_XXX_,________,
  XXXXXXX_,________,
  XXXXXX__,________,
  XXXXXXX_,________,
  XXXXXXX_,________,
  XXX__XXX,________,
  XXX__XXX,X_______,
  XXX___XX,X_______,
  XXX___XX,XX______,
  XXX____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_006C[ 17] = { /* code 006C, LATIN SMALL LETTER L */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_006D[ 26] = { /* code 006D, LATIN SMALL LETTER M */
  XXX__XX_,___XX___,
  XXXXXXXX,_XXXXX__,
  XXXXXXXX,XXXXXXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_006E[ 26] = { /* code 006E, LATIN SMALL LETTER N */
  XXX__XXX,________,
  XXX_XXXX,XX______,
  XXXX___X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_006F[ 26] = { /* code 006F, LATIN SMALL LETTER O */
  ___XXXX_,________,
  _XXXXXXX,X_______,
  _XXX__XX,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0070[ 36] = { /* code 0070, LATIN SMALL LETTER P */
  XXX__XXX,________,
  XXXXXXXX,X_______,
  XXXX__XX,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXXX__XX,XX______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXX__XXX,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0071[ 36] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXX__X,XX______,
  _XXXXXXX,XX______,
  _XXX__XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXXX__XX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  __XXX__X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0072[ 13] = { /* code 0072, LATIN SMALL LETTER R */
  XXX__X__,
  XXXXXX__,
  XXXXXX__,
  XXXX____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0073[ 26] = { /* code 0073, LATIN SMALL LETTER S */
  __XXXX__,________,
  _XXXXXXX,________,
  XXX___XX,________,
  XXX___XX,________,
  XXXX____,________,
  _XXXXX__,________,
  __XXXXXX,________,
  ___XXXXX,________,
  _____XXX,X_______,
  XX____XX,X_______,
  XX____XX,X_______,
  _XXXXXXX,________,
  __XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  __XXX___,
  __XXX___,
  __XXX___,
  XXXXXXX_,
  XXXXXXX_,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXXXX_,
  __XXXXX_,
  ___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0075[ 26] = { /* code 0075, LATIN SMALL LETTER U */
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX___XX,XX______,
  XXXXXX_X,XX______,
  __XXX__X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0076[ 26] = { /* code 0076, LATIN SMALL LETTER V */
  XXX____X,XX______,
  XXXX___X,XX______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXX_XX,________,
  __XXXXXX,________,
  __XXXXXX,________,
  __XXXXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0077[ 26] = { /* code 0077, LATIN SMALL LETTER W */
  XXX___XX,XX___XXX,
  XXX___XX,XX___XXX,
  _XXX__XX,XX___XX_,
  _XXX__XX,XX__XXX_,
  _XXX__XX,XXX_XXX_,
  _XXX_XXX,XXX_XXX_,
  _XXX_XXX,_XX_XXX_,
  __XX_XX_,_XX_XX__,
  __XXXXX_,_XX_XX__,
  __XXXXX_,_XXXXX__,
  __XXXXX_,_XXXXX__,
  __XXXXX_,_XXXXX__,
  ___XXXX_,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0078[ 26] = { /* code 0078, LATIN SMALL LETTER X */
  XXXX___X,XXX_____,
  _XXX___X,XX______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XXXXX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  __XXX_XX,X_______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_0079[ 36] = { /* code 0079, LATIN SMALL LETTER Y */
  XXX____X,XX______,
  XXXX___X,XX______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXX_XX,________,
  __XXX_XX,________,
  __XXXXXX,________,
  ___XXXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_007A[ 26] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _____XXX,________,
  ____XXXX,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  _XXXX___,________,
  _XXX____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn28_00B0[  7] = { /* code 00B0, DEGREE SIGN */
  __XXX___,
  _XXXXX__,
  XX___XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  __XXX___};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHelveticaNeueLTStdCn28_CharInfo[76] = {
   {   1,   1,   0,  23,  6, acGUI_FontHelveticaNeueLTStdCn28_0020 } /* code 0020, SPACE */
  ,{   3,  17,   2,   6,   7, acGUI_FontHelveticaNeueLTStdCn28_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   7,   8,   2,   6,  11, acGUI_FontHelveticaNeueLTStdCn28_0022 } /* code 0022, QUOTATION MARK */
  ,{  16,  17,   1,   6,  19, acGUI_FontHelveticaNeueLTStdCn28_0025 } /* code 0025, PERCENT SIGN */
  ,{   6,  22,   1,   6,   7, acGUI_FontHelveticaNeueLTStdCn28_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   6,  22,   0,   6,   7, acGUI_FontHelveticaNeueLTStdCn28_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   7,   3,   1,  15,   9, acGUI_FontHelveticaNeueLTStdCn28_002D } /* code 002D, HYPHEN-MINUS */
  ,{   3,   4,   1,  19,   6, acGUI_FontHelveticaNeueLTStdCn28_002E } /* code 002E, FULL STOP */
  ,{   8,  17,   0,   6,   8, acGUI_FontHelveticaNeueLTStdCn28_002F } /* code 002F, SOLIDUS */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0030 } /* code 0030, DIGIT ZERO */
  ,{   6,  17,   2,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0031 } /* code 0031, DIGIT ONE */
  ,{   9,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0032 } /* code 0032, DIGIT TWO */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0034 } /* code 0034, DIGIT FOUR */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0035 } /* code 0035, DIGIT FIVE */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0036 } /* code 0036, DIGIT SIX */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0037 } /* code 0037, DIGIT SEVEN */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0038 } /* code 0038, DIGIT EIGHT */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0039 } /* code 0039, DIGIT NINE */
  ,{   3,  12,   1,  11,   6, acGUI_FontHelveticaNeueLTStdCn28_003A } /* code 003A, COLON */
  ,{  17,  17,   1,   6,  19, acGUI_FontHelveticaNeueLTStdCn28_0040 } /* code 0040, COMMERCIAL AT */
  ,{  13,  17,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn28_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  11,  17,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn28_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  11,  17,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn28_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  10,  17,   2,   6,  14, acGUI_FontHelveticaNeueLTStdCn28_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   9,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   9,  17,   1,   6,  11, acGUI_FontHelveticaNeueLTStdCn28_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  11,  17,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn28_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  11,  17,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn28_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   3,  17,   2,   6,   6, acGUI_FontHelveticaNeueLTStdCn28_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  10,  17,   0,   6,  11, acGUI_FontHelveticaNeueLTStdCn28_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  11,  17,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn28_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   9,  17,   1,   6,  11, acGUI_FontHelveticaNeueLTStdCn28_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  15,  17,   1,   6,  18, acGUI_FontHelveticaNeueLTStdCn28_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  11,  17,   1,   6,  14, acGUI_FontHelveticaNeueLTStdCn28_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  11,  17,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn28_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  11,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  11,  19,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn28_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  12,  17,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn28_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  11,  17,   0,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  11,  17,   1,   6,  13, acGUI_FontHelveticaNeueLTStdCn28_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  12,  17,   0,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  18,  17,   0,   6,  18, acGUI_FontHelveticaNeueLTStdCn28_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  12,  17,   0,   6,  13, acGUI_FontHelveticaNeueLTStdCn28_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  11,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   8,  17,   0,   6,   8, acGUI_FontHelveticaNeueLTStdCn28_005C } /* code 005C, REVERSE SOLIDUS */
  ,{  12,   1,   0,  25,  12, acGUI_FontHelveticaNeueLTStdCn28_005F } /* code 005F, LOW LINE */
  ,{   9,  13,   1,  10,  12, acGUI_FontHelveticaNeueLTStdCn28_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   9,  13,   1,  10,  11, acGUI_FontHelveticaNeueLTStdCn28_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   9,  13,   1,  10,  11, acGUI_FontHelveticaNeueLTStdCn28_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   7,  17,   0,   6,   7, acGUI_FontHelveticaNeueLTStdCn28_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{  10,  18,   1,  10,  12, acGUI_FontHelveticaNeueLTStdCn28_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   3,  17,   1,   6,   6, acGUI_FontHelveticaNeueLTStdCn28_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   5,  22,  -1,   6,   6, acGUI_FontHelveticaNeueLTStdCn28_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  10,  17,   1,   6,  12, acGUI_FontHelveticaNeueLTStdCn28_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   3,  17,   1,   6,   6, acGUI_FontHelveticaNeueLTStdCn28_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  15,  13,   1,  10,  18, acGUI_FontHelveticaNeueLTStdCn28_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{  10,  13,   1,  10,  12, acGUI_FontHelveticaNeueLTStdCn28_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{  10,  13,   1,  10,  12, acGUI_FontHelveticaNeueLTStdCn28_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{  10,  18,   1,  10,  12, acGUI_FontHelveticaNeueLTStdCn28_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{  10,  18,   1,  10,  12, acGUI_FontHelveticaNeueLTStdCn28_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   6,  13,   1,  10,   8, acGUI_FontHelveticaNeueLTStdCn28_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   9,  13,   1,  10,  11, acGUI_FontHelveticaNeueLTStdCn28_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   7,  16,   0,   7,   7, acGUI_FontHelveticaNeueLTStdCn28_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{  10,  13,   1,  10,  12, acGUI_FontHelveticaNeueLTStdCn28_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  10,  13,   0,  10,  11, acGUI_FontHelveticaNeueLTStdCn28_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  16,  13,   0,  10,  17, acGUI_FontHelveticaNeueLTStdCn28_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{  11,  13,   0,  10,  11, acGUI_FontHelveticaNeueLTStdCn28_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{  10,  18,   0,  10,  11, acGUI_FontHelveticaNeueLTStdCn28_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   9,  13,   1,  10,  10, acGUI_FontHelveticaNeueLTStdCn28_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   7,   7,   1,   6,  10, acGUI_FontHelveticaNeueLTStdCn28_00B0 } /* code 00B0, DEGREE SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn28_Prop9 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn28_CharInfo[ 75] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn28_Prop8 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn28_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn28_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn28_Prop7 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn28_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn28_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn28_Prop6 = {
   0x005C /* first character */
  ,0x005C /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn28_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn28_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn28_Prop5 = {
   0x0040 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn28_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn28_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn28_Prop4 = {
   0x002D /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn28_CharInfo[  6] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn28_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn28_Prop3 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn28_CharInfo[  4] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn28_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn28_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn28_CharInfo[  3] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn28_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn28_Prop1 = {
   0x0020 /* first character */
  ,0x0022 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn28_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn28_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn28 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,28 /* height of font  */
  ,28 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTStdCn28_Prop1}
  ,23 /* Baseline */
  ,13 /* Height of lowercase characters */
  ,17 /* Height of capital characters */
};

