/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Std Cn25.c                            *
* Font:        HelveticaNeueLT Std Cn                                *
* Height:      25                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 25                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\WB\MDK5\fonts_all.txt                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn25;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0021[ 15] = { /* code 0021, EXCLAMATION MARK */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0022[  7] = { /* code 0022, QUOTATION MARK */
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0025[ 30] = { /* code 0025, PERCENT SIGN */
  _XXXX___,__XXX___,
  XX__XX__,__XX____,
  XX__XX__,_XX_____,
  XX__XX__,_XX_____,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX_X,X_______,
  _XXXX__X,X_______,
  ______XX,__XXXX__,
  _____XX_,_XX__XX_,
  _____XX_,_XX__XX_,
  ____XX__,_XX__XX_,
  ____XX__,_XX__XX_,
  ___XX___,_XX__XX_,
  __XXX___,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0028[ 19] = { /* code 0028, LEFT PARENTHESIS */
  ___XX___,
  __XXX___,
  __XX____,
  _XXX____,
  _XX_____,
  _XX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  _XX_____,
  _XX_____,
  _XXX____,
  __XX____,
  __XXX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0029[ 19] = { /* code 0029, RIGHT PARENTHESIS */
  XX______,
  XXX_____,
  _XX_____,
  _XXX____,
  __XX____,
  __XX____,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XX____,
  __XX____,
  _XXX____,
  _XX_____,
  XXX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_002D[  2] = { /* code 002D, HYPHEN-MINUS */
  XXXXXX__,
  XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_002E[  3] = { /* code 002E, FULL STOP */
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_002F[ 15] = { /* code 002F, SOLIDUS */
  _____XX_,
  ____XX__,
  ____XX__,
  ____XX__,
  ___XXX__,
  ___XX___,
  ___XX___,
  __XXX___,
  __XX____,
  __XX____,
  _XXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0030[ 30] = { /* code 0030, DIGIT ZERO */
  ___XXXXX,________,
  _XXX__XX,X_______,
  _XX____X,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,X_______,
  _XXX__XX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0031[ 15] = { /* code 0031, DIGIT ONE */
  ____XX__,
  ___XXX__,
  __XXXX__,
  XXXXXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0032[ 30] = { /* code 0032, DIGIT TWO */
  __XXXXX_,________,
  _XXX__XX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  ____XXXX,________,
  ___XXXX_,________,
  __XXXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXX____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0033[ 30] = { /* code 0033, DIGIT THREE */
  ___XXXX_,________,
  __XX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  ______XX,X_______,
  ______XX,________,
  _____XXX,________,
  ___XXXXX,X_______,
  ______XX,X_______,
  _______X,XX______,
  _______X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXX__XX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0034[ 30] = { /* code 0034, DIGIT FOUR */
  _____XXX,X_______,
  _____XXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXXXX,X_______,
  ___XX_XX,X_______,
  __XX__XX,X_______,
  _XXX__XX,X_______,
  _XX___XX,X_______,
  XX____XX,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0035[ 30] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _XX_____,________,
  _XX_____,________,
  _XX_____,________,
  XXX_XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  XXX____X,XX______,
  XXXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0036[ 30] = { /* code 0036, DIGIT SIX */
  ___XXXXX,________,
  __XX___X,X_______,
  _XX____X,XX______,
  XXX_____,________,
  XXX_____,________,
  XXX_XXXX,________,
  XXXXXXXX,X_______,
  XXXX__XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XX____X,XX______,
  _XXX__XX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0037[ 30] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0038[ 30] = { /* code 0038, DIGIT EIGHT */
  ___XXXX_,________,
  __XX__XX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XX__XX,________,
  ___XXXXX,________,
  _XXX__XX,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXX__XX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0039[ 30] = { /* code 0039, DIGIT NINE */
  __XXXXXX,________,
  _XXX__XX,X_______,
  XXX____X,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXXX__XX,XX______,
  _XXXXXXX,XX______,
  __XXXX_X,XX______,
  _______X,XX______,
  _______X,XX______,
  _XXX___X,X_______,
  _XXX__XX,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_003A[ 11] = { /* code 003A, COLON */
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0040[ 30] = { /* code 0040, COMMERCIAL AT */
  _____XXX,XX______,
  ___XX___,__XXX___,
  __XX____,___XXX__,
  _XX__XXX,X_XXXX__,
  _XX_XXXX,XXXX_XX_,
  XX__XX__,XXX__XX_,
  XX_XX___,_XX__XX_,
  XX_XX___,_XX__XX_,
  XX_XX___,XXX__X__,
  XX_XX___,XX__XX__,
  _XX_XXXX,XXXXX___,
  _XX_XXX_,_XX_____,
  __XX____,___XXX__,
  ___XX___,__XXX___,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0041[ 30] = { /* code 0041, LATIN CAPITAL LETTER A */
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ___XX__X,X_______,
  __XXX__X,XX______,
  __XXX__X,XX______,
  __XXX__X,XX______,
  __XXX__X,XX______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  XXX_____,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0042[ 30] = { /* code 0042, LATIN CAPITAL LETTER B */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX___XX,XX______,
  XXXXXXXX,X_______,
  XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0043[ 30] = { /* code 0043, LATIN CAPITAL LETTER C */
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX__XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXX__XX,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0044[ 30] = { /* code 0044, LATIN CAPITAL LETTER D */
  XXXXXXX_,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,X_______,
  XXX___XX,X_______,
  XXXXXXXX,X_______,
  XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0045[ 30] = { /* code 0045, LATIN CAPITAL LETTER E */
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0046[ 15] = { /* code 0046, LATIN CAPITAL LETTER F */
  XXXXXXXX,
  XXXXXXXX,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXXXXXXX,
  XXXXXXXX,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0047[ 30] = { /* code 0047, LATIN CAPITAL LETTER G */
  ___XXXXX,________,
  _XXXXXXX,X_______,
  _XXX__XX,XX______,
  _XX____X,XX______,
  XXX____X,XX______,
  XXX_____,________,
  XXX_____,________,
  XXX__XXX,XX______,
  XXX__XXX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXX__XX,XX______,
  _XXXXXXX,XX______,
  __XXXXX_,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0048[ 30] = { /* code 0048, LATIN CAPITAL LETTER H */
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0049[ 15] = { /* code 0049, LATIN CAPITAL LETTER I */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_004A[ 30] = { /* code 004A, LATIN CAPITAL LETTER J */
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_004B[ 30] = { /* code 004B, LATIN CAPITAL LETTER K */
  XXX____X,XX______,
  XXX___XX,X_______,
  XXX__XXX,X_______,
  XXX__XXX,________,
  XXX_XXX_,________,
  XXXXXXX_,________,
  XXXXXX__,________,
  XXXXXXX_,________,
  XXXXXXX_,________,
  XXXXXXXX,________,
  XXX__XXX,________,
  XXX__XXX,X_______,
  XXX___XX,X_______,
  XXX___XX,XX______,
  XXX____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_004C[ 15] = { /* code 004C, LATIN CAPITAL LETTER L */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXXXXXXX,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_004D[ 30] = { /* code 004D, LATIN CAPITAL LETTER M */
  XXXXX___,_XXXXX__,
  XXXXX___,_XXXXX__,
  XXXXX___,_XXXXX__,
  XXXXX___,_XXXXX__,
  XXXXXX__,XXXXXX__,
  XXX_XX__,XX_XXX__,
  XXX_XX__,XX_XXX__,
  XXX_XX__,XX_XXX__,
  XXX_XXXX,XX_XXX__,
  XXX_XXXX,XX_XXX__,
  XXX__XXX,X__XXX__,
  XXX__XXX,X__XXX__,
  XXX__XXX,X__XXX__,
  XXX__XXX,X__XXX__,
  XXX___XX,___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_004E[ 30] = { /* code 004E, LATIN CAPITAL LETTER N */
  XXXX___X,XX______,
  XXXX___X,XX______,
  XXXX___X,XX______,
  XXXXX__X,XX______,
  XXXXX__X,XX______,
  XXXXX__X,XX______,
  XXX_XX_X,XX______,
  XXX_XX_X,XX______,
  XXX_XX_X,XX______,
  XXX__XXX,XX______,
  XXX__XXX,XX______,
  XXX__XXX,XX______,
  XXX___XX,XX______,
  XXX___XX,XX______,
  XXX___XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_004F[ 30] = { /* code 004F, LATIN CAPITAL LETTER O */
  ___XXXX_,________,
  _XXXXXXX,X_______,
  _XXX__XX,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0050[ 30] = { /* code 0050, LATIN CAPITAL LETTER P */
  XXXXXXX_,________,
  XXXXXXXX,________,
  XXX__XXX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX__XXX,X_______,
  XXXXXXXX,________,
  XXXXXXX_,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0051[ 34] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ___XXXX_,________,
  _XXXXXXX,X_______,
  _XXX__XX,X_______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  ___XXXXX,XX______,
  ________,XX______,
  ________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0052[ 30] = { /* code 0052, LATIN CAPITAL LETTER R */
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX___XX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXX___XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0053[ 30] = { /* code 0053, LATIN CAPITAL LETTER S */
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX____,________,
  _XXXX___,________,
  __XXXXX_,________,
  ___XXXXX,X_______,
  ____XXXX,X_______,
  ______XX,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  XXX____X,XX______,
  _XXXXXXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0054[ 30] = { /* code 0054, LATIN CAPITAL LETTER T */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0055[ 30] = { /* code 0055, LATIN CAPITAL LETTER U */
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0056[ 30] = { /* code 0056, LATIN CAPITAL LETTER V */
  XXX_____,XXX_____,
  XXXX___X,XXX_____,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XX_XX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0057[ 30] = { /* code 0057, LATIN CAPITAL LETTER W */
  XXX___XX,XX___XXX,
  XXX___XX,XX___XXX,
  _XX___XX,XX___XX_,
  _XXX__XX,XX__XXX_,
  _XXX__XX,XX__XXX_,
  _XXX__XX,XX__XXX_,
  _XXX__XX,XX__XXX_,
  __XX_XX_,_XX_XX__,
  __XX_XX_,_XX_XX__,
  __XX_XX_,_XX_XX__,
  __XXXXX_,_XXXXX__,
  __XXXXX_,_XXXXX__,
  __XXXXX_,_XXXXX__,
  ___XXXX_,_XXXX___,
  ___XXX__,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0058[ 30] = { /* code 0058, LATIN CAPITAL LETTER X */
  XXXX___X,XXX_____,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XXXXX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ___XXXXX,________,
  ___XXXXX,________,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  XXXX___X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0059[ 30] = { /* code 0059, LATIN CAPITAL LETTER Y */
  XXXX___X,XXX_____,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XX_XX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_005A[ 30] = { /* code 005A, LATIN CAPITAL LETTER Z */
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _____XXX,X_______,
  _____XXX,________,
  ____XXXX,________,
  ____XXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXXX__,________,
  __XXX___,________,
  _XXXX___,________,
  _XXX____,________,
  XXXX____,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_005C[ 15] = { /* code 005C, REVERSE SOLIDUS */
  XX______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXX____,
  __XX____,
  __XX____,
  __XXX___,
  ___XX___,
  ___XX___,
  ___XXX__,
  ____XX__,
  ____XX__,
  ____XX__,
  _____XX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_005F[  2] = { /* code 005F, LOW LINE */
  XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0061[ 22] = { /* code 0061, LATIN SMALL LETTER A */
  __XXXXXX,________,
  _XX___XX,X_______,
  _XX___XX,X_______,
  ______XX,X_______,
  ___XXXXX,X_______,
  _XXXXXXX,X_______,
  XXXX__XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX__XXX,X_______,
  _XXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0062[ 30] = { /* code 0062, LATIN SMALL LETTER B */
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_XXX_,________,
  XXXXXXXX,________,
  XXXX_XXX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXX_XXX,________,
  XXX_XXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0063[ 11] = { /* code 0063, LATIN SMALL LETTER C */
  __XXXX__,
  _XXXXXX_,
  _XX__XXX,
  XXX__XXX,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX__XXX,
  XXX__XXX,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0064[ 30] = { /* code 0064, LATIN SMALL LETTER D */
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  __XXX_XX,X_______,
  _XXXXXXX,X_______,
  _XXX_XXX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXX_XXX,X_______,
  __XXX_XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0065[ 11] = { /* code 0065, LATIN SMALL LETTER E */
  __XXXX__,
  _XX__XX_,
  XXX__XXX,
  XXX__XXX,
  XXXXXXXX,
  XXX_____,
  XXX_____,
  XXX__XXX,
  XXX__XX_,
  _XX__XX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0066[ 15] = { /* code 0066, LATIN SMALL LETTER F */
  __XXXX__,
  _XXXXX__,
  _XXX____,
  _XXX____,
  XXXXXX__,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0067[ 30] = { /* code 0067, LATIN SMALL LETTER G */
  __XXX_XX,X_______,
  _XXX_XXX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX__XXX,X_______,
  _XXXXXXX,X_______,
  __XXX_XX,X_______,
  ______XX,X_______,
  XXX___XX,X_______,
  XXX__XXX,________,
  _XXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0068[ 30] = { /* code 0068, LATIN SMALL LETTER H */
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_XXXX,________,
  XXXXXXXX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0069[ 15] = { /* code 0069, LATIN SMALL LETTER I */
  XXX_____,
  XXX_____,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_006A[ 19] = { /* code 006A, LATIN SMALL LETTER J */
  __XXX___,
  __XXX___,
  ________,
  ________,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  XXXXX___,
  XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_006B[ 30] = { /* code 006B, LATIN SMALL LETTER K */
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX___XX,X_______,
  XXX__XXX,________,
  XXX_XXX_,________,
  XXXXXX__,________,
  XXXXXX__,________,
  XXXXXXX_,________,
  XXXXXXX_,________,
  XXX__XXX,________,
  XXX__XXX,________,
  XXX___XX,X_______,
  XXX___XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_006C[ 15] = { /* code 006C, LATIN SMALL LETTER L */
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_006D[ 22] = { /* code 006D, LATIN SMALL LETTER M */
  XXX_XXXX,__XXXX__,
  XXXXXXXX,XXXXXXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_006E[ 22] = { /* code 006E, LATIN SMALL LETTER N */
  XXX_XXXX,________,
  XXXX__XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_006F[ 22] = { /* code 006F, LATIN SMALL LETTER O */
  __XXXXX_,________,
  _XXX_XXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXX_XXX,________,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0070[ 30] = { /* code 0070, LATIN SMALL LETTER P */
  XXX_XXX_,________,
  XXXX_XXX,________,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXX_XXX,________,
  XXXXXXXX,________,
  XXX_XXX_,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0071[ 30] = { /* code 0071, LATIN SMALL LETTER Q */
  __XXX_XX,X_______,
  _XXX_XXX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXX_XXX,X_______,
  _XXXXXXX,X_______,
  __XXX_XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0072[ 11] = { /* code 0072, LATIN SMALL LETTER R */
  XXX_XX__,
  XXXXXX__,
  XXXX____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0073[ 22] = { /* code 0073, LATIN SMALL LETTER S */
  __XXXXX_,________,
  XXX___XX,________,
  XXX___XX,________,
  XXXX____,________,
  _XXXXX__,________,
  __XXXXXX,________,
  ___XXXXX,________,
  ______XX,X_______,
  _XX___XX,X_______,
  _XX___XX,X_______,
  __XXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0074[ 14] = { /* code 0074, LATIN SMALL LETTER T */
  _XXX____,
  _XXX____,
  _XXX____,
  XXXXXX__,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXXXX__,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0075[ 22] = { /* code 0075, LATIN SMALL LETTER U */
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXX__XXX,X_______,
  _XXXX_XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0076[ 22] = { /* code 0076, LATIN SMALL LETTER V */
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXX__XX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  __XX_XX_,________,
  __XXXXX_,________,
  __XXXXX_,________,
  ___XXXX_,________,
  ___XXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0077[ 22] = { /* code 0077, LATIN SMALL LETTER W */
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  _XXX_XXX,XX__XX__,
  _XXX_XX_,XX_XXX__,
  _XXX_XX_,XX_XXX__,
  _XXX_XX_,XX_XXX__,
  __XX_XX_,XX_XX___,
  __XX_XX_,XXXXX___,
  __XXXX__,_XXXX___,
  __XXXX__,_XXXX___,
  ___XXX__,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0078[ 22] = { /* code 0078, LATIN SMALL LETTER X */
  XXX___XX,X_______,
  _XXX_XXX,________,
  _XXX_XXX,________,
  __XXXXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXXXX_,________,
  __XX_XX_,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  XXX___XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_0079[ 30] = { /* code 0079, LATIN SMALL LETTER Y */
  XXX___XX,X_______,
  XXX___XX,X_______,
  _XXX__XX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  __XX_XXX,________,
  __XX_XX_,________,
  __XXXXX_,________,
  __XXXXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  _XXXX___,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_007A[ 11] = { /* code 007A, LATIN SMALL LETTER Z */
  XXXXXXXX,
  XXXXXXXX,
  ____XXXX,
  ____XXX_,
  ___XXX__,
  __XXXX__,
  __XXX___,
  _XXX____,
  XXXX____,
  XXXXXXXX,
  XXXXXXXX};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTStdCn25_00B0[  6] = { /* code 00B0, DEGREE SIGN */
  __XXX___,
  _X___X__,
  XX___XX_,
  XX___XX_,
  XX___X__,
  __XXX___};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHelveticaNeueLTStdCn25_CharInfo[76] = {
   {   1,   1,   0,  20,  6, acGUI_FontHelveticaNeueLTStdCn25_0020 } /* code 0020, SPACE */
  ,{   3,  15,   2,   5,   6, acGUI_FontHelveticaNeueLTStdCn25_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   6,   7,   2,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0022 } /* code 0022, QUOTATION MARK */
  ,{  15,  15,   1,   5,  16, acGUI_FontHelveticaNeueLTStdCn25_0025 } /* code 0025, PERCENT SIGN */
  ,{   5,  19,   1,   5,   6, acGUI_FontHelveticaNeueLTStdCn25_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   5,  19,   0,   5,   6, acGUI_FontHelveticaNeueLTStdCn25_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   6,   2,   1,  13,   8, acGUI_FontHelveticaNeueLTStdCn25_002D } /* code 002D, HYPHEN-MINUS */
  ,{   3,   3,   1,  17,   5, acGUI_FontHelveticaNeueLTStdCn25_002E } /* code 002E, FULL STOP */
  ,{   7,  15,   0,   5,   7, acGUI_FontHelveticaNeueLTStdCn25_002F } /* code 002F, SOLIDUS */
  ,{  10,  15,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0030 } /* code 0030, DIGIT ZERO */
  ,{   6,  15,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0031 } /* code 0031, DIGIT ONE */
  ,{   9,  15,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0032 } /* code 0032, DIGIT TWO */
  ,{  10,  15,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  15,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0034 } /* code 0034, DIGIT FOUR */
  ,{  10,  15,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0035 } /* code 0035, DIGIT FIVE */
  ,{  10,  15,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  15,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0037 } /* code 0037, DIGIT SEVEN */
  ,{  10,  15,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0038 } /* code 0038, DIGIT EIGHT */
  ,{  10,  15,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0039 } /* code 0039, DIGIT NINE */
  ,{   3,  11,   1,   9,   5, acGUI_FontHelveticaNeueLTStdCn25_003A } /* code 003A, COLON */
  ,{  15,  15,   1,   5,  17, acGUI_FontHelveticaNeueLTStdCn25_0040 } /* code 0040, COMMERCIAL AT */
  ,{  12,  15,   0,   5,  12, acGUI_FontHelveticaNeueLTStdCn25_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  10,  15,   1,   5,  12, acGUI_FontHelveticaNeueLTStdCn25_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  10,  15,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  10,  15,   1,   5,  12, acGUI_FontHelveticaNeueLTStdCn25_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   9,  15,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   8,  15,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  10,  15,   1,   5,  12, acGUI_FontHelveticaNeueLTStdCn25_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  10,  15,   1,   5,  12, acGUI_FontHelveticaNeueLTStdCn25_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   3,  15,   1,   5,   5, acGUI_FontHelveticaNeueLTStdCn25_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   9,  15,   0,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  11,  15,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   8,  15,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  14,  15,   1,   5,  16, acGUI_FontHelveticaNeueLTStdCn25_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  10,  15,   1,   5,  12, acGUI_FontHelveticaNeueLTStdCn25_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  10,  15,   1,   5,  12, acGUI_FontHelveticaNeueLTStdCn25_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   9,  15,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  10,  17,   1,   5,  12, acGUI_FontHelveticaNeueLTStdCn25_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  11,  15,   1,   5,  12, acGUI_FontHelveticaNeueLTStdCn25_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  10,  15,   0,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   9,  15,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   9,  15,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  11,  15,   0,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  16,  15,   0,   5,  16, acGUI_FontHelveticaNeueLTStdCn25_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  11,  15,   0,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  11,  15,   0,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   9,  15,   1,   5,  10, acGUI_FontHelveticaNeueLTStdCn25_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   7,  15,   0,   5,   7, acGUI_FontHelveticaNeueLTStdCn25_005C } /* code 005C, REVERSE SOLIDUS */
  ,{  11,   1,   0,  22,  11, acGUI_FontHelveticaNeueLTStdCn25_005F } /* code 005F, LOW LINE */
  ,{   9,  11,   0,   9,  10, acGUI_FontHelveticaNeueLTStdCn25_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   9,  15,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   8,  11,   1,   9,  10, acGUI_FontHelveticaNeueLTStdCn25_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   9,  15,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   8,  11,   1,   9,  10, acGUI_FontHelveticaNeueLTStdCn25_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   6,  15,   1,   5,   6, acGUI_FontHelveticaNeueLTStdCn25_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   9,  15,   1,   9,  11, acGUI_FontHelveticaNeueLTStdCn25_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   9,  15,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   3,  15,   1,   5,   5, acGUI_FontHelveticaNeueLTStdCn25_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   5,  19,  -1,   5,   5, acGUI_FontHelveticaNeueLTStdCn25_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{  10,  15,   1,   5,  11, acGUI_FontHelveticaNeueLTStdCn25_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   3,  15,   1,   5,   5, acGUI_FontHelveticaNeueLTStdCn25_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{  15,  11,   1,   9,  16, acGUI_FontHelveticaNeueLTStdCn25_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   9,  11,   1,   9,  11, acGUI_FontHelveticaNeueLTStdCn25_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   9,  11,   1,   9,  10, acGUI_FontHelveticaNeueLTStdCn25_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   9,  15,   1,   9,  11, acGUI_FontHelveticaNeueLTStdCn25_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   9,  15,   1,   9,  11, acGUI_FontHelveticaNeueLTStdCn25_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   6,  11,   1,   9,   7, acGUI_FontHelveticaNeueLTStdCn25_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   9,  11,   0,   9,   9, acGUI_FontHelveticaNeueLTStdCn25_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   6,  14,   1,   6,   6, acGUI_FontHelveticaNeueLTStdCn25_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   9,  11,   1,   9,  11, acGUI_FontHelveticaNeueLTStdCn25_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   9,  11,   0,   9,   9, acGUI_FontHelveticaNeueLTStdCn25_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{  15,  11,   0,   9,  15, acGUI_FontHelveticaNeueLTStdCn25_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   9,  11,   0,   9,  10, acGUI_FontHelveticaNeueLTStdCn25_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   9,  15,   0,   9,   9, acGUI_FontHelveticaNeueLTStdCn25_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   8,  11,   0,   9,   9, acGUI_FontHelveticaNeueLTStdCn25_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   7,   6,   1,   5,   8, acGUI_FontHelveticaNeueLTStdCn25_00B0 } /* code 00B0, DEGREE SIGN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn25_Prop9 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn25_CharInfo[ 75] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn25_Prop8 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn25_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn25_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn25_Prop7 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn25_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn25_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn25_Prop6 = {
   0x005C /* first character */
  ,0x005C /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn25_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn25_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn25_Prop5 = {
   0x0040 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn25_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn25_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn25_Prop4 = {
   0x002D /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn25_CharInfo[  6] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn25_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn25_Prop3 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn25_CharInfo[  4] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn25_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn25_Prop2 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn25_CharInfo[  3] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn25_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHelveticaNeueLTStdCn25_Prop1 = {
   0x0020 /* first character */
  ,0x0022 /* last character  */
  ,&GUI_FontHelveticaNeueLTStdCn25_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTStdCn25_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTStdCn25 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,25 /* height of font  */
  ,25 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTStdCn25_Prop1}
  ,20 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,15 /* Height of capital characters */
};

