/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: TradeGothicCn19.c                                     *
* Font:        Trade Gothic LT Std Cn                                *
* Height:      19                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 19                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: C:\Users\litoku\Desktop\fontsmall.txt           *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontTradeGothicCn19;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0020[ 19] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0022[ 19] = { /* code 0022, QUOTATION MARK */
  ________,
  ________,
  ________,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0025[ 38] = { /* code 0025, PERCENT SIGN */
  ________,________,
  ________,________,
  ________,________,
  __XXX___,_XX_____,
  _X___X__,XX______,
  _X___X__,X_______,
  _X___X_X,X_______,
  _X___X_X,________,
  __XXX__X,________,
  ______X_,________,
  _____X__,XXX_____,
  ____XX_X,___X____,
  ____X__X,___X____,
  ___XX__X,___X____,
  __XX____,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0028[ 19] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  ________,
  ________,
  __XX____,
  __X_____,
  _XX_____,
  _X______,
  XX______,
  XX______,
  XX______,
  XX______,
  XX______,
  _X______,
  _XX_____,
  _XX_____,
  __XX____,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0029[ 19] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _XX_____,
  __X_____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __X_____,
  _XX_____,
  _XX_____,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_002D[ 19] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_002E[ 19] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0030[ 19] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0031[ 19] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ___XX___,
  __XXX___,
  __XXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0032[ 19] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  ____XX__,
  ____XX__,
  ____X___,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0033[ 19] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  ____XX__,
  ____XX__,
  ___XX___,
  ____XX__,
  ____XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0034[ 19] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  ____XX__,
  ___XXX__,
  ___XXX__,
  ___XXX__,
  __X_XX__,
  __X_XX__,
  _XX_XX__,
  _X__XX__,
  _XXXXXX_,
  ____XX__,
  ____XX__,
  ____XX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0035[ 19] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXX___,
  _XX_XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0036[ 19] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_____,
  _XX_____,
  _XXXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0037[ 19] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXX__,
  ____XX__,
  ____XX__,
  ____X___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___X____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0038[ 19] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0039[ 19] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXXX__,
  ____XX__,
  ____XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_003A[ 19] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0040[ 38] = { /* code 0040, COMMERCIAL AT */
  ________,________,
  ________,________,
  ________,________,
  _____XXX,X_______,
  ___XX___,_XX_____,
  __X_____,___X____,
  _XX__XXX,_X_X____,
  XX__XX__,XX_X____,
  XX_XX___,X__X____,
  XX_XX___,X__X____,
  _X_XX__X,X_X_____,
  _X__XXX_,XX______,
  __X_____,___X____,
  ___XX___,_XX_____,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0041[ 19] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  ________,
  __XXX___,
  __XXX___,
  __X_X___,
  __X_X___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XXXXX__,
  _X___X__,
  XX___XX_,
  XX___XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0042[ 19] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0043[ 19] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0044[ 19] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0045[ 19] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0046[ 19] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXX__,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0047[ 19] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX_____,
  _XX_____,
  _XX_XXX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0048[ 19] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,
  ________,
  ________,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXXX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0049[ 19] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_004A[ 19] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_004B[ 19] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,
  ________,
  ________,
  _XX__XX_,
  _XX_XX__,
  _XX_XX__,
  _XXXX___,
  _XXXX___,
  _XXXX___,
  _XXXXX__,
  _XX_XX__,
  _XX_XX__,
  _XX__X__,
  _XX__XX_,
  _XX__XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_004C[ 19] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_004D[ 38] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXX_XX,X_______,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  _XX_XX_X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_004E[ 19] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,
  ________,
  ________,
  _XX__XX_,
  _XX__XX_,
  _XXX_XX_,
  _XXX_XX_,
  _XXX_XX_,
  _XXX_XX_,
  _XX_XXX_,
  _XX_XXX_,
  _XX_XXX_,
  _XX_XXX_,
  _XX__XX_,
  _XX__XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_004F[ 19] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0050[ 19] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0051[ 19] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX_XXX_,
  _XX_XXX_,
  _XX_XXX_,
  __XXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0052[ 19] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XXXXX__,
  _XX_XX__,
  _XX_XX__,
  _XX__X__,
  _XX__XX_,
  _XX__XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0053[ 19] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX_____,
  _XX_____,
  __XX____,
  __XXX___,
  ___XXX__,
  ____XX__,
  _____XX_,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0054[ 19] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  XXXXXX__,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0055[ 19] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,
  ________,
  ________,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0056[ 19] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,
  ________,
  ________,
  XX___XX_,
  XX___XX_,
  _X___X__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __X_X___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0057[ 38] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,________,
  ________,________,
  ________,________,
  XX__XX__,XX______,
  XX__XX__,XX______,
  XX__XX__,XX______,
  _X__XX__,X_______,
  _XX_XXX_,X_______,
  _XX_XXX_,X_______,
  _XXXX_XX,X_______,
  _XXX__XX,X_______,
  __XX__XX,X_______,
  __XX__XX,________,
  __XX__XX,________,
  __XX__XX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0058[ 19] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,
  ________,
  ________,
  XX___XX_,
  _XX_XX__,
  _XX_XX__,
  __X_X___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  XX___XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0059[ 19] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,
  ________,
  ________,
  _XX__XX_,
  _XX__XX_,
  __X__X__,
  __XX_X__,
  __XXXX__,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_005A[ 19] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,
  ________,
  ________,
  _XXXXX__,
  _____X__,
  ____XX__,
  ____X___,
  ____X___,
  ___XX___,
  ___X____,
  __XX____,
  __XX____,
  __XX____,
  _XX_____,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_005F[ 19] = { /* code 005F, LOW LINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXXX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0061[ 19] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  ____XX__,
  __XXXX__,
  _XX_XX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0062[ 19] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0063[ 19] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_____,
  _XX_____,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0064[ 19] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ________,
  ________,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  __XXXX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0065[ 19] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XXXXX__,
  _XX_____,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0066[ 19] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  ________,
  __XX____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0067[ 19] = { /* code 0067, LATIN SMALL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX_X_,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  XX__XX__,
  _XXXX___,
  XX______,
  XXXXXX__,
  XX___XX_,
  XX___XX_,
  _XXXXX__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0068[ 19] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXXXX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0069[ 19] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_006A[ 19] = { /* code 006A, LATIN SMALL LETTER J */
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_006B[ 19] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX__XX_,
  _XX_XX__,
  _XXXX___,
  _XXXX___,
  _XX_XX__,
  _XX_XX__,
  _XX__X__,
  _XX__XX_,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_006C[ 19] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_006D[ 38] = { /* code 006D, LATIN SMALL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  _XX__XX_,_XX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_006E[ 19] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_006F[ 19] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0070[ 19] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0071[ 19] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  __XXXX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0072[ 19] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0073[ 19] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  XX______,
  _XXX____,
  __XXX___,
  ____XX__,
  XX__XX__,
  _XXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0074[ 19] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  XXXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  __XX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0075[ 19] = { /* code 0075, LATIN SMALL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XX_XX__,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0076[ 19] = { /* code 0076, LATIN SMALL LETTER V */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  XX__XX__,
  _X__X___,
  _XX_X___,
  _XXXX___,
  _XXXX___,
  __XX____,
  __XX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0077[ 38] = { /* code 0077, LATIN SMALL LETTER W */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XX__X__X,X_______,
  XX_XX__X,________,
  _X_XXX_X,________,
  _X_X_X_X,________,
  _XXX_XXX,________,
  _XXX_XX_,________,
  __XX_XX_,________,
  __X__XX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0078[ 19] = { /* code 0078, LATIN SMALL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  _XXXX___,
  _XXXX___,
  __XX____,
  __XX____,
  _XXXX___,
  _XX_X___,
  XX__XX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_0079[ 19] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX__XX__,
  XX__XX__,
  _X__X___,
  _XX_X___,
  _XXXX___,
  _XXXX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  _XX_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_007A[ 19] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  ____XX__,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  _XX_____,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontTradeGothicCn19_00B0[ 19] = { /* code 00B0, DEGREE SIGN */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontTradeGothicCn19_CharInfo[73] = {
   {   4,   4,  1, acGUI_FontTradeGothicCn19_0020 } /* code 0020 */
  ,{   5,   5,  1, acGUI_FontTradeGothicCn19_0022 } /* code 0022 */
  ,{  12,  12,  2, acGUI_FontTradeGothicCn19_0025 } /* code 0025 */
  ,{   4,   4,  1, acGUI_FontTradeGothicCn19_0028 } /* code 0028 */
  ,{   4,   4,  1, acGUI_FontTradeGothicCn19_0029 } /* code 0029 */
  ,{   5,   5,  1, acGUI_FontTradeGothicCn19_002D } /* code 002D */
  ,{   4,   4,  1, acGUI_FontTradeGothicCn19_002E } /* code 002E */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0030 } /* code 0030 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0031 } /* code 0031 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0032 } /* code 0032 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0033 } /* code 0033 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0034 } /* code 0034 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0035 } /* code 0035 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0036 } /* code 0036 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0037 } /* code 0037 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0038 } /* code 0038 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0039 } /* code 0039 */
  ,{   4,   4,  1, acGUI_FontTradeGothicCn19_003A } /* code 003A */
  ,{  13,  13,  2, acGUI_FontTradeGothicCn19_0040 } /* code 0040 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_0044 } /* code 0044 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0045 } /* code 0045 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_0047 } /* code 0047 */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_0048 } /* code 0048 */
  ,{   4,   4,  1, acGUI_FontTradeGothicCn19_0049 } /* code 0049 */
  ,{   4,   4,  1, acGUI_FontTradeGothicCn19_004A } /* code 004A */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_004B } /* code 004B */
  ,{   6,   6,  1, acGUI_FontTradeGothicCn19_004C } /* code 004C */
  ,{  10,  10,  2, acGUI_FontTradeGothicCn19_004D } /* code 004D */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_004E } /* code 004E */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_0051 } /* code 0051 */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_0052 } /* code 0052 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0053 } /* code 0053 */
  ,{   6,   6,  1, acGUI_FontTradeGothicCn19_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_0055 } /* code 0055 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0056 } /* code 0056 */
  ,{  11,  11,  2, acGUI_FontTradeGothicCn19_0057 } /* code 0057 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0058 } /* code 0058 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0059 } /* code 0059 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_005A } /* code 005A */
  ,{   8,   8,  1, acGUI_FontTradeGothicCn19_005F } /* code 005F */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0061 } /* code 0061 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0062 } /* code 0062 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0063 } /* code 0063 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0064 } /* code 0064 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0065 } /* code 0065 */
  ,{   4,   4,  1, acGUI_FontTradeGothicCn19_0066 } /* code 0066 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0067 } /* code 0067 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0068 } /* code 0068 */
  ,{   4,   4,  1, acGUI_FontTradeGothicCn19_0069 } /* code 0069 */
  ,{   4,   4,  1, acGUI_FontTradeGothicCn19_006A } /* code 006A */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_006B } /* code 006B */
  ,{   4,   4,  1, acGUI_FontTradeGothicCn19_006C } /* code 006C */
  ,{  11,  11,  2, acGUI_FontTradeGothicCn19_006D } /* code 006D */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_006E } /* code 006E */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_006F } /* code 006F */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0070 } /* code 0070 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0071 } /* code 0071 */
  ,{   5,   5,  1, acGUI_FontTradeGothicCn19_0072 } /* code 0072 */
  ,{   6,   6,  1, acGUI_FontTradeGothicCn19_0073 } /* code 0073 */
  ,{   4,   4,  1, acGUI_FontTradeGothicCn19_0074 } /* code 0074 */
  ,{   7,   7,  1, acGUI_FontTradeGothicCn19_0075 } /* code 0075 */
  ,{   6,   6,  1, acGUI_FontTradeGothicCn19_0076 } /* code 0076 */
  ,{   9,   9,  2, acGUI_FontTradeGothicCn19_0077 } /* code 0077 */
  ,{   6,   6,  1, acGUI_FontTradeGothicCn19_0078 } /* code 0078 */
  ,{   6,   6,  1, acGUI_FontTradeGothicCn19_0079 } /* code 0079 */
  ,{   6,   6,  1, acGUI_FontTradeGothicCn19_007A } /* code 007A */
  ,{   6,   6,  1, acGUI_FontTradeGothicCn19_00B0 } /* code 00B0 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTradeGothicCn19_Prop10 = {
   0x00B0 /* first character */
  ,0x00B0 /* last character  */
  ,&GUI_FontTradeGothicCn19_CharInfo[ 72] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTradeGothicCn19_Prop9 = {
   0x0061 /* first character */
  ,0x007A /* last character  */
  ,&GUI_FontTradeGothicCn19_CharInfo[ 46] /* address of first character */
  ,&GUI_FontTradeGothicCn19_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTradeGothicCn19_Prop8 = {
   0x005F /* first character */
  ,0x005F /* last character  */
  ,&GUI_FontTradeGothicCn19_CharInfo[ 45] /* address of first character */
  ,&GUI_FontTradeGothicCn19_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTradeGothicCn19_Prop7 = {
   0x0040 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontTradeGothicCn19_CharInfo[ 18] /* address of first character */
  ,&GUI_FontTradeGothicCn19_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTradeGothicCn19_Prop6 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontTradeGothicCn19_CharInfo[  7] /* address of first character */
  ,&GUI_FontTradeGothicCn19_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTradeGothicCn19_Prop5 = {
   0x002D /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontTradeGothicCn19_CharInfo[  5] /* address of first character */
  ,&GUI_FontTradeGothicCn19_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTradeGothicCn19_Prop4 = {
   0x0028 /* first character */
  ,0x0029 /* last character  */
  ,&GUI_FontTradeGothicCn19_CharInfo[  3] /* address of first character */
  ,&GUI_FontTradeGothicCn19_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTradeGothicCn19_Prop3 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontTradeGothicCn19_CharInfo[  2] /* address of first character */
  ,&GUI_FontTradeGothicCn19_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTradeGothicCn19_Prop2 = {
   0x0022 /* first character */
  ,0x0022 /* last character  */
  ,&GUI_FontTradeGothicCn19_CharInfo[  1] /* address of first character */
  ,&GUI_FontTradeGothicCn19_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontTradeGothicCn19_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontTradeGothicCn19_CharInfo[  0] /* address of first character */
  ,&GUI_FontTradeGothicCn19_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontTradeGothicCn19 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,19 /* height of font  */
  ,19 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontTradeGothicCn19_Prop1}
  ,15 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,12 /* Height of capital characters */
};

